# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'municipality',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('municipality', models.CharField(blank=True, max_length=255, null=True, verbose_name='Savivaldybė')),
                ('region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regionas')),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True, verbose_name='Pavadinimas')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresas')),
                ('company_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Registracijos numeris')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Elektroninis paštas')),
                ('is_public', models.BooleanField(blank=True, null=True, verbose_name='Organizacija viešinama')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono numeris')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tinklalapis')),
                ('kind', models.CharField(choices=[('gov', 'Valstybinė įstaiga'), ('com', 'Verslo organizacija'), ('org', 'Nepelno ir nevalstybinė organizacija')], default='org', max_length=36, verbose_name='Tipas')),
                ('role', models.CharField(blank=True, choices=[('group', 'Grupė'), ('ministry', 'Ministerija'), ('municipality', 'Savivaldybė')], max_length=255, null=True, verbose_name='Vaidmuo')),
                ('publisher', models.BooleanField(default=False, verbose_name='Duomenų atvėrimo paslaugų teikėjas')),
                ('name', models.TextField(blank=True, max_length=255, null=True, unique=True)),
                ('alternative_titles', models.TextField(blank=True, null=True, verbose_name='Alternatyvūs pavadinimai')),
                ('imageuuid', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organization_mapping',
            },
        ),
        migrations.CreateModel(
            name='PublishedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True, verbose_name='Duomenys')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Pavadinimas')),
            ],
            options={
                'verbose_name': 'Ataskaita',
                'verbose_name_plural': 'Ataskaitos',
                'db_table': 'published_report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('coordinator', 'Koordinatorius'), ('manager', 'Tvarkytojas')], max_length=255)),
                ('has_api_access', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'representative',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sukurta')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Modifikuota')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='Identifikatorius')),
                ('text', models.CharField(max_length=100, verbose_name='Tekstas')),
                ('document', models.FileField(upload_to='data/files/templates', verbose_name='Pridėtas dokumentas')),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='RepresentativeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Sukurta')),
                ('document', models.FileField(upload_to='data/files/request_assignments', verbose_name='Pridėtas dokumentas')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono numeris')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='El. paštas')),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'Pateiktas'), ('APPROVED', 'Patvirtintas'), ('REJECTED', 'Atmestas')], default='CREATED', max_length=255, null=True, verbose_name='Būsena')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization', verbose_name='Organizacija')),
            ],
            options={
                'db_table': 'representative_request',
                'managed': True,
            },
        ),
    ]
