# Generated by Django 3.2.13 on 2022-08-12 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True},
        ),
    ]