# Generated by Django 3.2.14 on 2022-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('com', 'Verslo organizacija'), ('org', 'Nepelno ir nevalstybinė organizacija'), ('gov', 'Valstybinė įstaiga')], default='org', max_length=36),
        ),
    ]
