# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_orgs', '0001_initial'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vitrina_classifiers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='representativerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Naudotojas'),
        ),
        migrations.AddField(
            model_name='representative',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='representative',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_orgs.organization'),
        ),
        migrations.AddField(
            model_name='representative',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_organization', to=settings.FILER_IMAGE_MODEL, verbose_name='Logotipas'),
        ),
        migrations.AddField(
            model_name='organization',
            name='jurisdiction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='organization_set', to='vitrina_classifiers.areaofmanagement', verbose_name='Valdymo sritis'),
        ),
        migrations.CreateModel(
            name='PublisherOrganization',
            fields=[
            ],
            options={
                'verbose_name': 'Duomenų atvėrimo paslaugų tiekėjas',
                'verbose_name_plural': 'Duomenų atvėrimo paslaugų tiekėjai',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vitrina_orgs.organization',),
        ),
        migrations.AlterUniqueTogether(
            name='representative',
            unique_together={('content_type', 'object_id', 'user')},
        ),
    ]
