# Generated by Django 3.2.13 on 2022-08-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('gov', 'Valstybinė įstaiga'), ('org', 'Nepelno ir nevalstybinė organizacija'), ('com', 'Verslo organizacija')], default='org', max_length=36),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_set', to='vitrina_orgs.organization'),
        ),
    ]
