# Generated by Django 3.2.25 on 2025-05-23 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0007_alter_dataset_organization'),
        ('vitrina_orgs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('synchronized_at', models.DateTimeField(blank=True, help_text='Nurodoma data, kada paskutįkart buvo bandyta vykdyti sinchronizaciją.', null=True, verbose_name='Paskutinės sinchronizacijos data')),
                ('is_last_sync_successful', models.BooleanField(blank=True, help_text='Nurodoma, ar paskutinė sinchronizacija įvyko sėkmingai t.y. jos metu nekilo klaidų.', null=True, verbose_name='Ar paskutinė sinchronizacija įvyko sėkmingai?')),
                ('title', models.CharField(help_text='Nurodomas Agento pavadinimas.', max_length=255, verbose_name='Pavadinimas')),
                ('codename', models.CharField(blank=True, help_text='Nurodomas Agento kodinis pavadinimas.', max_length=255, verbose_name='Kodinis pavadinimas')),
                ('is_enabled', models.BooleanField(default=False, help_text='Nurodoma, ar Agentas yra įjungtas ar išjungtas.', verbose_name='Agentas įjungtas')),
                ('organization', models.ForeignKey(help_text='Nurodoma organizacija, kuriai priskirtas Agentas.', on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization', verbose_name='Organizacija')),
                ('service', models.ForeignKey(help_text='Nurodoma su Agentu susieta duomenų paslauga.', on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset', verbose_name='Duomenų paslauga')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
