# Generated by Django 3.2.25 on 2025-06-11 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0007_alter_dataset_organization'),
        ('vitrina_orgs', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('synchronized_at', models.DateTimeField(blank=True, help_text='Nurodoma data, kada paskutinį kartą buvo bandyta vykdyti sinchronizaciją.', null=True, verbose_name='Paskutinės sinchronizacijos data')),
                ('is_last_sync_successful', models.BooleanField(blank=True, help_text='Nurodoma, ar paskutinė sinchronizacija įvyko sėkmingai t.y. jos metu nekilo klaidų.', null=True, verbose_name='Ar paskutinė sinchronizacija įvyko sėkmingai?')),
                ('title', models.CharField(help_text='Nurodomas Agento pavadinimas.', max_length=255, verbose_name='Pavadinimas')),
                ('codename', models.CharField(blank=True, help_text='Nurodomas Agento kodinis pavadinimas.', max_length=255, verbose_name='Kodinis pavadinimas')),
                ('object_type', models.CharField(choices=[('SPINTA', 'Spinta'), ('OTHER', 'Kita')], default='SPINTA', max_length=64)),
                ('is_open_data_published', models.BooleanField(default=False, help_text='Nurodo, ar Agentas papildomai publikuoja `access=open` duomenis į atvirų duomenų Saugyklą.', verbose_name='Atviri duomenys publikuojami Saugykloje')),
                ('open_data_publish_url', models.URLField(blank=True, default='https://get.data.gov.lt/', help_text='Nuoroda, kur turėtų būti publikuojami atviri duomenys.', max_length=1024, verbose_name='Atvirų duomenų publikavimo nuoroda')),
                ('is_enabled', models.BooleanField(default=False, help_text='Nurodoma, ar Agentas yra įjungtas ar išjungtas.', verbose_name='Agentas įjungtas')),
                ('is_archived', models.BooleanField(default=False, help_text='Nurodo ar Agentas yra archyvuotas. Archyvuoti agentai nėra pasiekiami įprastiems platformos vartotojams', verbose_name='Agentas archyvuotas')),
                ('organization', models.ForeignKey(help_text='Nurodoma organizacija, kuriai priskirtas Agentas.', on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization', verbose_name='Organizacija')),
                ('service', models.ForeignKey(help_text='Nurodoma su Agentu susieta duomenų paslauga.', on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset', verbose_name='Duomenų paslauga')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('codename', 'organization'), name='unique_name_and_organization_for_not_archived_agents'),
        ),
    ]
