# Generated by Django 3.2.14 on 2022-08-29 05:41

from django.db import migrations, models


def update_paths(apps, schema_editor):
    from treebeard.numconv import NumConv

    alphabet = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    number_converter = NumConv(radix=len(alphabet), alphabet=alphabet)

    Organization = apps.get_model("vitrina_orgs", "Organization")
    for index, org in enumerate(Organization.objects.all(), 1):
        org.path = f"{number_converter.int2str(index):0>4}"
        org.save(update_fields=["path"])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0002_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AddField(
            model_name='organization',
            name='depth',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('com', 'Verslo organizacija'), ('org', 'Nepelno ir nevalstybinė organizacija'), ('gov', 'Valstybinė įstaiga')], default='org', max_length=36),
        ),
        migrations.AddField(
            model_name='organization',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='path',
            field=models.CharField(default="0000", max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(update_paths),
        migrations.AlterField(
            model_name="organization",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
