# Generated by Django 3.2.15 on 2022-09-19 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0003_auto_20220829_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representative',
            options={},
        ),
    ]
