# Generated by Django 3.2.15 on 2022-09-26 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0003_auto_20220829_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='publishedreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='representative',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
