# Generated by Django 3.2.13 on 2022-08-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0003_auto_20220812_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': False},
        ),
    ]
