# Generated by Django 3.2.25 on 2025-06-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0003_auto_20250611_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='object_type',
            field=models.CharField(choices=[('SPINTA', 'Spinta'), ('OTHER', 'Kita')], default='SPINTA', help_text='Nurodoma Agento rūšis t.y. ar bus naudojama "Spinta" ar kitas sprendimas.', max_length=64, verbose_name='Rūšis'),
        ),
    ]
