# Generated by Django 3.2.15 on 2022-09-19 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0004_auto_20220919_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Tvarkytojas'), ('coordinator', 'Koordinatorius')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
