# Generated by Django 3.2.14 on 2022-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0004_alter_organization_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('gov', 'Valstybinė įstaiga'), ('com', 'Verslo organizacija'), ('org', 'Nepelno ir nevalstybinė organizacija')], default='org', max_length=36),
        ),
    ]
