# Generated by Django 3.2.25 on 2025-06-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_api', '0007_remove_apikey_agent'),
        ('vitrina_orgs', '0004_alter_agent_object_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
