# Generated by Django 3.2.15 on 2022-09-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0004_auto_20220923_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vitrina_orgs.organization'),
        ),
    ]
