# Generated by Django 4.2.23 on 2025-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_orgs", "0005_delete_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="representative",
            name="can_write",
            field=models.BooleanField(default=True, verbose_name='Leidžiama keisti duomenis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="representative",
            name="can_write",
            field=models.BooleanField(default=False, verbose_name='Leidžiama keisti duomenis'),
        ),
    ]
