# Generated by Django 3.2.15 on 2022-09-19 08:16
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def update_user_field(apps, schema_editor):
    User = apps.get_model('vitrina_users', 'User')
    Representative = apps.get_model('vitrina_orgs', 'Representative')

    for rep in Representative.objects.all():
        if rep.email:
            try:
                user = User.objects.get(email=rep.email)
                rep.user = user
                rep.role = user.role
                rep.save()
            except ObjectDoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0005_auto_20220919_1057'),
    ]

    operations = [
        migrations.RunPython(update_user_field),
    ]
