# Generated by Django 3.2.15 on 2022-09-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0003_alter_organization_kind'),
        ('vitrina_orgs', '0006_alter_organization_kind'),
    ]

    operations = [
    ]
