# Generated by Django 4.2.23 on 2025-10-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0007_create_viewer_and_manager_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='can_make_agreements',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
