# Generated by Django 3.2.15 on 2022-09-28 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_orgs', '0007_auto_20220928_1451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='representative',
            unique_together={('organization', 'email'), ('organization', 'user')},
        ),
    ]
