# Generated by Django 3.2.15 on 2022-10-03 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_orgs', '0007_auto_20220928_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representative',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vitrina_orgs.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representative',
            name='role',
            field=models.CharField(choices=[('coordinator', 'Koordinatorius'), ('manager', 'Tvarkytojas')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='representative',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
