# Generated by Django 4.2.23 on 2025-10-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0008_representative_can_make_agreements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisherorganization',
            options={'verbose_name': 'Duomenų atvėrimo paslaugų teikėjas', 'verbose_name_plural': 'Duomenų atvėrimo paslaugų teikėjai'},
        ),
    ]
