# Generated by Django 4.2.23 on 2025-11-05 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0009_alter_publisherorganization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='whitelisted_code_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Sąrašas kodinių pavadinimų, kuriuos gali naudoti ši organizacija.', size=None, verbose_name='Leistini kodiniai pavadinimai'),
        ),
    ]
