# Generated by Django 4.2.26 on 2025-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0009_alter_publisherorganization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='information_system_representative',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Informacinės sistemos tvarkytojas'),
        ),
        migrations.AddField(
            model_name='representative',
            name='open_data_representative',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Atvirų duomenų tvarkytojas'),
        ),
    ]
