# Generated by Django 3.2.16 on 2022-10-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0009_auto_20221010_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='organization',
        ),
    ]
