# Generated by Django 4.2.23 on 2025-11-11 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0010_representative_information_system_representative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistedCodeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(help_text='Unikalus kodinis pavadinimas, kurį galima naudoti kuriant duomenų išteklius.', max_length=255, unique=True, verbose_name='Kodinis pavadinimas')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelisted_code_names', to='vitrina_orgs.organization', verbose_name='Organizacija')),
            ],
            options={
                'verbose_name': 'Leistinas kodinis pavadinimas',
                'verbose_name_plural': 'Leistini kodiniai pavadinimai',
                'ordering': ['code_name'],
            },
        ),
    ]
