# Generated by Django 4.2.26 on 2025-12-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0010_representative_information_system_representative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='information_system_representative',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='open_data_representative',
        ),
        migrations.AlterField(
            model_name='representative',
            name='role',
            field=models.CharField(choices=[('resource_coordinator', 'Duomenų išteklių koordinatorius'), ('resource_manager', 'Duomenų išteklių tvarkytojas'), ('open_data_coordinator', 'Atvirų duomenų koordinatorius'), ('open_data_manager', 'Atvirų duomenų tvarkytojas')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='representative',
            name='can_write',
        ),
    ]
