# Generated by Django 4.2.26 on 2026-01-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0010_representative_information_system_representative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('gov', 'Valstybinė įstaiga'), ('com', 'Verslo organizacija'), ('org', 'Ne pelno siekianti ar nevyriausybinė organizacija')], default='org', max_length=36, verbose_name='Tipas'),
        ),
    ]
