# Generated by Django 4.2.26 on 2025-12-04 09:37

from django.db import migrations
from vitrina.orgs.helpers import generate_dataset_prefix


def generate_org_prefix_for_existing_orgs(apps, schema_editor):
    Organization = apps.get_model('vitrina_orgs', 'Organization')

    for org in Organization.objects.all():
        if not org.name or not org.kind:
            continue
        new_name = generate_dataset_prefix(org.name, org.kind)
        if org.name == new_name:
            continue
        org.name = new_name
        org.save(update_fields=['name'])

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0011_whitelistedcodename'),
    ]

    operations = [
        migrations.RunPython(generate_org_prefix_for_existing_orgs),
    ]
