# Generated by Django 4.2.23 on 2025-12-12 08:08

from django.db import migrations, models


def set_nulled_can_make_agreements_representatives_to_false(apps, schema_editor):
    Representative = apps.get_model("vitrina_orgs", "Representative")
    Representative.objects.filter(can_make_agreements__isnull=True).update(can_make_agreements=False)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0012_generate_organization_name_with_prefix'),
    ]

    operations = [
        migrations.RunPython(
            set_nulled_can_make_agreements_representatives_to_false,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='representative',
            name='can_make_agreements',
            field=models.BooleanField(default=False),
        ),
    ]
