# Generated by Django 3.2.19 on 2023-07-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0015_auto_20221205_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='provider',
            field=models.BooleanField(default=False, verbose_name='Atvėrimo duomenų teikėjas'),
        ),
    ]
