# Generated by Django 4.2.26 on 2025-12-10 14:31

from django.db import migrations

def migrate_roles_forward(apps, schema_editor):
    Representative = apps.get_model("vitrina_orgs", "Representative")

    Representative.objects.filter(
        role="coordinator"
    ).update(role="open_data_coordinator")

    Representative.objects.filter(
        role="manager"
    ).update(role="open_data_manager")



class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0015_remove_representative_information_system_representative_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_roles_forward),
    ]
