# Generated by Django 3.2.20 on 2023-08-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0016_auto_20230711_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organization_mapping',
            },
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='publishedreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('gov', 'Valstybinė įstaiga'), ('org', 'Nepelno ir nevalstybinė organizacija'), ('com', 'Verslo organizacija')], default='org', max_length=36),
        ),
    ]
