# Generated by Django 4.2.26 on 2026-02-23 06:00

from django.db import migrations, models


def change_vda_role(apps, schema_editor):
    Representative = apps.get_model("vitrina_orgs", "Representative")
    Organization = apps.get_model("vitrina_orgs", "Organization")
    Dataset = apps.get_model("vitrina_datasets", "Dataset")
    ContentType = apps.get_model('contenttypes', 'ContentType')

    org_content_type = ContentType.objects.get_for_model(Organization)
    dataset_content_type = ContentType.objects.get_for_model(Dataset)

    vda = Organization.objects.filter(title="Valstybės duomenų agentūra").first()
    if vda:
        for rep in Representative.objects.filter(organization=vda):
            if rep.content_type == org_content_type and vda.pk != rep.object_id:
                rep.role = "open_data_publisher"
                rep.save()
            elif rep.content_type == dataset_content_type:
                dataset = Dataset.objects.filter(pk=rep.object_id).first()
                if dataset and dataset.organization_id != vda.pk:
                    rep.role = "open_data_publisher"
                    rep.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0016_update_roles'),
        ('vitrina_datasets', '0038_auto_20260204_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='role',
            field=models.CharField(choices=[('resource_coordinator', 'Duomenų išteklių koordinatorius'), ('resource_manager', 'Duomenų išteklių tvarkytojas'), ('open_data_coordinator', 'Atvirų duomenų koordinatorius'), ('open_data_manager', 'Atvirų duomenų tvarkytojas'), ('open_data_publisher', 'Atvirų duomenų skelbėjas')], max_length=255),
        ),
        migrations.RunPython(change_vda_role),
    ]
