# Generated by Django 3.2.21 on 2023-09-25 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vitrina_orgs', '0017_auto_20230808_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='company_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Registracijos numeris'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Elektroninis paštas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_organization', to=settings.FILER_IMAGE_MODEL, verbose_name='Logotipas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(blank=True, null=True, verbose_name='Organizacija viešinama'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jurisdikcija'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='kind',
            field=models.CharField(choices=[('org', 'Nepelno ir nevalstybinė organizacija'), ('com', 'Verslo organizacija'), ('gov', 'Valstybinė įstaiga')], default='org', max_length=36, verbose_name='Tipas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Savivaldybė'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefono numeris'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Regionas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(blank=True, choices=[('group', 'Grupė'), ('ministry', 'Ministerija'), ('municipality', 'Savivaldybė')], max_length=255, null=True, verbose_name='Vaidmuo'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tinklalapis'),
        ),
        migrations.AlterField(
            model_name='region',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='representative',
            name='role',
            field=models.CharField(choices=[('manager', 'Tvarkytojas'), ('coordinator', 'Koordinatorius')], max_length=255),
        ),
    ]
