# Generated by Django 3.2.23 on 2023-11-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0020_auto_20231108_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representativerequest',
            name='document',
            field=models.FileField(upload_to='data/files/request_assignments'),
        ),
    ]
