# Generated by Django 3.2.23 on 2023-12-12 18:33

from django.db import migrations
from vitrina.orgs.models import Organization

def fix_ordering(apps, schema_editor):
    #Organization = apps.get_model("vitrina_orgs", "Organization")
    Organization.fix_tree(fix_paths=True)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0021_auto_20231110_1011'),
    ]

    operations = [
        migrations.RunPython(fix_ordering),
    ]
