# Generated by Django 3.2.25 on 2024-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0029_auto_20241008_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRepresentative',
            fields=[
            ],
            options={
                'verbose_name': 'Organizacijos atstovas',
                'verbose_name_plural': 'Organizacijos atstovų sąrašas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vitrina_orgs.representative',),
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organizacija', 'verbose_name_plural': 'Organizacijos'},
        ),
        migrations.AddField(
            model_name='representative',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktyvus'), ('awaiting_confirmation', 'Laukiama patvirtinimo'), ('deleted', 'Pašalintas')], max_length=255, null=True),
        ),
    ]
