# Generated by Django 3.2.25 on 2024-10-08 11:31

from django.db import migrations


ACTIVE = 'active'
AWAITING_CONFIRMATION = 'awaiting_confirmation'
DELETED = 'deleted'


def update_representative_statuses(apps, schema_editor):
    Representative = apps.get_model('vitrina_orgs', 'Representative')

    for rep in Representative.objects.all():
        if rep.deleted and rep.deleted_on:
            rep.status = DELETED
        elif not rep.user:
            rep.status = AWAITING_CONFIRMATION
        else:
            rep.status = ACTIVE

        rep.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0030_auto_20241008_1356'),
    ]

    operations = [
        migrations.RunPython(update_representative_statuses)
    ]
