# Generated by Django 3.2.25 on 2024-11-08 07:42

from django.db import migrations, models
import django.db.models.deletion


def map_jurisdiction(apps, schema_editor):
    organization = apps.get_model('vitrina_orgs', 'Organization')
    jurisdiction_mapping = {
        'Ekonomikos ir inovacijų ministerija': 2,      # Lietuvos Respublikos ekonomikos ir inovacijų ministerija
        'Energetikos ministerija': 3,                  # Lietuvos Respublikos energetikos ministerija
        'Finansų ministerija': 4,                      # Lietuvos Respublikos finansų ministerija
        'Krašto apsaugos ministerija': 5,              # Lietuvos Respublikos krašto apsaugos ministerija
        'Kultūros ministerija': 6,                     # Lietuvos Respublikos kultūros ministerija
        'Socialinės apsaugos ir darbo ministerija': 7, # Lietuvos Respublikos socialinės apsaugos ir darbo ministerija
        'Susisiekimo ministerija': 8,                  # Lietuvos Respublikos susisiekimo ministerija
        'Sveikatos apsaugos ministerija': 9,           # Lietuvos Respublikos sveikatos apsaugos ministerija
        'Švietimo, mokslo ir sporto ministerija': 10,  # Lietuvos Respublikos švietimo, mokslo ir sporto ministerija
        'Teisingumo ministerija': 11,                  # Lietuvos Respublikos teisingumo ministerija
        'Užsienio reikalų ministerija': 12,            # Lietuvos Respublikos užsienio reikalų ministerija
        'Vidaus reikalų ministerija': 13,              # Lietuvos Respublikos vidaus reikalų ministerija
        'Žemės ūkio ministerija': 14,                  # Lietuvos Respublikos žemės ūkio ministerija
        'Savivaldybės': 15,                            # Savivaldybės
        'Vyriausybei atskaitingos institucijos': 16,   # Vyriausybei atsakingos institucijos
        'Verslas': 19,                                 # Verslas
        'Nevyriausybinės organizacijos': 21,           # Neviriausybinės organizacijos
        'Aplinkos ministerija': 22,                    # Lietuvos Respublikos aplinkos ministerija
    }
    for org in organization.objects.all():
        org.jurisdiction = jurisdiction_mapping.get(org.jurisdiction, 1)
        org.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0028_auto_20240828_0812'),
    ]

    operations = [
        migrations.RunPython(map_jurisdiction),
        migrations.AlterField(
            model_name='organization',
            name='jurisdiction',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.SET_DEFAULT, to='vitrina_classifiers.AreaOfManagement', verbose_name='Jurisdikcija'),
        ),
    ]
