# Generated by Django 3.2.25 on 2024-10-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0031_auto_20241008_1431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='representative',
            unique_together=set(),
        ),
    ]
