# Generated by Django 3.2.25 on 2024-11-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0032_auto_20241015_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='parent_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_orgs.representative'),
        ),
    ]
