# Generated by Django 3.2.25 on 2024-11-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0017_auto_20241112_1333'),
        ('vitrina_orgs', '0032_auto_20241108_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='jurisdiction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='vitrina_classifiers.areaofmanagement', verbose_name='Valdymo sritis'),
        ),
    ]
