# Generated by Django 3.2.25 on 2024-12-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0033_auto_20241115_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='provider',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='organization',
            name='publisher',
            field=models.BooleanField(default=False, verbose_name='Duomenų atvėrimo paslaugų teikėjas'),
        ),
    ]
