# Generated by Django 3.2.25 on 2024-12-11 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0034_auto_20241206_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='vitrina_orgs.organization')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_organizations', to='vitrina_orgs.organization')),
            ],
            options={
                'unique_together': {('publisher', 'organization')},
            },
        ),
    ]
