# Generated by Django 3.2.25 on 2024-12-23 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0034_auto_20241202_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_orgs.organization'),
        ),
    ]
