# Generated by Django 3.2.25 on 2024-12-30 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_orgs", "0035_auto_20241223_0844"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="provider",
            new_name="publisher",
        ),
        migrations.AlterField(
            model_name="organization",
            name="publisher",
            field=models.BooleanField(
                default=False, verbose_name="Duomenų atvėrimo paslaugų teikėjas"
            ),
        ),
    ]
