# Generated by Django 3.2.15 on 2022-09-21 06:33
from datetime import datetime
from django.db import migrations


def migrate_likes(apps, schema_editor):
    UserLike = apps.get_model('vitrina_likes', 'UserLike')
    UserVote = apps.get_model('vitrina_likes', 'UserVote')
    Like = apps.get_model('vitrina_likes', 'Like')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for user_like in UserLike.objects.all():
        content_type = ContentType.objects.get(app_label='vitrina_requests', model='request')
        Like.objects.create(
            created=user_like.created or datetime.now(),
            content_type=content_type,
            object_id=user_like.request_id,
            user_id=user_like.user_id
        )

    for user_vote in UserVote.objects.all():
        if user_vote.dataset:
            content_type = ContentType.objects.get(app_label='vitrina_datasets', model='dataset')
            Like.objects.create(
                created=user_vote.created or datetime.now(),
                content_type=content_type,
                object_id=user_vote.dataset.pk,
                user=user_vote.user
            )
        elif user_vote.harvested:
            content_type = ContentType.objects.get(app_label='vitrina_datasets', model='harvestingresult')
            Like.objects.create(
                created=user_vote.created or datetime.now(),
                content_type=content_type,
                object_id=user_vote.harvested.pk,
                user=user_vote.user
            )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_likes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_likes),
    ]
