# Generated by Django 3.2.25 on 2025-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_likes", "0003_auto_20220928_0842"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlike",
            options={"managed": True},
        ),
        migrations.AlterModelOptions(
            name="uservote",
            options={"managed": True},
        ),
        migrations.AlterField(
            model_name="like",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
