# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lt', models.CharField(default='Nepriskirta', max_length=255, verbose_name='Pavadinimas lietuviškai')),
                ('name_en', models.CharField(default='Unassigned', max_length=255, verbose_name='Pavadinimas angliškai')),
            ],
            options={
                'verbose_name': 'Valdymo sritis',
                'verbose_name_plural': 'Valdymo sritys',
                'db_table': 'area_of_management',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(blank=True, default=1)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, verbose_name='Nuoroda į kontroliuojamą žodyną')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('edp_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField()),
                ('icon', models.CharField(blank=True, help_text='Naudokite "glyph" pavadinimą iš icomoon.svg failo', max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('title_en', models.TextField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('hours', models.IntegerField(blank=True, null=True, verbose_name='Valandos')),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Kodas')),
            ],
            options={
                'db_table': 'frequency',
                'ordering': ['hours'],
            },
        ),
        migrations.CreateModel(
            name='GeoportalAccessRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('access_rights', models.CharField(blank=True, choices=[('PUBLIC', 'Atviri duomenys'), ('RESTRICTED', 'Apsaugoti duomenys'), ('NON_PUBLIC', 'Uždari duomenys')], max_length=255, null=True, verbose_name='Atitinkančios prieigos teisės')),
            ],
            options={
                'verbose_name': 'Geoportalo prieigos teisė',
                'verbose_name_plural': 'Geoportalo prieigos teisės',
                'db_table': 'geoportal_access_rights',
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'licence',
            },
        ),
        migrations.CreateModel(
            name='GeoportalLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('licence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_classifiers.licence', verbose_name='Atitinkanti licencija')),
            ],
            options={
                'verbose_name': 'Geoportalo licencija',
                'verbose_name_plural': 'Geoportalo licencijos',
                'db_table': 'geoportal_licence',
            },
        ),
        migrations.CreateModel(
            name='GeoportalFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_classifiers.frequency', verbose_name='Atitinkantis atnaujinimo periodiškumas')),
            ],
            options={
                'verbose_name': 'Geoportalo atnaujinimo periodiškumas',
                'verbose_name_plural': 'Geoportalo atnaujinimo periodiškumai',
                'db_table': 'geoportal_frequency',
            },
        ),
        migrations.CreateModel(
            name='GeoportalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('categories', models.ManyToManyField(blank=True, to='vitrina_classifiers.Category', verbose_name='Atitinkančios kategorijos')),
            ],
            options={
                'verbose_name': 'Geoportalo kategorija',
                'verbose_name_plural': 'Geoportalo kategorijos',
                'db_table': 'geoportal_category',
            },
        ),
    ]
