# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_classifiers', '0001_initial'),
        ('vitrina_datasets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(to='vitrina_datasets.DatasetGroup'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_set', to='vitrina_classifiers.category'),
        ),
    ]
