# Generated by Django 3.2.25 on 2025-04-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0005_auto_20250328_0742'),
        ('vitrina_classifiers', '0003_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(blank=True, to='vitrina_datasets.DatasetGroup'),
        ),
    ]
