# Generated by Django 3.2.15 on 2022-09-19 07:47

from django.db import migrations, models


def count_category_depth(cat):
    depth = 0
    parent_cat = cat
    while parent_cat.parent:
        depth += 1
        parent_cat = parent_cat.parent
    return depth


def set_root_category_data(categories, Category):
    for cat in categories:
        cat.depth = 0
        cat.numchild = Category.objects.filter(parent=cat).count()
        cat.save(update_fields=['numchild', 'depth'])


def set_child_category_data(categories, Category):
    for cat in categories:
        cat.numchild = Category.objects.filter(parent=cat).count()
        cat.depth = count_category_depth(cat)
        cat.save(update_fields=['numchild', 'depth'])


def calculate_category_paths(Category):
    steplen = 4
    alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    check_depth = 0
    while Category.objects.filter(depth=check_depth).exists():
        for index, cat in enumerate(Category.objects.filter(depth=check_depth), start=0):
            if cat.parent and cat.parent.path:
                parent_path = cat.parent.path
            else:
                parent_path = ''
            cat.path = '{0}{1}{2}'.format(
                parent_path,
                alphabet[0] * (steplen - len(str(index))),
                index
            )
            cat.save(update_fields=['path'])
        check_depth += 1


def remake_categories(apps, schema_editor):
    Category = apps.get_model("vitrina_classifiers", "Category")
    root_cats = Category.objects.filter(parent__isnull=True)
    set_root_category_data(root_cats, Category)
    child_cats = Category.objects.filter(parent__isnull=False)
    set_child_category_data(child_cats, Category)
    calculate_category_paths(Category)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0004_rename_parent_id_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('books', 'books'), ('analysis', 'analysis'),
                                                        ('electricity', 'electricity'),
                                                        ('cityscape', 'cityscape'),
                                                        ('accounting', 'accounting'),
                                                        ('airplane', 'airplane'), ('balance', 'balance'),
                                                        ('marketing', 'marketing'), ('nature', 'nature'),
                                                        ('oil', 'oil'), ('pantheon', 'pantheon'),
                                                        ('retirement', 'retirement'), ('trumpet', 'trumpet'),
                                                        ('vaccine', 'vaccine')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='numchild',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, null=True, max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(remake_categories),
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(unique=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='numchild',
            field=models.PositiveIntegerField(),
        ),
    ]

