# Generated by Django 3.2.15 on 2022-09-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0004_rename_parent_id_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={'managed': True},
        ),
    ]
