# Generated by Django 3.2.25 on 2025-07-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0004_alter_category_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeoportalAccessRights',
        ),
        migrations.DeleteModel(
            name='GeoportalLicence',
        ),
    ]
