# Generated by Django 3.2.25 on 2025-05-27 07:43

from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.apps.registry import Apps
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
from django.utils.translation import override



def create_initial_statuses(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Status = apps.get_model('vitrina_classifiers', 'Status')

    statuses = [
        {
            'codename': None,
            'translations': {
                'lt': {
                    'name': 'Nepasirinkta',
                    'description': '',
                },
                'en': {
                    'name': 'Not chosen',
                    'description': '',
                },
            },
            'default': True,
        },
        {
            'codename': 'develop',
            'translations': {
                'lt': {
                    'name': 'Kuriama (develop)',
                    'description': 'Galima keisti be išankstinio įspėjimo',
                },
                'en': {
                    'name': 'Under development (develop)',
                    'description': 'Can be changed without prior notice',
                },
            },
            'default': False,
        },
        {
            'codename': 'completed',
            'translations': {
                'lt': {
                    'name': 'Užbaigta (completed)',
                    'description': 'Galima keisti tik informavus naudotojus prieš nustatytą laiką.',
                },
                'en': {
                    'name': 'Completed (completed)',
                    'description': 'Changes can only be made after users have been informed in advance.',
                },
            },
            'default': False,
        },
        {
            'codename': 'discont',
            'translations': {
                'lt': {
                    'name': 'Nerekomenduojama (discont)',
                    'description': 'Duomenys nėra atnaujinami, tačiau elemento šalinti kol kas neplanuojama.',
                },
                'en': {
                    'name': 'Not recommended (discont)',
                    'description': 'The data is not updated, but there are no plans to remove the element for the time being.',
                },
            },
            'default': False,
        },
        {
            'codename': 'deprecated',
            'translations': {
                'lt': {
                    'name': 'Nebetiekiama (deprecated)',
                    'description': 'Nebenaudotina, ateityje bus pašalinta, nurodoma, kai numatyta pašalinti `completed` būsenos elementus.',
                },
                'en': {
                    'name': 'Deprecated (deprecated)',
                    'description': 'No longer used, to be removed in the future, is indicated when it is intended to remove `completed` status items.',
                },
            },
            'default': False,
        },
        {
            'codename': 'withdrawn',
            'translations': {
                'lt': {
                    'name': 'Atšaukta (withdrawn)',
                    'description': 'Pilnai panaikinama, kai praeina nustatytas laiko terminas po `deprecated`būsenos nurodymo.',
                },
                'en': {
                    'name': 'Withdrawn (withdrawn)',
                    'description': 'Completely deprecated when a specified period of time has elapsed since the `deprecated` status was specified.',
                },
            },
            'default': False,
        },
    ]

    for status_data in statuses:
        status = Status.objects.create(codename=status_data['codename'])

        for lang_code, fields in status_data['translations'].items():
            with override(lang_code):
                status.set_current_language(lang_code)
                status.name = fields['name']
                status.description = fields['description']
                status.save()

        if status_data.get('default'):
            status.is_default = True
            status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0004_alter_category_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('codename', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Kodinis pavadinimas')),
                ('url', models.CharField(blank=True, max_length=512, null=True, verbose_name='Nuoroda į kontroliuojamą EU žodyną')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Būsena',
                'verbose_name_plural': 'Būsenos',
                'db_table': 'status',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.status')),
            ],
            options={
                'verbose_name': 'Būsena Translation',
                'db_table': 'status_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(create_initial_statuses),
    ]
