# Generated by Django 3.2.15 on 2022-09-19 07:47

from django.db import migrations, models
from django.shortcuts import get_object_or_404


def remake_categories(apps, schema_editor):
    Category = apps.get_model("vitrina_classifiers", "Category")
    root_cats = Category.objects.filter(parent__isnull=True)
    Category_MP = apps.get_model('vitrina_classifiers', 'Category_MP')
    for cat in root_cats:
        Category_MP.add_root(cat)
    child_cats = Category.objects.filter(parent__isnull=False).order_by('parent_id')
    for cat in child_cats:
        parent = Category_MP.get_object_or_404(pk=cat.parent_id)
        parent.add_child(cat)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0004_rename_parent_id_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('books', 'books'), ('analysis', 'analysis'),
                                                        ('electricity', 'electricity'),
                                                        ('cityscape', 'cityscape'),
                                                        ('accounting', 'accounting'),
                                                        ('airplane', 'airplane'), ('balance', 'balance'),
                                                        ('marketing', 'marketing'), ('nature', 'nature'),
                                                        ('oil', 'oil'), ('pantheon', 'pantheon'),
                                                        ('retirement', 'retirement'), ('trumpet', 'trumpet'),
                                                        ('vaccine', 'vaccine')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Category_MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('edp_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField()),
                ('icon', models.CharField(blank=True, choices=[('books', 'books'), ('analysis', 'analysis'),
                                                               ('electricity', 'electricity'),
                                                               ('cityscape', 'cityscape'),
                                                               ('accounting', 'accounting'),
                                                               ('airplane', 'airplane'), ('balance', 'balance'),
                                                               ('marketing', 'marketing'), ('nature', 'nature'),
                                                               ('oil', 'oil'), ('pantheon', 'pantheon'),
                                                               ('retirement', 'retirement'), ('trumpet', 'trumpet'),
                                                               ('vaccine', 'vaccine')], max_length=255, null=True)),
                ('depth', models.PositiveIntegerField(default=0)),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('path', models.CharField(unique=True, max_length=255)),
            ],
            options={
                'db_table': 'category_mp_node',
                'managed': False,
            },
        ),
        migrations.RunPython(remake_categories),
        migrations.DeleteModel('category'),
        migrations.RenameModel("Category_MP_Node", "category")
    ]

