# Generated by Django 3.2.15 on 2022-09-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0005_auto_20220930_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequency',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licence',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
