# Generated by Django 3.2.15 on 2022-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0005_fix_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True,
                                   max_length=255,
                                   help_text='Pasirinkite kategorijos paveikslėlį iš šios nuorodos: https://fontawesome.com/search'),
        ),
        migrations.AddField(
            model_name='category',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='numchild',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, null=True, max_length=255),
            preserve_default=False,
        ),
    ]

