# Generated by Django 3.2.25 on 2025-06-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0005_status_statustranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='codename',
            field=models.CharField(blank=True, help_text='Savybė nurodanti prieigos prie metaduomenų lygį. DCAT-AP rekomenduoja naudoti šias klasifikatoriaus reikšmes: <br>- develop <br>- completed <br>- discont <br>- deprecated <br>- withdrawn <br>', max_length=255, null=True, unique=True, verbose_name='Kodinis pavadinimas'),
        ),
        migrations.AlterField(
            model_name='statustranslation',
            name='description',
            field=models.CharField(blank=True, help_text='Būsenos lauko aprašymas. Šis aprašymas yra skirtas skaityti žmonėms ir bus rodomas duomenų laukų sąrašuose ir antraštėse. ', max_length=255, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='statustranslation',
            name='name',
            field=models.CharField(help_text='Būsenos lauko pavadinimas. Šis pavadinimas yra skirtas skaityti žmonėms ir bus rodomas duomenų laukų sąrašuose ir antraštėse. ', max_length=255, unique=True, verbose_name='Pavadinimas'),
        ),
    ]
