# Generated by Django 3.2.15 on 2022-09-19 07:47

from typing import Type

from django.db import migrations

from treebeard.mp_tree import MP_Node


def _get_path(
    value: int,
    steplen: int = MP_Node.steplen,
    alphabet: str = MP_Node.alphabet,
) -> str:
    return MP_Node._int2str(value).rjust(steplen, alphabet[0])


def _fix_mp(
    model: Type[MP_Node],
    order_by: list[str],  # model.node_order_by
    parent: MP_Node | None = None,
    depth: int = 1,
    path: str = '',
) -> int:  # numchild
    i = 0
    qs = model.objects.filter(parent=parent).order_by(*order_by)
    for i, obj in enumerate(qs, 1):
        obj.depth = depth
        obj.path = path + _get_path(i)
        obj.numchild = _fix_mp(model, order_by, obj, depth + 1, obj.path)
        obj.save(update_fields=['depth', 'path', 'numchild'])
    return i


def remake_categories(apps, schema_editor):
    Category = apps.get_model("vitrina_classifiers", "Category")
    _fix_mp(Category, ['title'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0006_alter_add_fields'),
    ]

    operations = [
        migrations.RunPython(remake_categories),
    ]
