# Generated by Django 3.2.25 on 2025-07-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0005_auto_20250714_0814'),
        ('vitrina_classifiers', '0006_auto_20250603_1142'),
    ]

    operations = [
    ]
