# Generated by Django 3.2.16 on 2022-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0006_auto_20220930_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='licence',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
