# Generated by Django 3.2.25 on 2025-04-17 05:55
from django.db import migrations, models

def update_category_icons(apps, schema_editor):
    Category = apps.get_model('vitrina_classifiers', 'Category')

    icon_mapping = {
        'Sveikata': 'syringe',
        'Teisingumas, teisės sistema ir visuomenės sauga': 'scale-balanced',
        'Tarptautiniai santykiai': 'earth-europe',
        'Švietimas': 'graduation-cap',
        'Transportas ir ryšiai': 'truck-plane',
        'Socialinė apsauga': 'shield-halved',
        'Ekonomika ir finansai': 'money-bill-trend-up',
        'Energetika': 'bolt',
        'Regionai ir miestai': 'city',
        'Sveikatos apsauga': 'shield-heart',
        'Kultūra': 'guitar',
        'Valstybės valdymas, viešasis administravimas': 'landmark',
        'Mokslas ir technologijos': 'flask',
        'Aplinka': 'cloud-sun',
        'Ūkinė veikla ir verslas': 'building-wheat',
    }

    for category in Category.objects.all():
        if not category.title in icon_mapping:
            continue

        category.icon = icon_mapping[category.title]
        category.featured = True
        category.save()

def reverse_icon_update(apps, schema_editor):
    Category = apps.get_model('vitrina_classifiers', 'Category')

    original_icon_mapping = {
        'Sveikata': 'vaccine',
        'Kultūra': 'trumpet',
        'Socialinė apsauga': 'retirement-plan',
        'Valstybės valdymas, viešasis administravimas': 'pantheon',
        'Ekonomika ir finansai': 'oil',
        'Aplinka': 'nature',
        'Tarptautiniai santykiai': 'marketing',
        'Energetika': 'electricity-tower',
        'Regionai ir miestai': 'cityscape',
        'Švietimas': 'books',
        'Teisingumas, teisės sistema ir visuomenės sauga': 'balance',
        'Mokslas ir technologijos': 'analysis',
        'Transportas ir ryšiai': 'airplane',
        'Ūkinė veikla ir verslas': 'accounting',
    }

    for category in Category.objects.all():
        if not category.title in original_icon_mapping:
            continue

        category_icon = original_icon_mapping[category.title]
        category.icon = category_icon
        if not category_icon:
            category.featured = False

        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0007_merge_0005_auto_20250714_0814_0006_auto_20250603_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Piktogramas rasite https://fontawesome.com/search?ic=free.', max_length=255),
        ),

        migrations.RunPython(update_category_icons, reverse_code=reverse_icon_update),
    ]
