# Generated by Django 3.2.25 on 2025-07-31 11:18
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0008_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptSchema',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uri', models.URLField(max_length=255, unique=True, verbose_name='uri')),
            ],
            options={
                'verbose_name': 'Sąvokų schema',
                'verbose_name_plural': 'Sąvokų schemos',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Kodinis pavadinimas')),
                ('valid_since', models.DateField(verbose_name='Galioja nuo')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Galioja iki')),
                ('concept_schemas', models.ManyToManyField(related_name='concepts', to='vitrina_classifiers.ConceptSchema', verbose_name='Sąvokų schemos')),
            ],
            options={
                'verbose_name': 'Sąvoka',
                'verbose_name_plural': 'Sąvokos',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConceptTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.concept')),
            ],
            options={
                'verbose_name': 'Sąvoka Translation',
                'db_table': 'vitrina_classifiers_concept_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConceptSchemaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.conceptschema')),
            ],
            options={
                'verbose_name': 'Sąvokų schema Translation',
                'db_table': 'vitrina_classifiers_conceptschema_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
