# Generated by Django 3.2.15 on 2022-09-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0008_alter_path_depth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={},
        ),
        migrations.AlterModelOptions(
            name='licence',
            options={},
        ),
    ]
