# Generated by Django 3.2.25 on 2025-08-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0009_concept_conceptschema_conceptschematranslation_concepttranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='uri',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='uri'),
        ),
    ]
