# Generated by Django 3.2.25 on 2025-08-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0010_concept_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='uri'),
        ),
        migrations.AlterField(
            model_name='conceptschema',
            name='uri',
            field=models.CharField(max_length=255, unique=True, verbose_name='uri'),
        ),
    ]
