# Generated by Django 3.2.25 on 2025-08-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0010_concept_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableLegislation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pavadinimas')),
                ('url', models.URLField(max_length=255, verbose_name='Nuoroda')),
            ],
            options={
                'verbose_name': 'Teisinis pagrindas',
                'verbose_name_plural': 'Teisiniai pagrindai',
            },
        ),
    ]
