# Generated by Django 3.2.25 on 2025-08-18 07:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0010_concept_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableLegislation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pavadinimas')),
                ('url', models.URLField(max_length=255, verbose_name='Nuoroda')),
            ],
            options={
                'verbose_name': 'Teisinis pagrindas',
                'verbose_name_plural': 'Teisiniai pagrindai',
            },
        ),
    ]
