# Generated by Django 3.2.16 on 2022-12-29 13:13

from django.db import migrations, models
import django.db.models.deletion


title_hours = {'Kas 30 metų': 262800,
               'Kas 25 metai': 219000,
               'Kas 10 metų': 87600,
               'Kas 5 metai': 43800,
               'Kas 4 metai': 35040,
               'Kas 3 metai': 26280,
               'Kas 2 metai': 17520,
               'Kasmet': 8760,
               'Dukart per metus': 4380,
               'Triskart per metus': 2920,
               'Kas 3 mėnesiai': 2160,
               'Kas 2 mėnesiai': 1440,
               'Kas mėnesį': 720,
               'Kas ketvirtį': 480,
               'Dukart per mėnesį': 360,
               'Kas 2 savaitės': 336,
               'Triskart per mėnesį': 240,
               'Kas savaitę': 168,
               'Dukart per savaitę': 84,
               'Triskart per savaitę': 56,
               'Kasdien': 24,
               'Dažniau nei kasdien': 23,
               'Dukart per dieną': 12,
               'Kas 3 valandos': 3,
               'Kas 2 valandas': 2,
               'Kas valandą': 1,
               'Nepertraukiamas': 0}


def set_hours(apps, schema_editor):
    Frequency = apps.get_model("vitrina_classifiers", "Frequency")
    frequencies = Frequency.objects.all()
    for freq in frequencies:
        hours = title_hours.get(freq.title, None)
        freq.hours = hours
        freq.save(update_fields=['hours'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0010_auto_20220930_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frequency',
            options={'ordering': ['hours']},
        ),
        migrations.AddField(
            model_name='frequency',
            name='hours',
            field=models.IntegerField(null=True, verbose_name='Valandos'),
        ),
        migrations.AlterField(
            model_name='category',
            name='version',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='licence',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.RunPython(set_hours),
    ]
