# Generated by Django 3.2.16 on 2023-03-09 12:39

from django.db import migrations, models

def restore_old_icons(apps, schema_editor):
    Category = apps.get_model("vitrina_classifiers", "Category")
    categories = Category.objects.all()
    for cat in categories:
        if cat.icon == 'fa-hand-holding-heart':
            cat.icon = 'vaccine'
        if cat.icon == 'fa-theater-masks':
            cat.icon = 'trumpet'
        if cat.icon == 'fa-universal-access':
            cat.icon = 'retirement-plan'
        if cat.icon == 'fa-columns':
            cat.icon = 'pantheon'
        if cat.icon == 'fa-oil-can':
            cat.icon = 'oil'
        if cat.icon == 'fa-tree':
            cat.icon = 'nature'
        if cat.icon == 'fa-handshake':
            cat.icon = 'marketing'
        if cat.icon == 'fa-broadcast-tower':
            cat.icon = 'electricity-tower'
        if cat.icon == 'fa-city':
            cat.icon = 'cityscape'
        if cat.icon == 'fa-book':
            cat.icon = 'books'
        if cat.icon == 'fa-balance-scale':
            cat.icon = 'balance'
        if cat.icon == 'fa-microscope':
            cat.icon = 'analysis'
        if cat.icon == 'fa-plane':
            cat.icon = 'airplane'
        if cat.icon == 'fa-tractor':
            cat.icon = 'accounting'
        cat.save(update_fields=['icon', 'featured'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0010_auto_20220930_0838'),
    ]

    operations = [
        migrations.RunPython(restore_old_icons),
    ]
