# Generated by Django 3.2.16 on 2023-03-22 11:07

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0011_auto_20221229_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licence',
            options={'verbose_name': 'License'},
        ),
        migrations.RenameField(
            model_name='licence',
            old_name='description',
            new_name='description_old'
        ),
        migrations.RenameField(
            model_name='licence',
            old_name='title',
            new_name="title_old"
        ),
        migrations.AlterField(
            model_name='category',
            name='numchild',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_set', to='vitrina_classifiers.category'),
        ),
        migrations.AlterField(
            model_name='frequency',
            name='hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valandos'),
        ),
        migrations.CreateModel(
            name='LicenceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.licence')),
            ],
            options={
                'verbose_name': 'License Translation',
                'db_table': 'licence_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
