# Generated by Django 3.2.19 on 2023-06-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0014_merge_0013_auto_20221202_0923_0013_auto_20221206_1003'),
        ('vitrina_classifiers', '0011_auto_20221229_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='groups',
            field=models.ManyToManyField(to='vitrina_datasets.DatasetGroup'),
        ),
    ]
