# Generated by Django 3.2.25 on 2025-08-12 08:06

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_information_system_importance_and_information_system_type(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")

    information_system_type_concept_schema, created = ConceptSchema.objects.get_or_create(
        uri="dcataplt:Type",
    )
    if created:
        information_system_type_concept_schema.set_current_language("lt")
        information_system_type_concept_schema.label = "Informacinės sistemos rūšis"
        information_system_type_concept_schema.description = "Informacinės sistemos tipas pagal Valstybės informacinių išteklių valdymo įstatymo reikalavimus"
        information_system_type_concept_schema.save()
        information_system_type_concept_schema.set_current_language("en")
        information_system_type_concept_schema.label = "Informacion system type"
        information_system_type_concept_schema.description = "Information system type according to the requirements of the Law on State Information Resources Management"
        information_system_type_concept_schema.save()

    information_system_importance_concept_schema, created = ConceptSchema.objects.get_or_create(
        uri="dcataplt:Importance",
    )
    if created:
        information_system_importance_concept_schema.set_current_language("lt")
        information_system_importance_concept_schema.label = "Informacinės sistemos svarba"
        information_system_importance_concept_schema.description = "Informacinės sistemos svarba pagal Valstybės informacinių išteklių valdymo įstatymo reikalavimus"
        information_system_importance_concept_schema.save()
        information_system_importance_concept_schema.set_current_language("en")
        information_system_importance_concept_schema.label = "Informacion system importance"
        information_system_importance_concept_schema.description = "Information system importance in accordance with the requirements of the Law on State Information Resources Management"
        information_system_importance_concept_schema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0011_auto_20250811_1340'),
    ]

    operations = [
        migrations.RunPython(create_information_system_importance_and_information_system_type, reverse_code=migrations.RunPython.noop),
    ]
