# Generated by Django 3.2.16 on 2023-03-22 11:28

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0012_translate_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='frequency',
            options={'ordering': ['hours'], 'verbose_name': 'Frequency'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='description_old',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name="title_old",
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_en',
            new_name="title_en_old",
        ),
        migrations.RenameField(
            model_name='frequency',
            old_name='title',
            new_name="title_old",
        ),
        migrations.RenameField(
            model_name='frequency',
            old_name='title_en',
            new_name="title_en_old",
        ),
        migrations.CreateModel(
            name='FrequencyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.frequency')),
            ],
            options={
                'verbose_name': 'Frequency Translation',
                'db_table': 'frequency_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.TextField(blank=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.category')),
            ],
            options={
                'verbose_name': 'Category Translation',
                'db_table': 'category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
