# Generated by Django 3.2.22 on 2023-11-08 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0012_auto_20230619_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uri',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nuoroda į kontroliuojamą žodyną'),
        ),
    ]
