# Generated by Django 3.2.25 on 2025-08-19 11:43

from django.db import migrations

URI="http://publications.europa.eu/resource/authority/data-service-type"


def create_concept_schema(apps, schema_editor):
    concept_schema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    schema, created = concept_schema.objects.get_or_create(
        uri=URI,
    )
    if created:
        schema.set_current_language("lt")
        schema.label = "Duomenų paslaugos tipas"
        schema.description = "Duomenų paslaugos tipas, atitinkantis dct:type"
        schema.save()
        schema.set_current_language("en")
        schema.label = "Data service type"
        schema.description = "Data service type, which corresponds to dct:type"
        schema.save()

def delete_concept_schema(apps, schema_editor):
    model = apps.get_model("vitrina_classifiers", "ConceptSchema")
    model.objects.filter(uri=URI).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0013_applicablelegislation'),
    ]

    operations = [
        migrations.RunPython(create_concept_schema, delete_concept_schema),
    ]
