# Generated by Django 3.2.25 on 2025-08-19 11:43
from datetime import date

from django.db import migrations

CONCEPT_SCHEMA_URI="http://publications.europa.eu/resource/authority/data-service-type"


def create_concept_schema(apps, schema_editor):
    concept_schema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    schema, created = concept_schema.objects.get_or_create(
        uri=CONCEPT_SCHEMA_URI,
    )
    if created:
        schema.set_current_language("lt")
        schema.label = "Duomenų paslaugos tipas"
        schema.description = "Duomenų paslaugos tipas, atitinkantis dct:type"
        schema.save()
        schema.set_current_language("en")
        schema.label = "Data service type"
        schema.description = "Data service type, which corresponds to dct:type"
        schema.save()

def delete_concept_schema(apps, schema_editor):
    model = apps.get_model("vitrina_classifiers", "ConceptSchema")
    model.objects.filter(uri=CONCEPT_SCHEMA_URI).delete()


def create_concepts(apps, schema_editor):
    Concept = apps.get_model("vitrina_classifiers", "Concept")
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")

    concept_schema = ConceptSchema.objects.get(uri=CONCEPT_SCHEMA_URI)

    concepts_data = [
        {
            "uri": "http://publications.europa.eu/resource/authority/data-service-type/API",
            "code": "API",
            "valid_since": date(2021, 8, 30),
            "translations": {
                "en": {
                    "label": "API",
                    "description": "An API – application programming interface – is a set of functions, procedures, definitions and protocols for machine-to-machine communication and the seamless exchange of data.",
                },
                "lt": {
                    "label": "Žiniatinklio paslauga",
                    "description": "Žiniatinklio paslauga – tai funkcijų, procedūrų, apibrėžimų ir protokolų rinkinys, skirtas mašinų tarpusavio ryšiui ir duomenų mainams."
                }
            }
        },
        {
            "uri": "http://publications.europa.eu/resource/authority/data-service-type/DOWNLOAD",
            "code": "DOWNLOAD",
            "valid_since": date(2021, 8, 30),
            "translations": {
                "en": {
                    "label": "Download service",
                    "description": "A download service is a service that enables copies of datasets or parts of such sets to be downloaded and, where practicable, accessed directly.",
                },
                "lt": {
                    "label": "Parsisiuntimas",
                    "description": "Atsisiuntimo paslauga – tai paslauga, leidžianti atsisiųsti duomenų rinkinių kopijas ar jų dalis ir, jei įmanoma, tiesiogiai prie jų prisijungti."
                }
            }
        },
        {
            "uri": "http://publications.europa.eu/resource/authority/data-service-type/HUMAN_INTERACTION",
            "code": "HUMAN_INTERACTION",
            "valid_since": date(2021, 8, 30),
            "translations": {
                "en": {
                    "label": "Human interaction service",
                    "description": "A human interaction service is a service that enables human beings to interact with it. In the context of data services, it typically provides a user interface (UI) for querying data.",
                },
                "lt": {
                    "label": "Žmogaus interakcija",
                    "description": "Žmogaus sąveikos paslauga – tai paslauga, leidžianti žmonėms su ja sąveikauti. Duomenų paslaugų kontekste ji paprastai teikia vartotojo sąsają (UI) duomenų užklausoms."
                }
            }
        },
        {
            "uri": "http://publications.europa.eu/resource/authority/data-service-type/OP_DATPRO",
            "code": "OP_DATPRO",
            "valid_since": date(2021, 8, 30),
            "translations": {
                "en": {
                    "label": "OP DATPRO service",
                },
                "lt": {
                    "label": "Operacinė/testuojama paslauga",
                }
            }
        },
        {
            "uri": "http://publications.europa.eu/resource/authority/data-service-type/SPARQL_ENDPOINT",
            "code": "SPARQL_ENDPOINT",
            "valid_since": date(2021, 8, 30),
            "translations": {
                "en": {
                    "label": "SPARQL endpoint",
                    "description": "A SPARQL endpoint is a point of access over an HTTP network that is able to process SPARQL protocol requests. Therefore, it allows agents, be they human or software, to query the knowledge base it stores through the standard query language and protocol for RDF (SPARQL).",
                },
                "lt": {
                    "label": "SPARQL paslauga",
                    "description": "SPARQL galinis taškas yra prieigos taškas per HTTP tinklą, kuris gali apdoroti SPARQL protokolo užklausas. Todėl jis leidžia agentams, nesvarbu, ar jie yra žmonės, ar programinė įranga, užklausti žinių bazę, kurią jis saugo, naudodamas standartinę užklausų kalbą ir protokolą skirtą RDF (SPARQL)."
                }
            }
        },
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0013_applicablelegislation'),
    ]

    operations = [
        migrations.RunPython(create_concept_schema, delete_concept_schema),
    ]
