# Generated by Django 3.2.23 on 2023-11-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0013_auto_20231108_1026'),
        ('vitrina_classifiers', '0013_generate_frequency_fk'),
    ]

    operations = [
    ]
