# Generated by Django 3.2.16 on 2023-03-23 12:40

from django.db import migrations, models


def fix_null_fields(apps, schema_editor):
    Dataset = apps.get_model("vitrina_datasets", "Dataset")
    for object in Dataset.objects.all():
        if not object.description_old:
            object.description_old = ''
        if not object.title_old:
            object.title_old = ''
        if not object.title_en_old:
            object.title_en_old = ''
        if not object.description_en_old:
            object.description_en_old = ''
        object.save()


def create_translations_for_category(apps, schema_editor):
    categories = Category.objects.all()
    category_transation = apps.get_model('vitrina_classifiers', 'CategoryTranslation')
    for cat in categories:
        category_transation.objects.create(
            master_id=cat.pk,
            language_code='lt',
            title=cat.title_old,
            description=cat.description_old
        )
        category_transation.objects.create(
            master_id=cat.pk,
            language_code='en',
            title=cat.title_en_old,
            description=cat.description_en_old
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0007_create_translation_model'),
    ]

    operations = [
        migrations.RunPython(fix_null_fields),
        migrations.RunPython(create_translations),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0013_translate_rest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description_old',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_en_old',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_old',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='title_en_old',
        ),
        migrations.RemoveField(
            model_name='frequency',
            name='title_old',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='description_old',
        ),
        migrations.RemoveField(
            model_name='licence',
            name='title_old',
        ),
    ]
