# Generated by Django 3.2.25 on 2025-08-26 13:06
from datetime import date
from django.db import migrations

concept_schema_uri="http://publications.europa.eu/resource/authority/distribution-status"


def create_concept_schema(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    schema, created = ConceptSchema.objects.get_or_create(
        uri=concept_schema_uri,
    )
    if created:
        schema.set_current_language("lt")
        schema.label = "Pasiskirstymo būsena"
        schema.description = "Duomenų pasiskirstymo būsena"
        schema.save()
        schema.set_current_language("en")
        schema.label = "Distribution status"
        schema.description = "Data distribution status"
        schema.save()


def create_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    concept_schema = ConceptSchema.objects.get(
        uri=concept_schema_uri,
    )

    concepts_data = [
        {
            "uri": "http://publications.europa.eu/resource/authority/distribution-status/COMPLETED",
            "code": "COMPLETED",
            "valid_since": date(2015, 10, 23),
            "translations": {
                "en": {
                    "label": "Completed",
                    "description": "This distribution is considered to be complete, it holds all information that is intended.",
                },
                "lt": {
                    "label": "Įgyvendintas – veikiantis",
                    "description": "Ši distribucija laikoma įgyvendinta – veikiančia, joje yra visa reikiama informacija.",
                },
            },
        },
        {
            "uri": "http://publications.europa.eu/resource/authority/distribution-status/DEVELOP",
            "code": "DEVELOP",
            "valid_since": date(2015, 10, 23),
            "translations": {
                "en": {
                    "label": "Under development",
                    "description": "This distribution is currently being assembled. It may be in an incomplete or faulty state.",
                },
                "lt": {
                    "label": "Kuriamas",
                    "description": "Ši distribucija yra kuriama. Ji gali būti nebaigta arba klaidinga.",
                },
            },
        },
        {
            "code": "PLANNED",
            "valid_since": date(2019, 1, 1),
            "translations": {
                "en": {
                    "label": "Planned",
                    "description": "The development of this distribution is planned.",
                },
                "lt": {
                    "label": "Kūrimas suplanuotas",
                    "description": "Šios distribucijos kūrimas suplanuotas.",
                },
            },
        },
        {
            "code": "DEPRECATED",
            "valid_since": date(2015, 10, 23),
            "translations": {
                "en": {
                    "label": "Deprecated",
                    "description": "It is recommended that the contents of this distribution no longer be used.",
                },
                "lt": {
                    "label": "Pasenęs",
                    "description": "Rekomenduojama nebenaudoti šios distribucijos turinio."
                }
            }
        },
        {
            "code": "WITHDRAWN",
            "valid_since": date(2015, 10, 23),
            "translations": {
                "en": {
                    "label": "Withdrawn",
                    "description": "This distribution is no longer meant to be published.",
                },
                "lt": {
                    "label": "Atsisakytas",
                    "description": "Ši distribucija neturėtų būti publikuojama."
                }
            }
        }
    ]

    for data in concepts_data:
        concept, created = Concept.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": data.get("uri"),
                "valid_since": data["valid_since"],
            },
        )
        if created:
            for lang, fields in data["translations"].items():
                concept.set_current_language(lang)
                concept.label = fields["label"]
                concept.description = fields["description"]
            concept.save()
        concept.concept_schemas.add(concept_schema)


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_classifiers", "0014_concept_schema_addition"),
    ]

    operations = [
        migrations.RunPython(create_concept_schema, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_concepts, reverse_code=migrations.RunPython.noop),
    ]
