# Generated by Django 3.2.25 on 2025-08-26 13:01

from django.db import migrations

# Generated by Django 3.2.25 on 2025-08-19 11:43

from django.db import migrations

URI="http://publications.europa.eu/resource/authority/distribution-status"


def create_concept_schema(apps, schema_editor):
    concept_schema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    schema, created = concept_schema.objects.get_or_create(
        uri=URI,
    )
    if created:
        schema.set_current_language("lt")
        schema.label = "Pasiskirstymo būsena"
        schema.description = "Duomenų pasiskirstymo būsena"
        schema.save()
        schema.set_current_language("en")
        schema.label = "Distribution status"
        schema.description = "Data distribution status"
        schema.save()

def delete_concept_schema(apps, schema_editor):
    model = apps.get_model("vitrina_classifiers", "ConceptSchema")
    model.objects.filter(uri=URI).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0014_concept_schema_addition'),
    ]

    operations = [
        migrations.RunPython(create_concept_schema, delete_concept_schema)
    ]
