# Generated by Django 3.2.25 on 2025-08-26 13:06
from datetime import date

from django.db import migrations


def create_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    concept_schema = ConceptSchema.objects.get(
        uri="http://publications.europa.eu/resource/authority/distribution-status"
    )

    concepts_data = [
        {
            "uri": "http://publications.europa.eu/resource/authority/distribution-status/COMPLETED",
            "code": "COMPLETED",
            "valid_since": date(2015, 10, 23),
            "label": "completed",
            "description": "This distribution is considered to be complete, it holds all information that is intended.",
        },
        {
            "uri": "http://publications.europa.eu/resource/authority/distribution-status/DEVELOP",
            "code": "DEVELOP",
            "valid_since": date(2015, 10, 23),
            "label": "under development",
            "description": "This distribution is currently being assembled. It may be in an incomplete or faulty state.",
        },
        {
            "code": "PLANNED",
            "valid_since": date(2019, 1, 1),
            "label": "development planned",
            "description": "The development of this distribution is planned.",
        },
    ]

    for data in concepts_data:
        concept, created = Concept.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": data.get("uri"),
                "valid_since": data["valid_since"],
            },
        )
        if created:
            concept.label = data["label"]
            concept.description = data["description"]
            concept.save()
        concept.concept_schemas.add(concept_schema)


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_classifiers", "0015_distribution_status_concept_schema"),
    ]

    operations = [
        migrations.RunPython(create_concepts, reverse_code=migrations.RunPython.noop),
    ]
