# Generated by Django 4.2.23 on 2025-10-20 06:00

from django.db import migrations


def create_dataset_group_category_uri_objects(apps, schema_editor):
    Category = apps.get_model("vitrina_classifiers", "Category")
    DatasetGroupCategoryUri = apps.get_model("vitrina_datasets", "DatasetGroupCategoryUri")

    for category in Category.objects.all():
        for group in category.groups.all():

            DatasetGroupCategoryUri.objects.create(
                group=group,
                category=category,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0015_concepts_with_distribution_status'),
        ('vitrina_datasets', '0030_dataset_is_hvd_datasetgroup_name_and_more'),
        ('vitrina_resources', '0010_datasetdistribution_is_hvd'),
    ]

    operations = [
        migrations.RunPython(create_dataset_group_category_uri_objects),
        migrations.RemoveField(
            model_name='category',
            name='groups',
        ),
    ]
