# Generated by Django 4.2.23 on 2025-10-22 06:51

from django.db import migrations


def set_default_status(apps, schema_editor):
    Status = apps.get_model("vitrina_classifiers", "Status")

    Status.objects.filter(is_default=True).update(is_default=False)

    Status.objects.filter(codename="develop").update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0016_remove_category_groups'),
    ]

    operations = [
        migrations.RunPython(set_default_status, reverse_code=migrations.RunPython.noop),
    ]
