# Generated by Django 3.2.25 on 2024-11-12 11:33

from django.db import migrations, models
import django.db.models.deletion

def add_existing_organizations_to_many_to_many(apps, schema_editor):
    aom = apps.get_model('vitrina_classifiers', 'AreaOfManagement')
    org = apps.get_model('vitrina_orgs', 'Organization')

    for aom in aom.objects.all():
        organizations = org.objects.filter(jurisdiction=aom)
        aom.organizations.set(organizations)

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0032_auto_20241108_0942'),
        ('vitrina_classifiers', '0016_areaofmanagement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofmanagement',
            options={'verbose_name': 'Valdymo sritis', 'verbose_name_plural': 'Valdymo sritys'},
        ),
        migrations.AddField(
            model_name='areaofmanagement',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='areas_of_management', to='vitrina_orgs.Organization', verbose_name='Organizacijos'),
        ),
        migrations.AlterField(
            model_name='areaofmanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='areaofmanagement',
            name='name_en',
            field=models.CharField(default='Unassigned', max_length=255, verbose_name='Pavadinimas angliškai'),
        ),
        migrations.AlterField(
            model_name='areaofmanagement',
            name='name_lt',
            field=models.CharField(default='Nepriskirta', max_length=255, verbose_name='Pavadinimas lietuviškai'),
        ),
        migrations.RunPython(
            code=add_existing_organizations_to_many_to_many,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
