# Generated by Django 4.2.28 on 2026-03-12 15:29

from django.db import migrations
from django.utils import timezone


CONCEPT_SCHEMA_URI = "https://data.gov.lt/id/non-standard/DataServiceStandard"

def add_standard_schema_and_uapi_concept(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema, created = ConceptSchema.objects.get_or_create(uri=CONCEPT_SCHEMA_URI)
    schema.set_current_language("lt")
    schema.label = "DataService standartas"
    schema.description = "Duomenų paslaugos standartas, atitinkantis dct:conformsTo."
    schema.set_current_language("en")
    schema.label = "DataService standard"
    schema.description = "Data service standard, corresponds to dct:conformsTo."
    schema.save()

    concept, created = Concept.objects.get_or_create(code="UAPI", defaults={"valid_since": "2026-03-13"})
    concept.concept_schemas.add(schema)
    concept.uri = "https://ivpk.github.io/uapi/"
    concept.set_current_language("lt")
    concept.label = "UDTS"
    concept.description = "Universali duomenų teikimo sąsajos specifikacija, pateikta kaip OpenAPI JSON failas Lietuvos valstybės institucijoms kaip šablonas, skirtas API įgyvendinimui duomenų mainams standartizuotu ir sąveikiu būdu."
    concept.set_current_language("en")
    concept.label = "UAPI"
    concept.description = "Universal API specification, provided as OpenAPI JSON file for Lithuanian government institutions as a template for implementing APIs for data exchange in a standardized and interoperable manner."
    concept.save()



class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0017_set_default_status_to_develop'),
    ]

    operations = [
        migrations.RunPython(add_standard_schema_and_uapi_concept, migrations.RunPython.noop)
    ]
