# Generated by Django 4.2.29 on 2026-04-27 14:07

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid


def add_concept_schemas(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema, created = ConceptSchema.objects.get_or_create(uri="dcataplt:RuleType")
    schema.set_current_language("lt")
    schema.label = "Taisyklės tipas"
    schema.description = "Taisyklės tipas"
    schema.set_current_language("en")
    schema.label = "Rule type"
    schema.description = "Rule type"
    schema.save()

    schema, created = ConceptSchema.objects.get_or_create(
        uri="http://publications.europa.eu/resource/authority/dataset-type"
    )
    schema.set_current_language("lt")
    schema.label = "Duomenų rinkinio tipas"
    schema.description = "Duomenų rinkinio tipas"
    schema.set_current_language("en")
    schema.label = "Dataset type"
    schema.description = "Dataset type"
    schema.save()

    schema, created = ConceptSchema.objects.get_or_create(uri="https://data.gov.lt/id/non-standard/DatasetStandard")
    schema.set_current_language("lt")
    schema.label = "Duomenų rinkinio standartas"
    schema.description = "Duomenų rinkinio standartas. Atitinka dct:conformsTo."
    schema.set_current_language("en")
    schema.label = "Dataset standard"
    schema.description = "Dataset standard. Corresponds to dct:conformsTo."
    schema.save()

    language_schema, created = ConceptSchema.objects.get_or_create(
        uri="http://publications.europa.eu/resource/authority/language"
    )
    language_schema.set_current_language("lt")
    language_schema.label = "Kalba"
    language_schema.description = "Kalba"
    language_schema.set_current_language("en")
    language_schema.label = "Language"
    language_schema.description = "Language"
    language_schema.save()

    concept, created = Concept.objects.get_or_create(
        code="LIT",
        defaults={
            "uri": "http://publications.europa.eu/resource/authority/language/LIT",
            "valid_since": "2012-06-27",
        }
    )
    concept.concept_schemas.add(language_schema)
    concept.set_current_language("lt")
    concept.label = "Lietuvių kalba"
    concept.description = "Lietuvių kalba"
    concept.set_current_language("en")
    concept.label = "Lithuanian"
    concept.description = "Lithuanian"
    concept.save()

    concept, created = Concept.objects.get_or_create(
        code="ENG",
        defaults={
            "uri": "http://publications.europa.eu/resource/authority/language/ENG",
            "valid_since": "2012-06-27",
        }
    )
    concept.concept_schemas.add(language_schema)
    concept.set_current_language("lt")
    concept.label = "Anglų kalba"
    concept.description = "Anglų kalba"
    concept.set_current_language("en")
    concept.label = "English"
    concept.description = "English"
    concept.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0018_add_udts_concept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
            ],
            options={
                'verbose_name': 'Veikla',
                'verbose_name_plural': 'Veiklos',
            },
        ),
        migrations.CreateModel(
            name='ProvenanceStatement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Pavadinimas')),
                ('url', models.URLField(max_length=255, verbose_name='Nuoroda')),
            ],
            options={
                'verbose_name': 'Kilmė',
                'verbose_name_plural': 'Kilmės',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('identifier', models.CharField(help_text='Naudojamas taisyklės identifikatorius. Jei nenaudojamas - nurodomas skaičius, pvz. 1. Atitinka dct:identifier.', max_length=255, verbose_name='Identifikatorius')),
                ('implements', models.ManyToManyField(blank=True, help_text='Nurodo teisės aktą, kurį įgyvendina taisyklė. Atitinka cpsv:implements.', related_name='rules', to='vitrina_classifiers.applicablelegislation', verbose_name='Įgyvendina')),
                ('language', models.ManyToManyField(blank=True, help_text='Nurodo taisyklės kalbą. Atitinka dct:language.', limit_choices_to={'concept_schemas__uri': 'http://publications.europa.eu/resource/authority/language'}, related_name='rules_by_language', to='vitrina_classifiers.concept', verbose_name='Kalba')),
                ('rule_type', models.ManyToManyField(blank=True, help_text='Nurodo taisyklės tipą. Atitinka dct:type.', limit_choices_to={'concept_schemas__uri': 'dcataplt:RuleType'}, related_name='rules_by_type', to='vitrina_classifiers.concept', verbose_name='Tipas')),
            ],
            options={
                'verbose_name': 'Taisyklė',
                'verbose_name_plural': 'Taisyklės',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceQualityPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, unique=True)),
            ],
            options={
                'verbose_name': 'Paslaugos kokybės puslapis',
                'verbose_name_plural': 'Paslaugos kokybės puslapiai',
            },
        ),
        migrations.CreateModel(
            name='RuleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.rule')),
            ],
            options={
                'verbose_name': 'Taisyklė Translation',
                'db_table': 'vitrina_classifiers_rule_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(add_concept_schemas, migrations.RunPython.noop),
    ]
