# Generated by Django 3.2.25 on 2025-01-21 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_classifiers", "0018_auto_20250108_0747"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="name",
        ),
    ]
