# Generated by Django 4.2.29 on 2026-06-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0018_add_udts_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thematic',
            field=models.BooleanField(default=False),
        ),
    ]
