# Generated by Django 4.2.29 on 2026-05-22 13:11

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0019_activity_provenancestatement_rule_servicequalitypage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldHelpText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('dcat_information_system', 'DCAT: Informacinė sistema'), ('dcat_service', 'DCAT: Paslauga'), ('dcat_dataset', 'DCAT: Duomenų rinkinys'), ('dcat_distribution', 'DCAT: Pateiktis')], max_length=255, verbose_name='Formos pavadinimas')),
                ('field_name', models.CharField(max_length=255, verbose_name='Lauko pavadinimas')),
            ],
            options={
                'verbose_name': 'Formos lauko pagalbinis tekstas',
                'verbose_name_plural': 'Formų laukų pagalbiniai tekstai',
                'unique_together': {('form_name', 'field_name')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormFieldHelpTextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('help_text', models.TextField(blank=True, verbose_name='Pagalbinis tekstas')),
                ('extended_help_text', models.TextField(blank=True, help_text="Išplėstinis pagalbinis tekstas bus rodomas kaip iššokantis paspaudus 'i' ikonėlę, jei forma tai palaiko", verbose_name='Išplėstinis pagalbinis tekstas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.formfieldhelptext')),
            ],
            options={
                'verbose_name': 'Formos lauko pagalbinis tekstas Translation',
                'db_table': 'vitrina_classifiers_formfieldhelptext_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
