# Generated by Django 3.2.25 on 2025-01-21 13:51

from django.db import migrations, models


def create_category_mappings(apps, schema_editor):
    GeoportalCategory = apps.get_model("vitrina_classifiers", "GeoportalCategory")

    categories = [
        "biota",
        "boundaries",
        "climatologyMeteorologyAtmosphere",
        "disaster",
        "economy",
        "elevation",
        "environment",
        "farming",
        "geoscientificInformation",
        "health",
        "imageryBaseMapsEarthCover",
        "inlandWaters",
        "location",
        "oceans",
        "planningCadastre",
        "society",
        "structure",
        "transportation",
        "utilitiesCommunication",
    ]

    for category in categories:
        GeoportalCategory.objects.create(title=category)


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_classifiers", "0019_auto_20250121_1544"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoportalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Pavadinimas")),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        to="vitrina_classifiers.Category",
                        verbose_name="Atitinkančios kategorijos",
                    ),
                ),
            ],
            options={
                "db_table": "geoportal_category",
            },
        ),
        migrations.RunPython(create_category_mappings),
    ]
