# Generated by Django 4.2.29 on 2026-06-01 05:21
from datetime import date

from django.db import migrations, models
import uuid

CONCEPT_SCHEMA_URI = "http://purl.org/adms/status/"


SPATIAL_COVERAGES = [
    "Lietuva",
    "Vilniaus apskritis",
    "Alytaus apskritis",
    "Kauno apskritis",
    "Klaipėdos apskritis",
    "Marijampolės apskritis",
    "Panevėžio apskritis",
    "Šiaulių apskritis",
    "Tauragės apskritis",
    "Telšių apskritis",
    "Utenos apskritis",
    "Akmenės rajono savivaldybė",
    "Alytaus miesto savivaldybė",
    "Alytaus rajono savivaldybė",
    "Anykščių rajono savivaldybė",
    "Birštono savivaldybė",
    "Biržų rajono savivaldybė",
    "Druskininkų savivaldybė",
    "Elektrėnų savivaldybė",
    "Ignalinos rajono savivaldybė",
    "Jonavos rajono savivaldybė",
    "Joniškio rajono savivaldybė",
    "Jurbarko rajono savivaldybė",
    "Kaišiadorių rajono savivaldybė",
    "Kalvarijos savivaldybė",
    "Kauno miesto savivaldybė",
    "Kauno rajono savivaldybė",
    "Kazlų Rūdos savivaldybė",
    "Kėdainių rajono savivaldybė",
    "Kelmės rajono savivaldybė",
    "Klaipėdos miesto savivaldybė",
    "Klaipėdos rajono savivaldybė",
    "Kretingos rajono savivaldybė",
    "Kupiškio rajono savivaldybė",
    "Lazdijų rajono savivaldybė",
    "Marijampolės savivaldybė",
    "Mažeikių rajono savivaldybė",
    "Molėtų rajono savivaldybė",
    "Neringos savivaldybė",
    "Pagėgių savivaldybė",
    "Pakruojo rajono savivaldybė",
    "Palangos miesto savivaldybė",
    "Panevėžio miesto savivaldybė",
    "Panevėžio rajono savivaldybė",
    "Pasvalio rajono savivaldybė",
    "Plungės rajono savivaldybė",
    "Prienų rajono savivaldybė",
    "Radviliškio rajono savivaldybė",
    "Raseinių rajono savivaldybė",
    "Rietavo savivaldybė",
    "Rokiškio rajono savivaldybė",
    "Skuodo rajono savivaldybė",
    "Šakių rajono savivaldybė",
    "Šalčininkų rajono savivaldybė",
    "Šiaulių miesto savivaldybė",
    "Šiaulių rajono savivaldybė",
    "Šilalės rajono savivaldybė",
    "Šilutės rajono savivaldybė",
    "Širvintų rajono savivaldybė",
    "Švenčionių rajono savivaldybė",
    "Tauragės rajono savivaldybė",
    "Telšių rajono savivaldybė",
    "Trakų rajono savivaldybė",
    "Ukmergės rajono savivaldybė",
    "Utenos rajono savivaldybė",
    "Varėnos rajono savivaldybė",
    "Vilkaviškio rajono savivaldybė",
    "Vilniaus miesto savivaldybė",
    "Vilniaus rajono savivaldybė",
    "Visagino savivaldybė",
    "Zarasų rajono savivaldybė",
]


def seed_spatial_coverages(apps, schema_editor):
    SpatialCoverage = apps.get_model("vitrina_classifiers", "SpatialCoverage")
    SpatialCoverage.objects.bulk_create(
        [
            SpatialCoverage(uuid=uuid.uuid4(), name=name, order=index)
            for index, name in enumerate(SPATIAL_COVERAGES)
        ],
        ignore_conflicts=True,
    )


def create_concept_schema(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")

    schema, created = ConceptSchema.objects.get_or_create(uri=CONCEPT_SCHEMA_URI)
    if created:
        schema.set_current_language("lt")
        schema.label = "ADMS paslaugos statusas"
        schema.description = "E. paslaugos brandos lygmens statusas pagal ADMS specifikaciją"
        schema.save()
        schema.set_current_language("en")
        schema.label = "ADMS status"
        schema.description = "Asset maturity status as defined by the ADMS specification"
        schema.save()


def create_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    concept_schema = ConceptSchema.objects.get(uri=CONCEPT_SCHEMA_URI)

    concepts_data = [
        {
            "uri": "http://purl.org/adms/status/Completed",
            "code": "ADMS_COMPLETED",
            "translations": {
                "en": {"label": "Completed", "description": "The asset is complete."},
                "lt": {"label": "Baigta", "description": "E. paslauga yra baigta."},
            },
        },
        {
            "uri": "http://purl.org/adms/status/Deprecated",
            "code": "ADMS_DEPRECATED",
            "translations": {
                "en": {"label": "Deprecated", "description": "The asset is deprecated."},
                "lt": {"label": "Pasenusi", "description": "E. paslauga yra pasenusi."},
            },
        },
        {
            "uri": "http://purl.org/adms/status/UnderDevelopment",
            "code": "ADMS_UNDER_DEVELOPMENT",
            "translations": {
                "en": {"label": "Under development", "description": "The asset is being developed."},
                "lt": {"label": "Kuriama", "description": "E. paslauga yra kuriama."},
            },
        },
        {
            "uri": "http://purl.org/adms/status/Withdrawn",
            "code": "ADMS_WITHDRAWN",
            "translations": {
                "en": {"label": "Withdrawn", "description": "The asset has been withdrawn."},
                "lt": {"label": "Atšaukta", "description": "E. paslauga yra atšaukta."},
            },
        },
    ]

    for data in concepts_data:
        concept, created = Concept.objects.get_or_create(
            uri=data["uri"],
            defaults={"code": data["code"], "valid_since": date(2013, 9, 9)},
        )
        if created:
            for lang, fields in data["translations"].items():
                concept.set_current_language(lang)
                concept.label = fields["label"]
                concept.description = fields["description"]
            concept.save()
        concept.concept_schemas.add(concept_schema)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0019_activity_formfieldhelptext_provenancestatement_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialCoverage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('order', models.PositiveIntegerField(verbose_name='Eilės numeris')),
            ],
            options={
                'verbose_name': 'Teritorinė aprėptis',
                'verbose_name_plural': 'Teritorinės aprėptys',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='formfieldhelptext',
            name='form_name',
            field=models.CharField(choices=[('dcat_information_system', 'DCAT: Informacinė sistema'), ('dcat_service', 'DCAT: Paslauga'), ('dcat_dataset', 'DCAT: Duomenų rinkinys'), ('dcat_distribution', 'DCAT: Pateiktis'), ('dcat_is_relationships', 'DCAT: IS ryšiai'), ('dcat_service_relationships', 'DCAT: Paslaugos ryšiai'), ('dcat_dataset_relationships', 'DCAT: Duomenų rinkinio ryšiai'), ('dcat_is_public_service', 'DCAT: E. paslauga')], max_length=255, verbose_name='Formos pavadinimas'),
        ),
        migrations.RunPython(seed_spatial_coverages, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_concept_schema, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_concepts, reverse_code=migrations.RunPython.noop),
    ]
