# Generated by Django 4.2.29 on 2026-06-22 13:06
from datetime import date

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import uuid

def add_concept_schemas(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema, created = ConceptSchema.objects.get_or_create(uri="dcataplt:RuleType")
    schema.set_current_language("lt")
    schema.label = "Taisyklės tipas"
    schema.description = "Taisyklės tipas"
    schema.set_current_language("en")
    schema.label = "Rule type"
    schema.description = "Rule type"
    schema.save()

    schema, created = ConceptSchema.objects.get_or_create(
        uri="http://publications.europa.eu/resource/authority/dataset-type"
    )
    schema.set_current_language("lt")
    schema.label = "Duomenų rinkinio tipas"
    schema.description = "Duomenų rinkinio tipas"
    schema.set_current_language("en")
    schema.label = "Dataset type"
    schema.description = "Dataset type"
    schema.save()

    schema, created = ConceptSchema.objects.get_or_create(uri="https://data.gov.lt/id/non-standard/DatasetStandard")
    schema.set_current_language("lt")
    schema.label = "Duomenų rinkinio standartas"
    schema.description = "Duomenų rinkinio standartas. Atitinka dct:conformsTo."
    schema.set_current_language("en")
    schema.label = "Dataset standard"
    schema.description = "Dataset standard. Corresponds to dct:conformsTo."
    schema.save()

    language_schema, created = ConceptSchema.objects.get_or_create(
        uri="http://publications.europa.eu/resource/authority/language"
    )
    language_schema.set_current_language("lt")
    language_schema.label = "Kalba"
    language_schema.description = "Kalba"
    language_schema.set_current_language("en")
    language_schema.label = "Language"
    language_schema.description = "Language"
    language_schema.save()

    concept, created = Concept.objects.get_or_create(
        code="LIT",
        defaults={
            "uri": "http://publications.europa.eu/resource/authority/language/LIT",
            "valid_since": "2012-06-27",
        }
    )
    concept.concept_schemas.add(language_schema)
    concept.set_current_language("lt")
    concept.label = "Lietuvių kalba"
    concept.description = "Lietuvių kalba"
    concept.set_current_language("en")
    concept.label = "Lithuanian"
    concept.description = "Lithuanian"
    concept.save()

    concept, created = Concept.objects.get_or_create(
        code="ENG",
        defaults={
            "uri": "http://publications.europa.eu/resource/authority/language/ENG",
            "valid_since": "2012-06-27",
        }
    )
    concept.concept_schemas.add(language_schema)
    concept.set_current_language("lt")
    concept.label = "Anglų kalba"
    concept.description = "Anglų kalba"
    concept.set_current_language("en")
    concept.label = "English"
    concept.description = "English"
    concept.save()

    schema, created = ConceptSchema.objects.get_or_create(
        uri="http://publications.europa.eu/resource/authority/planned-availability"
    )
    schema.set_current_language("lt")
    schema.label = "Planuojamas prieinamumas"
    schema.description = "Planuojamas prieinamumas"
    schema.set_current_language("en")
    schema.label = "Planned availability"
    schema.description = "Planned availability"
    schema.save()

    schema, created = ConceptSchema.objects.get_or_create(
        uri="https://data.gov.lt/id/non-standard/DistributionStandard"
    )
    schema.set_current_language("lt")
    schema.label = "Pateikties standartas"
    schema.description = "Pateikties standartas. Atitinka dct:conformsTo."
    schema.set_current_language("en")
    schema.label = "Distribution standard"
    schema.description = "Distribution standard. Corresponds to dct:conformsTo."
    schema.save()


IMPORTANCE_SCHEMA_URI = "dcataplt:Importance"
TYPE_SCHEMA_URI = "dcataplt:Type"

importance_concepts_data = [
    {
        "code": "highlyImportant",
        "uri": "dcataplt:Importance/highlyImportant",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Ypatingos svarbos",
            },
            "en": {
                "label": "Highly Important",
            },
        },
    },
    {
        "code": "important",
        "uri": "dcataplt:Importance/important",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Svarbūs",
            },
            "en": {
                "label": "Important",
            },
        },
    },
    {
        "code": "moderatelyImportant",
        "uri": "dcataplt:Importance/moderatelyImportant",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Vidutinės svarbos",
            },
            "en": {
                "label": "Moderately Important",
            },
        },
    },
    {
        "code": "slightlyImportant",
        "uri": "dcataplt:Importance/slightlyImportant",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Mažos svarbos",
            },
            "en": {
                "label": "Slightly Important",
            },
        },
    },
]

type_concepts_data = [
    {
        "code": "registerInformationSystem",
        "uri": "dcataplt:Type/registerInformationSystem",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Registro informacinė sistema",
            },
            "en": {
                "label": "Register Information System",
            },
        },
    },
    {
        "code": "stateInformationSystem",
        "uri": "dcataplt:Type/stateInformationSystem",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Valstybės informacinė sistema",
            },
            "en": {
                "label": "State Information System",
            },
        },
    },
    {
        "code": "internalInformationSystem",
        "uri": "dcataplt:Type/internalInformationSystem",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Vidaus administravimo informacinė sistema",
            },
            "en": {
                "label": "Internal Information System",
            },
        },
    },
]

BASE_FREQUENCY_URI = "http://publications.europa.eu/resource/authority/frequency"

frequency_data = [
    {"code": "ANNUAL",       "hours": 8760,   "title": "Kasmet",                  "title_en": "Once a year"},
    {"code": "ANNUAL_2",     "hours": 4380,   "title": "Dukart per metus",         "title_en": "Twice a year"},
    {"code": "ANNUAL_3",     "hours": 2920,   "title": "Triskart per metus",       "title_en": "Three times a year"},
    {"code": "BIDECENNIAL",  "hours": 175200, "title": "Kas 20 metų",              "title_en": "Every twenty years"},
    {"code": "BIENNIAL",     "hours": 17520,  "title": "Kas 2 metai",              "title_en": "Every two years"},
    {"code": "BIHOURLY",     "hours": 2,      "title": "Kas 2 valandas",           "title_en": "Every two hours"},
    {"code": "BIMONTHLY",    "hours": 1440,   "title": "Kas 2 mėnesiai",           "title_en": "Every two months"},
    {"code": "BIWEEKLY",     "hours": 336,    "title": "Kas 2 savaitės",           "title_en": "Every two weeks"},
    {"code": "CONT",         "hours": 13,     "title": "Dažniau nei kasdien",      "title_en": "More frequent than daily"},
    {"code": "DAILY",        "hours": 24,     "title": "Kasdien",                  "title_en": "Once a day"},
    {"code": "DAILY_2",      "hours": 12,     "title": "Dukart per dieną",         "title_en": "Twice a day"},
    {"code": "DAILY_3",      "hours": 8,      "title": "Triskart per dieną",       "title_en": "Three times a day"},
    {"code": "DECENNIAL",    "hours": 87600,  "title": "Kas 10 metų",              "title_en": "Every ten years"},
    {"code": "HOURLY",       "hours": 1,      "title": "Kas valandą",              "title_en": "Every hour"},
    {"code": "IRREG",        "hours": 0,      "title": "Nevienodu periodiškumu",   "title_en": "At uneven intervals"},
    {"code": "MONTHLY",      "hours": 720,    "title": "Kas mėnesį",               "title_en": "Once a month"},
    {"code": "MONTHLY_2",    "hours": 360,    "title": "Dukart per mėnesį",        "title_en": "Twice a month"},
    {"code": "MONTHLY_3",    "hours": 240,    "title": "Triskart per mėnesį",      "title_en": "Three times a month"},
    {"code": "NEVER",        "hours": 0,      "title": "Neatnaujinamas",           "title_en": "Never updated"},
    {"code": "OP_DATPRO",    "hours": 0,      "title": "Operacinis",               "title_en": "Operational (test)"},
    {"code": "OTHER",        "hours": 0,      "title": "Neapibrėžtu periodiškumu", "title_en": "With unknown regularity"},
    {"code": "QUADRENNIAL",  "hours": 35040,  "title": "Kas 4 metai",              "title_en": "Every four years"},
    {"code": "QUARTERLY",    "hours": 2160,   "title": "Kas 3 mėnesiai",           "title_en": "Every three months"},
    {"code": "QUINQUENNIAL", "hours": 43800,  "title": "Kas 5 metai",              "title_en": "Every five years"},
    {"code": "TRIDECENNIAL", "hours": 262800, "title": "Kas 30 metų",              "title_en": "Every thirty years"},
    {"code": "TRIENNIAL",    "hours": 26280,  "title": "Kas 3 metai",              "title_en": "Every three years"},
    {"code": "TRIHOURLY",    "hours": 3,      "title": "Kas 3 valandos",           "title_en": "Every three hours"},
    {"code": "UNKNOWN",      "hours": 0,      "title": "Nežinomas",                "title_en": "Unknown interval"},
    {"code": "UPDATE_CONT",  "hours": 8760,   "title": "Nepertraukiamas",          "title_en": "Without interruption"},
    {"code": "WEEKLY",       "hours": 168,    "title": "Kas savaitę",              "title_en": "Once a week"},
    {"code": "WEEKLY_2",     "hours": 84,     "title": "Dukart per savaitę",       "title_en": "Twice a week"},
    {"code": "WEEKLY_3",     "hours": 56,     "title": "Triskart per savaitę",     "title_en": "Three times a week"},
]


def add_importance_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema = ConceptSchema.objects.get(uri=IMPORTANCE_SCHEMA_URI)

    for data in importance_concepts_data:
        concept, created = Concept.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": data["uri"],
                "valid_since": data["valid_since"],
            },
        )
        if created:
            for lang, fields in data["translations"].items():
                concept.set_current_language(lang)
                concept.label = fields["label"]
                concept.description = fields.get("description", "")
            concept.save()
        concept.concept_schemas.add(schema)


def add_type_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema = ConceptSchema.objects.get(uri=TYPE_SCHEMA_URI)

    for data in type_concepts_data:
        concept, created = Concept.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": data["uri"],
                "valid_since": data["valid_since"],
            },
        )
        if created:
            for lang, fields in data["translations"].items():
                concept.set_current_language(lang)
                concept.label = fields["label"]
                concept.description = fields.get("description", "")
            concept.save()
        concept.concept_schemas.add(schema)


def add_frequency_values(apps, schema_editor):
    Frequency = apps.get_model("vitrina_classifiers", "Frequency")

    for data in frequency_data:
        Frequency.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": f"{BASE_FREQUENCY_URI}/{data['code']}",
                "hours": data["hours"],
                "title": data["title"],
                "title_en": data["title_en"],
            },
        )


STATUS_CONCEPT = "http://purl.org/adms/status/"


def create_status_schema_and_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema, created = ConceptSchema.objects.get_or_create(uri=STATUS_CONCEPT)
    if created:
        schema.set_current_language("lt")
        schema.label = "ADMS paslaugos statusas"
        schema.description = "E. paslaugos brandos lygmens statusas pagal ADMS specifikaciją"
        schema.save()
        schema.set_current_language("en")
        schema.label = "ADMS status"
        schema.description = "Asset maturity status as defined by the ADMS specification"
        schema.save()

    concepts_data = [
        {
            "uri": "http://purl.org/adms/status/Completed",
            "code": "ADMS_COMPLETED",
            "translations": {
                "en": {"label": "Completed", "description": "The asset is complete."},
                "lt": {"label": "Baigta", "description": "E. paslauga yra baigta."},
            },
        },
        {
            "uri": "http://purl.org/adms/status/Deprecated",
            "code": "ADMS_DEPRECATED",
            "translations": {
                "en": {"label": "Deprecated", "description": "The asset is deprecated."},
                "lt": {"label": "Pasenusi", "description": "E. paslauga yra pasenusi."},
            },
        },
        {
            "uri": "http://purl.org/adms/status/UnderDevelopment",
            "code": "ADMS_UNDER_DEVELOPMENT",
            "translations": {
                "en": {"label": "Under development", "description": "The asset is being developed."},
                "lt": {"label": "Kuriama", "description": "E. paslauga yra kuriama."},
            },
        },
        {
            "uri": "http://purl.org/adms/status/Withdrawn",
            "code": "ADMS_WITHDRAWN",
            "translations": {
                "en": {"label": "Withdrawn", "description": "The asset has been withdrawn."},
                "lt": {"label": "Atšaukta", "description": "E. paslauga yra atšaukta."},
            },
        },
    ]

    for data in concepts_data:
        concept, created = Concept.objects.get_or_create(
            uri=data["uri"],
            defaults={"code": data["code"], "valid_since": date(2013, 9, 9)},
        )
        if created:
            for lang, fields in data["translations"].items():
                concept.set_current_language(lang)
                concept.label = fields["label"]
                concept.description = fields["description"]
            concept.save()
        concept.concept_schemas.add(schema)


SPATIAL_COVERAGES = [
    "Lietuva",
    "Vilniaus apskritis",
    "Alytaus apskritis",
    "Kauno apskritis",
    "Klaipėdos apskritis",
    "Marijampolės apskritis",
    "Panevėžio apskritis",
    "Šiaulių apskritis",
    "Tauragės apskritis",
    "Telšių apskritis",
    "Utenos apskritis",
    "Akmenės rajono savivaldybė",
    "Alytaus miesto savivaldybė",
    "Alytaus rajono savivaldybė",
    "Anykščių rajono savivaldybė",
    "Birštono savivaldybė",
    "Biržų rajono savivaldybė",
    "Druskininkų savivaldybė",
    "Elektrėnų savivaldybė",
    "Ignalinos rajono savivaldybė",
    "Jonavos rajono savivaldybė",
    "Joniškio rajono savivaldybė",
    "Jurbarko rajono savivaldybė",
    "Kaišiadorių rajono savivaldybė",
    "Kalvarijos savivaldybė",
    "Kauno miesto savivaldybė",
    "Kauno rajono savivaldybė",
    "Kazlų Rūdos savivaldybė",
    "Kėdainių rajono savivaldybė",
    "Kelmės rajono savivaldybė",
    "Klaipėdos miesto savivaldybė",
    "Klaipėdos rajono savivaldybė",
    "Kretingos rajono savivaldybė",
    "Kupiškio rajono savivaldybė",
    "Lazdijų rajono savivaldybė",
    "Marijampolės savivaldybė",
    "Mažeikių rajono savivaldybė",
    "Molėtų rajono savivaldybė",
    "Neringos savivaldybė",
    "Pagėgių savivaldybė",
    "Pakruojo rajono savivaldybė",
    "Palangos miesto savivaldybė",
    "Panevėžio miesto savivaldybė",
    "Panevėžio rajono savivaldybė",
    "Pasvalio rajono savivaldybė",
    "Plungės rajono savivaldybė",
    "Prienų rajono savivaldybė",
    "Radviliškio rajono savivaldybė",
    "Raseinių rajono savivaldybė",
    "Rietavo savivaldybė",
    "Rokiškio rajono savivaldybė",
    "Skuodo rajono savivaldybė",
    "Šakių rajono savivaldybė",
    "Šalčininkų rajono savivaldybė",
    "Šiaulių miesto savivaldybė",
    "Šiaulių rajono savivaldybė",
    "Šilalės rajono savivaldybė",
    "Šilutės rajono savivaldybė",
    "Širvintų rajono savivaldybė",
    "Švenčionių rajono savivaldybė",
    "Tauragės rajono savivaldybė",
    "Telšių rajono savivaldybė",
    "Trakų rajono savivaldybė",
    "Ukmergės rajono savivaldybė",
    "Utenos rajono savivaldybė",
    "Varėnos rajono savivaldybė",
    "Vilkaviškio rajono savivaldybė",
    "Vilniaus miesto savivaldybė",
    "Vilniaus rajono savivaldybė",
    "Visagino savivaldybė",
    "Zarasų rajono savivaldybė",
]


def seed_spatial_coverages(apps, schema_editor):
    SpatialCoverage = apps.get_model("vitrina_classifiers", "SpatialCoverage")
    SpatialCoverage.objects.bulk_create(
        [
            SpatialCoverage(uuid=uuid.uuid4(), name=name, order=index)
            for index, name in enumerate(SPATIAL_COVERAGES)
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0019_category_thematic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
            ],
            options={
                'verbose_name': 'Veikla',
                'verbose_name_plural': 'Veiklos',
            },
        ),
        migrations.CreateModel(
            name='FormFieldText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(choices=[('dcat_information_system', 'DCAT: Informacinė sistema'), ('dcat_service', 'DCAT: Paslauga'), ('dcat_dataset', 'DCAT: Duomenų rinkinys'), ('dcat_distribution', 'DCAT: Pateiktis'), ('dcat_is_relationships', 'DCAT: IS ryšiai'), ('dcat_service_relationships', 'DCAT: Paslaugos ryšiai'), ('dcat_dataset_relationships', 'DCAT: Duomenų rinkinio ryšiai'), ('dcat_is_public_service', 'DCAT: E. paslauga'), ('dcat_contact', 'DCAT: Kontaktas')], max_length=255, verbose_name='Formos pavadinimas')),
                ('field_name', models.CharField(max_length=255, verbose_name='Lauko pavadinimas')),
            ],
            options={
                'verbose_name': 'Formos lauko tekstas',
                'verbose_name_plural': 'Formų laukų tekstai',
                'unique_together': {('form_name', 'field_name')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProvenanceStatement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Pavadinimas')),
                ('url', models.URLField(max_length=255, verbose_name='Nuoroda')),
            ],
            options={
                'verbose_name': 'Kilmė',
                'verbose_name_plural': 'Kilmės',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('identifier', models.CharField(help_text='Naudojamas taisyklės identifikatorius. Jei nenaudojamas - nurodomas skaičius, pvz. 1. Atitinka dct:identifier.', max_length=255, verbose_name='Identifikatorius')),
                ('implements', models.ManyToManyField(blank=True, help_text='Nurodo teisės aktą, kurį įgyvendina taisyklė. Atitinka cpsv:implements.', related_name='rules', to='vitrina_classifiers.applicablelegislation', verbose_name='Įgyvendina')),
                ('language', models.ManyToManyField(blank=True, help_text='Nurodo taisyklės kalbą. Atitinka dct:language.', limit_choices_to={'concept_schemas__uri': 'http://publications.europa.eu/resource/authority/language'}, related_name='rules_by_language', to='vitrina_classifiers.concept', verbose_name='Kalba')),
                ('rule_type', models.ManyToManyField(blank=True, help_text='Nurodo taisyklės tipą. Atitinka dct:type.', limit_choices_to={'concept_schemas__uri': 'dcataplt:RuleType'}, related_name='rules_by_type', to='vitrina_classifiers.concept', verbose_name='Tipas')),
            ],
            options={
                'verbose_name': 'Taisyklė',
                'verbose_name_plural': 'Taisyklės',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceQualityPage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.CharField(blank=True, max_length=1024, unique=True)),
            ],
            options={
                'verbose_name': 'Paslaugos kokybės puslapis',
                'verbose_name_plural': 'Paslaugos kokybės puslapiai',
            },
        ),
        migrations.CreateModel(
            name='SpatialCoverage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Pavadinimas')),
                ('order', models.PositiveIntegerField(verbose_name='Eilės numeris')),
            ],
            options={
                'verbose_name': 'Teritorinė aprėptis',
                'verbose_name_plural': 'Teritorinės aprėptys',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RuleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(verbose_name='Aprašymas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.rule')),
            ],
            options={
                'verbose_name': 'Taisyklė Translation',
                'db_table': 'vitrina_classifiers_rule_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormFieldTextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Lauko antraštė')),
                ('help_text', models.TextField(blank=True, verbose_name='Pagalbinis tekstas')),
                ('extended_help_text', models.TextField(blank=True, help_text="Išplėstinis pagalbinis tekstas bus rodomas kaip iššokantis paspaudus 'i' ikonėlę, jei forma tai palaiko", verbose_name='Išplėstinis pagalbinis tekstas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.formfieldtext')),
            ],
            options={
                'verbose_name': 'Formos lauko tekstas Translation',
                'db_table': 'vitrina_classifiers_formfieldtext_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RunPython(add_concept_schemas, migrations.RunPython.noop),
        migrations.RunPython(add_importance_concepts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_type_concepts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_frequency_values, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_status_schema_and_concepts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(seed_spatial_coverages, reverse_code=migrations.RunPython.noop),
    ]
