# Generated by Django 3.2.25 on 2025-03-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_classifiers", "0020_auto_20250121_1551"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoportalAccessRights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Pavadinimas")),
                (
                    "access_rights",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PUBLIC", "Atviri duomenys"),
                            ("RESTRICTED", "Apsaugoti duomenys"),
                            ("NON_PUBLIC", "Uždari duomenys"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Atitinkančios prieigos teisės",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geoportalo prieigos teisė",
                "verbose_name_plural": "Geoportalo prieigos teisės",
                "db_table": "geoportal_access_rights",
            },
        ),
        migrations.CreateModel(
            name="GeoportalLicence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Pavadinimas")),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitrina_classifiers.licence",
                        verbose_name="Atitinkanti licencija",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geoportalo licencija",
                "verbose_name_plural": "Geoportalo licencijos",
                "db_table": "geoportal_licence",
            },
        ),
        migrations.CreateModel(
            name="GeoportalFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Pavadinimas")),
                (
                    "frequency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vitrina_classifiers.frequency",
                        verbose_name="Atitinkantis atnaujinimo periodiškumas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geoportalo atnaujinimo periodiškumas",
                "verbose_name_plural": "Geoportalo atnaujinimo periodiškumai",
                "db_table": "geoportal_frequency",
            },
        ),
    ]
