# Generated by Django 4.2.29 on 2026-06-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0020_spatialcoverage_alter_formfieldhelptext_form_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldhelptext',
            name='form_name',
            field=models.CharField(choices=[('dcat_information_system', 'DCAT: Informacinė sistema'), ('dcat_service', 'DCAT: Paslauga'), ('dcat_dataset', 'DCAT: Duomenų rinkinys'), ('dcat_distribution', 'DCAT: Pateiktis'), ('dcat_is_relationships', 'DCAT: IS ryšiai'), ('dcat_service_relationships', 'DCAT: Paslaugos ryšiai'), ('dcat_dataset_relationships', 'DCAT: Duomenų rinkinio ryšiai'), ('dcat_is_public_service', 'DCAT: E. paslauga'), ('dcat_contact', 'DCAT: Kontaktas')], max_length=255, verbose_name='Formos pavadinimas'),
        ),
    ]
