# Generated by Django 3.2.25 on 2025-01-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_classifiers", "0020_auto_20250121_1551"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geoportalcategory",
            options={
                "verbose_name": "Geoportalo kategorija",
                "verbose_name_plural": "Geoportalo kategorijos",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text='Naudokite "glyph" pavadinimą iš icomoon.svg failo',
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children_set",
                to="vitrina_classifiers.category",
            ),
        ),
    ]
