# Generated by Django 4.2.29 on 2026-05-27 10:35

from datetime import date

from django.db import migrations

IMPORTANCE_SCHEMA_URI = "dcataplt:Importance"
TYPE_SCHEMA_URI = "dcataplt:Type"

importance_concepts_data = [
    {
        "code": "highlyImportant",
        "uri": "dcataplt:Importance/highlyImportant",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Ypatingos svarbos",
            },
            "en": {
                "label": "Highly Important",
            },
        },
    },
    {
        "code": "important",
        "uri": "dcataplt:Importance/important",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Svarbūs",
            },
            "en": {
                "label": "Important",
            },
        },
    },
    {
        "code": "moderatelyImportant",
        "uri": "dcataplt:Importance/moderatelyImportant",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Vidutinės svarbos",
            },
            "en": {
                "label": "Moderately Important",
            },
        },
    },
    {
        "code": "slightlyImportant",
        "uri": "dcataplt:Importance/slightlyImportant",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Mažos svarbos",
            },
            "en": {
                "label": "Slightly Important",
            },
        },
    },
]

type_concepts_data = [
    {
        "code": "registerInformationSystem",
        "uri": "dcataplt:Type/registerInformationSystem",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Registro informacinė sistema",
            },
            "en": {
                "label": "Register Information System",
            },
        },
    },
    {
        "code": "stateInformationSystem",
        "uri": "dcataplt:Type/stateInformationSystem",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Valstybės informacinė sistema",
            },
            "en": {
                "label": "State Information System",
            },
        },
    },
    {
        "code": "internalInformationSystem",
        "uri": "dcataplt:Type/internalInformationSystem",
        "valid_since": date(2026, 1, 1),
        "translations": {
            "lt": {
                "label": "Vidaus administravimo informacinė sistema",
            },
            "en": {
                "label": "Internal Information System",
            },
        },
    },
]

BASE_FREQUENCY_URI = "http://publications.europa.eu/resource/authority/frequency"

frequency_data = [
    {"code": "ANNUAL",       "hours": 8760,   "title": "Kasmet",                  "title_en": "Once a year"},
    {"code": "ANNUAL_2",     "hours": 4380,   "title": "Dukart per metus",         "title_en": "Twice a year"},
    {"code": "ANNUAL_3",     "hours": 2920,   "title": "Triskart per metus",       "title_en": "Three times a year"},
    {"code": "BIDECENNIAL",  "hours": 175200, "title": "Kas 20 metų",              "title_en": "Every twenty years"},
    {"code": "BIENNIAL",     "hours": 17520,  "title": "Kas 2 metai",              "title_en": "Every two years"},
    {"code": "BIHOURLY",     "hours": 2,      "title": "Kas 2 valandas",           "title_en": "Every two hours"},
    {"code": "BIMONTHLY",    "hours": 1440,   "title": "Kas 2 mėnesiai",           "title_en": "Every two months"},
    {"code": "BIWEEKLY",     "hours": 336,    "title": "Kas 2 savaitės",           "title_en": "Every two weeks"},
    {"code": "CONT",         "hours": 13,     "title": "Dažniau nei kasdien",      "title_en": "More frequent than daily"},
    {"code": "DAILY",        "hours": 24,     "title": "Kasdien",                  "title_en": "Once a day"},
    {"code": "DAILY_2",      "hours": 12,     "title": "Dukart per dieną",         "title_en": "Twice a day"},
    {"code": "DAILY_3",      "hours": 8,      "title": "Triskart per dieną",       "title_en": "Three times a day"},
    {"code": "DECENNIAL",    "hours": 87600,  "title": "Kas 10 metų",              "title_en": "Every ten years"},
    {"code": "HOURLY",       "hours": 1,      "title": "Kas valandą",              "title_en": "Every hour"},
    {"code": "IRREG",        "hours": 0,      "title": "Nevienodu periodiškumu",   "title_en": "At uneven intervals"},
    {"code": "MONTHLY",      "hours": 720,    "title": "Kas mėnesį",               "title_en": "Once a month"},
    {"code": "MONTHLY_2",    "hours": 360,    "title": "Dukart per mėnesį",        "title_en": "Twice a month"},
    {"code": "MONTHLY_3",    "hours": 240,    "title": "Triskart per mėnesį",      "title_en": "Three times a month"},
    {"code": "NEVER",        "hours": 0,      "title": "Neatnaujinamas",           "title_en": "Never updated"},
    {"code": "OP_DATPRO",    "hours": 0,      "title": "Operacinis",               "title_en": "Operational (test)"},
    {"code": "OTHER",        "hours": 0,      "title": "Neapibrėžtu periodiškumu", "title_en": "With unknown regularity"},
    {"code": "QUADRENNIAL",  "hours": 35040,  "title": "Kas 4 metai",              "title_en": "Every four years"},
    {"code": "QUARTERLY",    "hours": 2160,   "title": "Kas 3 mėnesiai",           "title_en": "Every three months"},
    {"code": "QUINQUENNIAL", "hours": 43800,  "title": "Kas 5 metai",              "title_en": "Every five years"},
    {"code": "TRIDECENNIAL", "hours": 262800, "title": "Kas 30 metų",              "title_en": "Every thirty years"},
    {"code": "TRIENNIAL",    "hours": 26280,  "title": "Kas 3 metai",              "title_en": "Every three years"},
    {"code": "TRIHOURLY",    "hours": 3,      "title": "Kas 3 valandos",           "title_en": "Every three hours"},
    {"code": "UNKNOWN",      "hours": 0,      "title": "Nežinomas",                "title_en": "Unknown interval"},
    {"code": "UPDATE_CONT",  "hours": 8760,   "title": "Nepertraukiamas",          "title_en": "Without interruption"},
    {"code": "WEEKLY",       "hours": 168,    "title": "Kas savaitę",              "title_en": "Once a week"},
    {"code": "WEEKLY_2",     "hours": 84,     "title": "Dukart per savaitę",       "title_en": "Twice a week"},
    {"code": "WEEKLY_3",     "hours": 56,     "title": "Triskart per savaitę",     "title_en": "Three times a week"},
]


def add_importance_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema = ConceptSchema.objects.get(uri=IMPORTANCE_SCHEMA_URI)

    for data in importance_concepts_data:
        concept, created = Concept.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": data["uri"],
                "valid_since": data["valid_since"],
            },
        )
        if created:
            for lang, fields in data["translations"].items():
                concept.set_current_language(lang)
                concept.label = fields["label"]
                concept.description = fields.get("description", "")
            concept.save()
        concept.concept_schemas.add(schema)


def add_type_concepts(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    schema = ConceptSchema.objects.get(uri=TYPE_SCHEMA_URI)

    for data in type_concepts_data:
        concept, created = Concept.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": data["uri"],
                "valid_since": data["valid_since"],
            },
        )
        if created:
            for lang, fields in data["translations"].items():
                concept.set_current_language(lang)
                concept.label = fields["label"]
                concept.description = fields.get("description", "")
            concept.save()
        concept.concept_schemas.add(schema)


def add_frequency_values(apps, schema_editor):
    Frequency = apps.get_model("vitrina_classifiers", "Frequency")

    for data in frequency_data:
        Frequency.objects.get_or_create(
            code=data["code"],
            defaults={
                "uri": f"{BASE_FREQUENCY_URI}/{data['code']}",
                "hours": data["hours"],
                "title": data["title"],
                "title_en": data["title_en"],
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0021_add_relationship_form_help_text_choices'),
    ]

    operations = [
        migrations.RunPython(add_importance_concepts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_type_concepts, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(add_frequency_values, reverse_code=migrations.RunPython.noop),
    ]
