# Generated by Django 4.2.29 on 2026-06-09 10:28

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0021_alter_formfieldhelptext_form_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFieldTextTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Lauko antraštė')),
                ('help_text', models.TextField(blank=True, verbose_name='Pagalbinis tekstas')),
                ('extended_help_text', models.TextField(blank=True, help_text="Išplėstinis pagalbinis tekstas bus rodomas kaip iššokantis paspaudus 'i' ikonėlę, jei forma tai palaiko", verbose_name='Išplėstinis pagalbinis tekstas')),
            ],
            options={
                'verbose_name': 'Formos lauko tekstai Translation',
                'db_table': 'vitrina_classifiers_formfieldtext_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.RenameModel(
            old_name='FormFieldHelpText',
            new_name='FormFieldText',
        ),
        migrations.AlterModelOptions(
            name='formfieldtext',
            options={'verbose_name': 'Formos lauko tekstai', 'verbose_name_plural': 'Formų laukų tekstai'},
        ),
        migrations.DeleteModel(
            name='FormFieldHelpTextTranslation',
        ),
        migrations.AddField(
            model_name='formfieldtexttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_classifiers.formfieldtext'),
        ),
        migrations.AlterUniqueTogether(
            name='formfieldtexttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
