# Generated by Django 3.2.25 on 2025-03-07 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_classifiers", "0021_auto_20250127_1347"),
        ("vitrina_classifiers", "0022_auto_20250307_0717"),
    ]

    operations = []
