kind: pipeline
type: docker
name: deploy-docker-compose

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy-with-docker-compose
    image: docker:cli
    volumes:
    - name: docker_sock
      path: /var/run/docker.sock
    privileged: true
    commands:
      - echo "Deploying application for branch ${DRONE_BRANCH}..."
      - apk add gettext
      - export BRANCH=${DRONE_BRANCH/\//-}
      - envsubst < docker-compose.template.yml > docker-compose.${DRONE_BRANCH/\//-}.yml
      - docker compose -p katalogas-${DRONE_BRANCH/\//-} -f docker-compose.${DRONE_BRANCH/\//-}.yml build
      - docker compose -p katalogas-${DRONE_BRANCH/\//-} -f docker-compose.${DRONE_BRANCH/\//-}.yml down || true
      - docker compose -p katalogas-${DRONE_BRANCH/\//-} -f docker-compose.${DRONE_BRANCH/\//-}.yml up -d
      - docker image prune -a -f
      - echo "Deployed application to https://${DRONE_BRANCH/\//-}.branch-test.data.gov.lt"
volumes:
- name: docker_sock
  host:
    path: /var/run/docker.sock
node:
  label: runner
trigger:
  ref:
    exclude:
      - refs/heads/devel

---
kind: pipeline
type: docker
name: deploy-docker-compose-dev

platform:
  os: linux
  arch: amd64

steps:
  - name: deploy-with-docker-compose
    image: docker:cli
    volumes:
    - name: docker_sock
      path: /var/run/docker.sock
    privileged: true
    commands:
      - apk add gettext
      - export BRANCH=${DRONE_BRANCH/\//-}
      - envsubst < docker-compose.dev.yml > docker-compose.yml
      - docker compose -f docker-compose.yml build --no-cache
      - docker compose -f docker-compose.yml down || true
      - docker compose -f docker-compose.yml up -d
      - sleep 30 && docker logs src-katalogas-1
      - docker image prune -a -f
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
node:
  label: runner-katalogas-dev1
trigger:
  ref:
    include:
      - refs/heads/devel
