services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=adp-dev
      - POSTGRES_USER=adp
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
    environment:
      discovery.type: 'single-node'
      network.publish_host: 0.0.0.0
      transport.tcp.port: 9200