version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - katalogas
      - spinta

networks:
  katalogas:
    external: true
  spinta:
    external: true
