services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: adp-dev
      POSTGRES_USER: adp
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    ports:
      - 127.0.0.1:9000:8080
    environment:
      ADMINER_PLUGINS: 'tables-filter'
      ADMINER_DEFAULT_SERVER: 'postgres'
