services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: adp-dev
      POSTGRES_USER: adp
      POSTGRES_PASSWORD: secret
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    ports:
      - 127.0.0.1:9000:8080
    environment:
      ADMINER_PLUGINS: 'tables-filter'
      ADMINER_DEFAULT_SERVER: 'postgres'

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'adp-dev'
      MYSQL_USER: 'adp'
      MYSQL_PASSWORD: 'secret'
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./resources/adp-dev.sql:/data/application/init.sql
    ports:
      - 0.0.0.0:3306:3306