# Should be ran on server before deployments
# docker network create katalogas
# docker compose -f docker-compose.nginx.yml up -d

services:
  katalogas-${BRANCH}:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: katalogas-${BRANCH}:latest
    command:
      - ./auto-entrypoint.sh
    environment:
      - REDIS_URL=redis://katalogas-${BRANCH}-redis:6379/
      - DATABASE_URL=postgres://admin:admin123@katalogas-${BRANCH}-database:5432/katalogas
      - SEARCH_URL=elasticsearch://katalogas-${BRANCH}-elasticsearch:9200/haystack
      - CELERY_BROKER_URL=redis://katalogas-${BRANCH}-redis:6379/3
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=vitrina.settings
      - STATIC_ROOT=/app/static
      - RUN_MODE=GUNICORN
      - ALLOWED_HOSTS=*,127.0.0.0
      - SPINTA_SERVER_URL=https://test.data.gov.lt
      - SPINTA_SERVER_NAME='Test Data Gov'
      - USE_OTP_VALIDATION=False
    networks:
      katalogas:
        aliases:
          - katalogas-${BRANCH}
    depends_on:
      - katalogas-${BRANCH}-database
      - katalogas-${BRANCH}-redis
      - katalogas-${BRANCH}-elasticsearch
    volumes:
      - /tmp/${BRANCH}-static:/app/static

  katalogas-${BRANCH}-elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      discovery.type: 'single-node'
      indices.query.bool.max_clause_count: 8192
    volumes:
      - ${BRANCH}-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - katalogas

  katalogas-${BRANCH}-database:
    image: postgres:16
    environment:
      - POSTGRES_DB=katalogas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - ${BRANCH}-postgres:/var/lib/postgresql/data
    networks:
      - katalogas

  katalogas-${BRANCH}-redis:
    image: redis:latest
    restart: always
    networks:
      - katalogas

  katalogas-${BRANCH}-nginx:
    image: nginx:latest
    volumes:
      - /tmp/${BRANCH}-static:/usr/share/nginx/html/static
    networks:
      - katalogas

  katalogas-${BRANCH}-adminer:
    image: adminer
    environment:
      ADMINER_PLUGINS: 'tables-filter'
      ADMINER_DEFAULT_SERVER: 'katalogas-${BRANCH}-database'
    depends_on:
      - katalogas-${BRANCH}-database
    networks:
      - katalogas

  katalogas-${BRANCH}-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: katalogas-${BRANCH}:latest
    command: celery -A vitrina worker -l info
    environment:
      - REDIS_URL=redis://katalogas-${BRANCH}-redis:6379/
      - DATABASE_URL=postgres://admin:admin123@katalogas-${BRANCH}-database:5432/katalogas
      - SEARCH_URL=elasticsearch://katalogas-${BRANCH}-elasticsearch:9200/haystack
      - CELERY_BROKER_URL=redis://katalogas-${BRANCH}-redis:6379/3
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=vitrina.settings
      - STATIC_ROOT=/app/static
      - RUN_MODE=GUNICORN
      - ALLOWED_HOSTS=*,127.0.0.0
      - SPINTA_SERVER_URL=https://test.data.gov.lt
      - SPINTA_SERVER_NAME='Test Data Gov'
      - USE_OTP_VALIDATION=False
    depends_on:
      - katalogas-${BRANCH}-redis
      - katalogas-${BRANCH}-database
    restart: always
    networks:
      katalogas:
        aliases:
          - katalogas-${BRANCH}

volumes:
  ${BRANCH}-postgres:
  ${BRANCH}-elasticsearch:

networks:
  katalogas:
    external: true
