services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=adp-dev
      - POSTGRES_USER=adp
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5