# Should be ran on server before deployments
# docker network create katalogas
# docker compose -f docker-compose.nginx.yml up -d

services:
  katalogas-${BRANCH}:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: katalogas-${BRANCH}:latest
    command:
      - ./auto-entrypoint.sh
    environment:
      - REDIS_URL=redis://katalogas-${BRANCH}-redis:6379/
      - DATABASE_URL=postgres://admin:admin123@katalogas-${BRANCH}-database:5432/katalogas
      - CELERY_BROKER_URL=redis://katalogas-${BRANCH}-redis:6379/3
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=vitrina.settings
      - STATIC_ROOT=/app/static
      - RUN_MODE=GUNICORN
      - ALLOWED_HOSTS=*,127.0.0.0
      - SPINTA_SERVER_URL=https://test.data.gov.lt
      - SPINTA_SERVER_NAME='Test Data Gov'
      - USE_OTP_VALIDATION=False
      - META_SITE_PROTOCOL=https
      - META_SITE_DOMAIN=${BRANCH}.branch-test.data.gov.lt
    networks:
      katalogas:
        aliases:
          - katalogas-${BRANCH}
    depends_on:
      - katalogas-${BRANCH}-database
      - katalogas-${BRANCH}-redis
    volumes:
      - /tmp/${BRANCH}-static:/app/static

  katalogas-${BRANCH}-database:
    image: postgres:18
    environment:
      - POSTGRES_DB=katalogas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      # postgres:18 changed the image default to /var/lib/postgresql/18/docker.
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ${BRANCH}-postgres:/var/lib/postgresql/data
    networks:
      - katalogas

  katalogas-${BRANCH}-redis:
    image: redis:latest
    restart: always
    networks:
      - katalogas

  katalogas-${BRANCH}-nginx:
    image: nginx:latest
    volumes:
      - /tmp/${BRANCH}-static:/usr/share/nginx/html/static
    networks:
      - katalogas

  katalogas-${BRANCH}-celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: katalogas-${BRANCH}:latest
    command: celery -A vitrina worker -l info
    environment:
      - REDIS_URL=redis://katalogas-${BRANCH}-redis:6379/
      - DATABASE_URL=postgres://admin:admin123@katalogas-${BRANCH}-database:5432/katalogas
      - CELERY_BROKER_URL=redis://katalogas-${BRANCH}-redis:6379/3
      - DEBUG=true
      - DJANGO_SETTINGS_MODULE=vitrina.settings
      - STATIC_ROOT=/app/static
      - RUN_MODE=GUNICORN
      - ALLOWED_HOSTS=*,127.0.0.0
      - SPINTA_SERVER_URL=https://test.data.gov.lt
      - SPINTA_SERVER_NAME='Test Data Gov'
      - USE_OTP_VALIDATION=False
      - META_SITE_PROTOCOL=https
      - META_SITE_DOMAIN=${BRANCH}.branch-test.data.gov.lt
    depends_on:
      - katalogas-${BRANCH}-redis
      - katalogas-${BRANCH}-database
    restart: always
    networks:
      katalogas:
        aliases:
          - katalogas-${BRANCH}

volumes:
  ${BRANCH}-postgres:

networks:
  katalogas:
    external: true
