services:
  adminer:
    image: adminer
    ports:
      - 0.0.0.0:9000:8080
    environment:
      ADMINER_DESIGN: 'pepa-linha'
      ADMINER_PLUGINS: 'tables-filter'
      ADMINER_DEFAULT_SERVER: 'mysql'
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'adp'
      MYSQL_USER: 'adp'
      MYSQL_PASSWORD: 'adp'
      MYSQL_ROOT_PASSWORD: 'adp'
    ports:
      - 3306:3306
