# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('variables', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'email_template',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GlobalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'global_email',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'newsletter_subscription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('recipient', models.TextField(blank=True, null=True, verbose_name='Gavėjas')),
                ('email_subject', models.TextField(blank=True, null=True, verbose_name='Tema')),
                ('email_content', models.TextField(blank=True, null=True, verbose_name='Turinys')),
                ('email_sent', models.BooleanField(blank=True, null=True, verbose_name='Išsiųsta')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifikatorius')),
            ],
            options={
                'db_table': 'sent_mail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sub_type', models.CharField(blank=True, choices=[('ORGANIZATION', 'Organizacijos prenumerata'), ('DATASET', 'Duomenų rinkinio prenumerata'), ('REQUEST', 'Poreikio prenumerata'), ('PROJECT', 'Projekto prenumerata'), ('COMMENT', 'Komentaro prenumerata')], max_length=255, null=True, verbose_name='Prenumeratos tipas')),
                ('email_subscribed', models.BooleanField(default=False, verbose_name='Prenumeratos laiško užsisakymas')),
                ('dataset_update_sub', models.BooleanField(default=False, verbose_name='Susijusių duomenų rinkinių prenumerata')),
                ('dataset_comments_sub', models.BooleanField(default=False, verbose_name='Duomenų rinkinių komentarų prenumerata')),
                ('request_update_sub', models.BooleanField(default=False, verbose_name='Susijusių poreikių prenumerata')),
                ('request_comments_sub', models.BooleanField(default=False, verbose_name='Poreikių komentarų prenumerata')),
                ('project_update_sub', models.BooleanField(default=False, verbose_name='Susijusių projektų prenumerata')),
                ('project_comments_sub', models.BooleanField(default=False, verbose_name='Projektų komentarų prenumerata')),
                ('comment_replies_sub', models.BooleanField(default=False, verbose_name='Komentaro atsako prenumerata')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('dataset', models.ForeignKey(blank=True, db_column='dataset', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset')),
            ],
            options={
                'db_table': 'user_dataset_subscription',
                'managed': True,
            },
        ),
    ]
