# Generated by Django 3.2.25 on 2025-06-18 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_messages", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "confirmation_token",
                    models.UUIDField(
                        blank=True, default=uuid.uuid4, null=True, unique=True
                    ),
                ),
                (
                    "confirmation_expires_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GlobalEmail",
        ),
        migrations.DeleteModel(
            name="NewsletterSubscription",
        ),
        migrations.DeleteModel(
            name="UserSubscription",
        ),
    ]
