# Generated by Django 4.2.23 on 2025-09-05 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Laukiama patvirtinimo'), ('subscribed', 'Prenumeruojama'), ('unsubscribed', 'Prenumeracija nutraukta')], default='pending', max_length=12)),
                ('confirmation_token', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('confirmation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
            options={
                'db_table': 'newsletter_subscriber',
            },
        ),
    ]
