# Generated by Django 3.2.22 on 2023-10-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0003_auto_20220928_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalemail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sentmail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='subscription',
            name='dataset_comments_sub',
            field=models.BooleanField(default=False, verbose_name='Duomenų rinkinių komentarų prenumerata'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dataset_update_sub',
            field=models.BooleanField(default=False, verbose_name='Susijusių duomenų rinkinių prenumerata'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='email_subscribed',
            field=models.BooleanField(default=False, verbose_name='Prenumeratos laiško užsisakymas'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='request_comments_sub',
            field=models.BooleanField(default=False, verbose_name='Poreikių komentarų prenumerata'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='request_update_sub',
            field=models.BooleanField(default=False, verbose_name='Susijusių poreikių prenumerata'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('REQUEST', 'Poreikio prenumerata'), ('DATASET', 'Duomenų rinkinio prenumerata'), ('ORGANIZATION', 'Organizacijos prenumerata')], max_length=255, null=True),
        ),
    ]
