# Generated by Django 3.2.22 on 2023-10-23 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0004_auto_20231016_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='globalemail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sentmail',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'managed': True},
        ),
    ]
