# Generated by Django 3.2.22 on 2023-10-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0004_auto_20231016_0946'),
        ('vitrina_messages', '0005_auto_20231013_0922'),
    ]

    operations = [
    ]
