# Generated by Django 3.2.22 on 2023-10-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0006_merge_0004_auto_20231016_0946_0005_auto_20231013_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('COMMENT', 'Komentaro prenumerata'), ('DATASET', 'Duomenų rinkinio prenumerata'), ('ORGANIZATION', 'Organizacijos prenumerata'), ('REQUEST', 'Poreikio prenumerata'), ('PROJECT', 'Projekto prenumerata')], max_length=255, null=True, verbose_name='Prenumeratos tipas'),
        ),
    ]
