# Generated by Django 3.2.22 on 2023-10-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0007_auto_20231018_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='email_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sentmail',
            name='email_sent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentmail',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('ORGANIZATION', 'Organizacijos prenumerata'), ('DATASET', 'Duomenų rinkinio prenumerata'), ('PROJECT', 'Projekto prenumerata'), ('COMMENT', 'Komentaro prenumerata'), ('REQUEST', 'Poreikio prenumerata')], max_length=255, null=True, verbose_name='Prenumeratos tipas'),
        ),
    ]
