# Generated by Django 3.2.22 on 2023-10-23 12:57

from django.db import migrations, models
import datetime


def change_existing_keys_in_template(apps, schema_editor):
    template_data = {
     "request-registered": """Sveiki, portale užregistruotas naujas poreikis duomenų rinkiniui: {0}.""",
     }
    email_templates = apps.get_model('vitrina_messages', "EmailTemplate")
    for template in template_data:
        if template in template_data.keys():
            created_template = email_templates.objects.create(
                created=datetime.datetime.now(),
                version=0,
                identifier=template,
                template=template_data[template],
                subject=template_data[template],
                title=template_data[template]
            )
            created_template.save()
        else:
            email_templates.objects.filter(identifier=template).update(template=template_data[template])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0008_auto_20231023_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='email_keys',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('COMMENT', 'Komentaro prenumerata'),
                                                        ('ORGANIZATION', 'Organizacijos prenumerata'),
                                                        ('DATASET', 'Duomenų rinkinio prenumerata'),
                                                        ('REQUEST', 'Poreikio prenumerata'),
                                                        ('PROJECT', 'Projekto prenumerata')], max_length=255, null=True,
                                                        verbose_name='Prenumeratos tipas'),
        ),
        migrations.RunPython(change_existing_keys_in_template)
    ]