# Generated by Django 3.2.22 on 2023-10-23 12:57

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0008_auto_20231023_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='email_keys',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('COMMENT', 'Komentaro prenumerata'),
                                                        ('ORGANIZATION', 'Organizacijos prenumerata'),
                                                        ('DATASET', 'Duomenų rinkinio prenumerata'),
                                                        ('REQUEST', 'Poreikio prenumerata'),
                                                        ('PROJECT', 'Projekto prenumerata')], max_length=255, null=True,
                                                        verbose_name='Prenumeratos tipas'),
        ),
    ]