# Generated by Django 3.2.22 on 2023-10-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0010_auto_20231024_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmail',
            name='email_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sentmail',
            name='recipient',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('REQUEST', 'Poreikio prenumerata'), ('COMMENT', 'Komentaro prenumerata'), ('DATASET', 'Duomenų rinkinio prenumerata'), ('ORGANIZATION', 'Organizacijos prenumerata'), ('PROJECT', 'Projekto prenumerata')], max_length=255, null=True, verbose_name='Prenumeratos tipas'),
        ),
    ]
