# Generated by Django 3.2.23 on 2024-02-19 09:05

from django.db import migrations


def update_organization_representative_subscriptions(apps, schema_editor):
    Representative = apps.get_model('vitrina_orgs', 'Representative')
    Subscription = apps.get_model("vitrina_messages", 'Subscription')
    Organization = apps.get_model("vitrina_orgs", "Organization")
    ContentType = apps.get_model('contenttypes', 'ContentType')

    org_ct = ContentType.objects.get_for_model(Organization)
    for representative in Representative.objects.filter(
        content_type=org_ct
    ):
        if sub := Subscription.objects.filter(
            user=representative.user,
            content_type=org_ct,
            object_id=representative.object_id
        ).first():
            sub.request_update_sub = True
            sub.save(update_fields=['request_update_sub'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_messages', '0011_auto_20231214_1030'),
        ('vitrina_orgs', '0024_auto_20240205_1319'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(update_organization_representative_subscriptions)
    ]
