# Generated by Django 3.2.25 on 2025-03-27 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_datasets', '0004_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yaml_file', models.FileField(upload_to='data/files/yaml_examples', verbose_name='Pridėtas YAML duomenų pavyzdys')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vitrina_datasets.dataset')),
            ],
            options={
                'db_table': 'api_example',
            },
        ),
    ]
