# Generated by Django 3.2.25 on 2025-03-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiexample',
            name='file_data',
            field=models.TextField(unique=True),
        ),
    ]
