# Generated by Django 3.2.25 on 2025-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiexample',
            name='yaml_file',
            field=models.FileField(upload_to='data/files/yaml_examples', verbose_name='Sukelti pavyzdinius duomenis YAML formatu.'),
        ),
    ]
