# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_comments', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('vitrina_orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Registruota'), ('assigned', 'Priskirta'), ('completed', 'Išspręsta')], default='created', max_length=255)),
                ('type', models.CharField(choices=[('apikey', 'Raktas'), ('dataset', 'Duomenų rinkinys'), ('comment', 'Komentaras'), ('request', 'Prašymas'), ('project', 'Project'), ('error', 'Klaida'), ('error_frequency', 'Klaida atnaujinimo dažnume'), ('error_distribution', 'Klaida duomenų rinkinio duomenų šaltinyje'), ('error_geoportal', 'Klaida importuojant duomenis iš Geoportal')], default='comment', max_length=255)),
                ('role', models.CharField(blank=True, choices=[('supervisor', 'Vyr. koordinatorius'), ('coordinator', 'Organizacijos koordinatorius'), ('manager', 'Organizacijos tvarkytojas')], max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned', models.DateTimeField(blank=True, null=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('comment_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_comments.comment')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_orgs.organization')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
