# Generated by Django 3.2.16 on 2022-11-24 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Sukurta'), ('completed', 'Atlikta')], default='created', max_length=255),
        ),
    ]
