# Generated by Django 3.2.25 on 2025-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_tasks', '0002_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('apikey', 'Raktas'), ('dataset', 'Duomenų išteklius'), ('comment', 'Komentaras'), ('request', 'Prašymas'), ('project', 'Project'), ('error', 'Klaida'), ('error_frequency', 'Klaida atnaujinimo dažnume'), ('error_distribution', 'Klaida duomenų rinkinio duomenų šaltinyje'), ('error_geoportal', 'Klaida importuojant duomenis iš Geoportal')], default='comment', max_length=255),
        ),
    ]
