# Generated by Django 3.2.16 on 2022-11-29 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_tasks', '0002_auto_20221124_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='role',
        ),
    ]
