# Generated by Django 4.2.29 on 2026-05-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_tasks', '0003_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('apikey', 'Raktas'), ('dataset', 'Duomenų išteklius'), ('comment', 'Komentaras'), ('request', 'Prašymas'), ('project', 'Project'), ('error', 'Klaida'), ('error_frequency', 'Klaida atnaujinimo dažnume'), ('error_distribution', 'Klaida duomenų rinkinio pateiktyje'), ('error_geoportal', 'Klaida importuojant duomenis iš Geoportal')], default='comment', max_length=255),
        ),
    ]
