# Generated by Django 3.2.20 on 2023-08-08 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vitrina_tasks', '0005_auto_20230629_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.CharField(blank=True, choices=[('supervisor', 'Vyr. koordinatorius'), ('coordinator', 'Organizacijos koordinatorius'), ('manager', 'Organizacijos tvarkytojas')], max_length=255, null=True),
        ),
    ]
