# Generated by Django 3.2.20 on 2023-08-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_tasks', '0010_alter_task_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('comment', 'Komentaras'), ('request', 'Prašymas'), ('error', 'Klaida')], default='comment', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.CharField(blank=True, choices=[('supervisor', 'Vyr. koordinatorius'), ('coordinator', 'Organizacijos koordinatorius'), ('manager', 'Organizacijos tvarkytojas')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Registruota'), ('assigned', 'Priskirta'), ('completed', 'Išspręsta')], default='created', max_length=255),
        ),
    ]
