# Generated by Django 3.2.15 on 2022-09-29 10:59
import re

from django.db import migrations


def update_tasks(apps, schema_editor):
    Task = apps.get_model("vitrina_tasks", "Task")
    Request = apps.get_model("vitrina_requests", "Request")
    ContentType = apps.get_model('contenttypes', 'ContentType')
    tasks_with_user_id = Task.objects.filter(content_type=ContentType.objects.get_for_model(Request))
    for task in tasks_with_user_id:
        task.user_id = None
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_tasks', '0016_auto_20230817_2238'),
        ('vitrina_requests', '0008_auto_20230906_0653'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(update_tasks),
    ]
