# Generated by Django 3.2.25 on 2024-12-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_tasks", "0017_update_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("supervisor", "Vyr. koordinatorius"),
                    ("coordinator", "Organizacijos koordinatorius"),
                    ("manager", "Organizacijos tvarkytojas"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("apikey", "Raktas"),
                    ("dataset", "Duomenų rinkinys"),
                    ("comment", "Komentaras"),
                    ("request", "Prašymas"),
                    ("project", "Project"),
                    ("error", "Klaida"),
                    ("error_frequency", "Klaida atnaujinimo dažnume"),
                    ("error_distribution", "Klaida duomenų rinkinio duomenų šaltinyje"),
                    ("error_geoportal", "Klaida importuojant duomenis iš Geoportal"),
                ],
                default="comment",
                max_length=255,
            ),
        ),
    ]
