name: "User Story"
description: "Aprašyk naują Katalogo naudotojo istoriją"
title: "User Story: [Trumpas pavadinimas]"
labels: ["web:ui"]
body:
  - type: markdown
    attributes:
      value: |
        # 🧩 User Story

        Užpildyk laukus žemiau pagal mūsų User Story struktūrą.
        Jei kai kurie skyriai netaikomi (pvz. As-Is ar User Flow), juos galima praleisti.

  - type: textarea
    id: poreikis
    attributes:
      label: "Poreikis"
      description: "Kaip <rolė>, tam, kad <tikslas>, noriu <funkcionalumas>."
      placeholder: |
        Kaip naudotojas,
        tam, kad galėčiau patogiai redaguoti duomenis naršyklėje,
        noriu matyti patogų redagavimo langą.
      render: markdown

  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > Apibrėžia naudotojo poreikį ir funkcionalumo vertę.

  - type: textarea
    id: aprasymas
    attributes:
      label: "Aprašymas"
      description: "Ką šis funkcionalumas turi daryti, kokią problemą sprendžia, ar yra priklausomybių?"
      placeholder: "Paaiškink pokyčio kontekstą ir tikslą."

  - type: textarea
    id: asis
    attributes:
      label: "Dabartinė būsena"
      description: "Kaip ši vieta veikia dabar?"
      placeholder: "Aprašyk dabartinį veikimą"

  - type: textarea
    id: tobe
    attributes:
      label: "Reikiama būsena"
      description: "Aprašyk, kaip sistema turėtų veikti po pakeitimo."
      placeholder: "Norimas elgesys, UI reakcijos, būsenos keitimas."

  - type: textarea
    id: wireframes
    attributes:
      label: "Wireframes"
      description: "Wireframe schema, geriausia iš screenshot, su atvaizduotais pakeitimais"
      placeholder: "Įkelk Wireframes (coy+paste)"

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      description: "Sąlygos, kurias įgyvendinus, istorija laikoma atlikta."
      placeholder: |
        - [ ] <UI elementas atvaizduojamas pagal dizainą>
        - [ ] <Veiksmas sukelia tinkamą reakciją>
        - [ ] <Duomenys teisingai išsaugomi>

  - type: textarea
    id: priedai
    attributes:
      label: "Priedai"
      description: "Nuorodos į API, schemas, kitas užduotis, Task tipo užduotis techniniam įgyvendinimui ar kitus dokumentus."
      placeholder: |
        - [ ] API dokumentacija
        - [ ] Dizaino nuoroda
        - [ ] Susijusi užduotis #123
        - [ ] Techninio įgyvendinimo užduotis (Task tipo) #123

  - type: textarea
    id: definition_of_done
    attributes:
      label: 📋 Definition of Done
      description: "Checklist, kuris visada turi būti pažymėtas prieš uždarant istoriją"
      value: |
        - [ ] **Testai** parašyti / atnaujinti
        - [ ] **Dokumentacija atnaujinta** (jei reikia)
        - [ ] Padeployinta ir ištestuota **Laikinojoj testinėj** aplinkoj
        - [ ] Acceptance Criteria įvykdyti
        - [ ] CHANGES.rst
        - [ ] Pademonstruota per Sprint Review
        - [ ] PO (ar atsakingas asmuo) peržiūrėjo ir patvirtino
