name: "User Story"
description: "Aprašyk naują Katalogo naudotojo istoriją"
title: "User Story: [Trumpas pavadinimas]"
labels: ["web:ui"]
body:
  - type: markdown
    attributes:
      value: |
        # 🧩 User Story

        Užpildyk laukus žemiau pagal mūsų User Story struktūrą.
        Jei kai kurie skyriai netaikomi (pvz. As-Is ar User Flow), juos galima praleisti.

  - type: textarea
    id: poreikis
    attributes:
      label: "Poreikis"
      placeholder: |
        Kaip naudotojas,
        tam, kad galėčiau patogiai redaguoti duomenis naršyklėje,
        noriu matyti patogų redagavimo langą.
      render: markdown

  - type: textarea
    id: asis
    attributes:
      label: "Dabartinė būsena"
      placeholder: "Aprašyk dabartinį veikimą"

  - type: textarea
    id: tobe
    attributes:
      label: "Siekiama būsena"
      placeholder: "Norimas elgesys, UI reakcijos."

  - type: textarea
    id: wireframes
    attributes:
      label: "Wireframes"
      placeholder: "Įkelk norimo veikimo Wireframes (pavyzdžiui, screenshotais) (coy+paste)"

  - type: textarea
    id: acceptance
    attributes:
      label: "Acceptance Criteria"
      placeholder: |
        - [ ] <UI elementas atvaizduojamas pagal dizainą>
        - [ ] <Veiksmas sukelia tinkamą reakciją>
        - [ ] <Duomenys teisingai išsaugomi>

  - type: textarea
    id: priedai
    attributes:
      label: "Priedai"
      placeholder: |
        - [ ] API dokumentacija
        - [ ] DSA Specifikacija
        - [ ] Dizaino nuoroda
        - [ ] Susijusi užduotis #123
        - [ ] Techninio įgyvendinimo užduotis (Task tipo) #123

  - type: textarea
    id: definition_of_done
    attributes:
      label: 📋 Definition of Done
      value: |
        - [ ] **Testai** parašyti / atnaujinti
        - [ ] **Dokumentacija atnaujinta** (jei reikia)
        - [ ] Padeployinta ir ištestuota **Laikinojoj testinėj** aplinkoj
        - [ ] Pokyčiai atsispindi Partnerių API, UDTS API ir RDF eksporte.
        - [ ] CHANGES.rst
