name: "VSSA testavimas"
description: "VSSA naudotojų priėmimo testavimas"
title: "<scenarijaus žingsnio nr.> - <Scenarijaus pavadinimas>"
labels: [bug, ui:web]
projects: ["atviriduomenys/DVMS (CCT)/15"]
type: Bug
body:
  - type: markdown
    attributes:
      value: |
        # UAT aptiktas trūkumas

        ## Scenarijaus žingsnio nr.: `<žingsnio numeris>`

        ## Testuota kaip: `<sistemos rolė>` - `<naudotojo vardas>`

        ## Testavimo metu pastebėti trūkumai:
        <trūkumo aprašymas (ten kur galite, prašome pridėti ekrano "screenshot")>