name: "VSSA DVMS testavimas"
description: "VSSA naudotojų priėmimo testavimas"
title: "<scenarijaus žingsnio nr.> - <Scenarijaus pavadinimas>"
labels: ["bug", "ui:web"]
projects: ["atviriduomenys/15"]
body:
  - type: textarea
    id: uat_details
    attributes:
      label: UAT aptiktas trūkumas
      description: Užpildykite šį šabloną
      value: |
        # UAT aptiktas trūkumas

        ## Scenarijaus žingsnio nr.: `<žingsnio numeris>`

        ## Testuota kaip: `<sistemos rolė>` - `<naudotojo vardas>`

        ## Testavimo metu pastebėti trūkumai:
        <trūkumo aprašymas (ten kur galite, prašome pridėti ekrano "screenshot")>
    validations:
      required: true
