# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vitrina_orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=255, null=True)),
                ('is_existing', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('periodicity', models.CharField(blank=True, max_length=255, null=True)),
                ('planned_opening_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'Pateiktas'), ('REJECTED', 'Atmestas'), ('OPENED', 'Įvykdytas'), ('ANSWERED', 'Atsakytas'), ('PLANNED', 'Suplanuotas'), ('APPROVED', 'Įvertintas')], max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('changes', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('structure_data', models.TextField(blank=True, null=True)),
                ('structure_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('organizations', models.ManyToManyField(to='vitrina_orgs.Organization')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='RequestStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('data_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('data_title', models.CharField(blank=True, max_length=255, null=True)),
                ('data_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dictionary_title', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.BigIntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'request_structure',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('external_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_requests.request')),
            ],
        ),
        migrations.CreateModel(
            name='RequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('meta', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_requests.request')),
            ],
            options={
                'db_table': 'request_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'Pateiktas'), ('REJECTED', 'Atmestas'), ('OPENED', 'Įvykdytas'), ('ANSWERED', 'Atsakytas'), ('PLANNED', 'Suplanuotas'), ('APPROVED', 'Įvertintas')], max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_orgs.organization')),
                ('request', models.ForeignKey(blank=True, db_column='request', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_requests.request')),
            ],
            options={
                'db_table': 'request_assignment',
            },
        ),
    ]
