# Generated by Django 3.2.16 on 2022-10-10 11:18

import collections

from django.db import migrations
from django.db.models import Q


def create_history_objects(apps, schema_editor):
    RequestEvent = apps.get_model('vitrina_requests', 'RequestEvent')
    Request = apps.get_model('vitrina_requests', 'Request')
    Revision = apps.get_model('reversion', 'Revision')
    Version = apps.get_model('reversion', 'Version')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    User = apps.get_model('vitrina_users', 'User')

    users = collections.defaultdict(dict)
    for user in User.objects.filter(organization_id__isnull=False):
        org = user.organization_id
        user_name = f'{user.first_name} {user.last_name}'
        users[org][user_name] = user

    events = RequestEvent.objects.exclude(
        Q(request__isnull=True) |
        Q(type='CREATED')
    )
    for event in events:
        content_type = ContentType.objects.get_for_model(Request)
        request = Request.objects.get(pk=event.request_id)
        user = users.get(request.organization_id, {}).get(event.meta)
        revision = Revision.objects.create(
            date_created=event.created,
            comment=event.type or "",
            user=user
        )
        Version.objects.create(
            object_id=event.request_id,
            content_type=content_type,
            object_repr=str(request),
            format="json",
            db="default",
            revision=revision
        )

    for request in Request.objects.all():
        content_type = ContentType.objects.get_for_model(Request)
        revision = Revision.objects.create(
            date_created=request.created,
            comment="CREATED",
            user=request.user,
        )
        Version.objects.create(
            object_id=request.id,
            content_type=content_type,
            object_repr=str(request),
            format="json",
            db="default",
            revision=revision,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0001_initial'),
        ('vitrina_orgs', '0007_auto_20220928_1451'),
        ('vitrina_users', '0004_auto_20220909_1301'),
    ]

    operations = [
        migrations.RunPython(create_history_objects)
    ]
