# Generated by Django 3.2.19 on 2023-07-05 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0003_auto_20221028_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
    ]
