# Generated by Django 4.2.23 on 2025-10-13 11:45
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('vitrina_requests', '0003_request_dataset'),
    ]
    operations = [
        migrations.CreateModel(
            name='RequestTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('_title', models.TextField(blank=True, help_text='Poreikiui suteiktas pavadinimas.', verbose_name='Pavadinimas')),
                ('_description', models.TextField(blank=True, help_text='Laisvo teksto aprašas laisvos formos tekstu.', verbose_name='Aprašymas')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_requests.request')),
            ],
            options={
                'verbose_name': 'request Translation',
                'db_table': 'request_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='requesttranslation',
            unique_together={('language_code', 'master')},
        ),
    ]