# Generated by Django 3.2.16 on 2023-05-09 05:47

from django.db import migrations
from django.core.exceptions import ObjectDoesNotExist
from vitrina.datasets.models import Dataset

def create_relation(apps, schema_editor):
    Request = apps.get_model("vitrina_requests", "Request")
    for req in Request.objects.all():
            try:
                dataset = Dataset.public.get(pk=req.dataset_id)
                req.dataset = dataset
            except ObjectDoesNotExist:
                req.dataset = None


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0003_auto_20221028_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='requestevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='requeststructure',
            options={'managed': True},
        ),
        migrations.RunPython(create_relation)
    ]
 