# Generated by Django 4.2.23 on 2025-10-13 11:46
from django.db import migrations
from django.conf import settings

def forwards_func(apps, schema_editor):
    Request = apps.get_model('vitrina_requests', 'Request')
    RequestTranslation = apps.get_model('vitrina_requests', 'RequestTranslation')

    for obj in Request.objects.all():
        RequestTranslation.objects.get_or_create(
            master_id=obj.pk,
            language_code=settings.LANGUAGE_CODE,
            defaults={
                '_title': obj.title or '',
                '_description': obj.description or '',
            }
        )

def backwards_func(apps, schema_editor):
    Request = apps.get_model('vitrina_requests', 'Request')
    RequestTranslation = apps.get_model('vitrina_requests', 'RequestTranslation')

    for obj in Request.objects.all():
        translation = RequestTranslation.objects.filter(
            master_id=obj.pk,
            language_code=settings.LANGUAGE_CODE
        ).first()

        if translation:
            obj.title = translation._title
            obj.description = translation._description
            obj.save(update_fields=['title', 'description'])

    RequestTranslation.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('vitrina_requests', '0004_add_translation_model'),
    ]
    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]