# Generated by Django 3.2.19 on 2023-07-20 13:48
from django.contrib.contenttypes.models import ContentType
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def migrate_requests(apps, schema_editor):
    Request = apps.get_model('vitrina_requests', 'Request')
    RequestObject = apps.get_model('vitrina_requests', 'RequestObject')

    for request in Request.objects.filter(Q(object_id__isnull=False) | Q(external_object_id__isnull=False)):
        RequestObject.objects.create(
            request=request,
            object_id=request.object_id,
            external_object_id=request.external_object_id,
            content_type=request.content_type,
            external_content_type=request.external_content_type
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vitrina_requests', '0005_auto_20230705_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('external_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='contenttypes.contenttype')),
                ('request',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_requests.request')),
            ],
        ),
        migrations.RunPython(migrate_requests),
        migrations.RemoveField(
            model_name='request',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='external_content_type',
        ),
        migrations.RemoveField(
            model_name='request',
            name='external_object_id',
        ),
    ]
