# Generated by Django 4.2.23 on 2025-10-13 12:03

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0005_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.RemoveField(
            model_name='request',
            name='title',
        ),
        migrations.AlterField(
            model_name='requesttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_requests.request'),
        ),
    ]
