# Generated by Django 4.2.23 on 2025-10-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0006_remove_untranslated_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requesttranslation',
            old_name='_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='requesttranslation',
            old_name='_title',
            new_name='title',
        ),
    ]
