# Generated by Django 3.2.20 on 2023-09-06 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0007_auto_20230803_0507'),
    ]

    def create_assignment_for_requests_with_org(apps, schema_editor):
        Request = apps.get_model("vitrina_requests", "Request")
        RequestAssignment = apps.get_model("vitrina_requests", "RequestAssignment")
        requests = Request.objects.all()
        for request in requests:
            if len(request.organizations.all()) > 0:
                for org in request.organizations.all():
                    reqA = RequestAssignment.objects.create(
                        organization=org,
                        request=request,
                        status=request.status
                    )
                    reqA.save()


    operations = [
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('REJECTED', 'Atmestas'), ('APPROVED', 'Patvirtintas'), ('CREATED', 'Pateiktas'), ('OPENED', 'Atvertas'), ('ANSWERED', 'Atsakytas')], max_length=255, null=True)),
                ('organization', models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vitrina_orgs.organization')),
                ('request', models.ForeignKey(blank=True, db_column='request', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vitrina_requests.request')),
            ],
        ),
        migrations.RunPython(create_assignment_for_requests_with_org),
    ]
