# Generated by Django 4.2.23 on 2025-10-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0007_rename_translated_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Pateiktas'), ('REJECTED', 'Atmestas'), ('OPENED', 'Įvykdytas'), ('ANSWERED', 'Atsakytas'), ('PLANNED', 'Suplanuotas'), ('APPROVED', 'Įvertintas'), ('IN_PROGRESS', 'Vertinamas')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='requestassignment',
            name='status',
            field=models.CharField(blank=True, choices=[('CREATED', 'Pateiktas'), ('REJECTED', 'Atmestas'), ('OPENED', 'Įvykdytas'), ('ANSWERED', 'Atsakytas'), ('PLANNED', 'Suplanuotas'), ('APPROVED', 'Įvertintas'), ('IN_PROGRESS', 'Vertinamas')], max_length=255, null=True),
        ),
    ]
