# Generated by Django 4.2.23 on 2025-11-18 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_requests", "0008_alter_request_status_alter_requestassignment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestEscalation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "escalation_level",
                    models.IntegerField(
                        choices=[(0, "Duomenų tvarkytojas"), (1, "Organizacijos koordinatorius"), (2, "Organizacija")],
                        default=0,
                    ),
                ),
                ("last_escalation_sent", models.DateTimeField()),
                ("recipients_at_current_level", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("manually_stopped", models.BooleanField(default=False)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stopped_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESPONDED", "Atsakymas gautas iš tvarkytojų/koordinatorių."),
                            ("MANUAL", "Rankiniu būdu sustabdytas administratorių."),
                            ("MAX_LEVEL", "Pasiektas maksimalus eskalacijos lygis."),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation",
                        to="vitrina_requests.request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poreikio eskalacija",
                "verbose_name_plural": "Poreikių eskalacija",
                "db_table": "request_escalation",
                "ordering": ["-created_at"],
            },
        ),
    ]
