# Generated by Django 4.2.23 on 2025-12-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0009_requestescalation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestescalation',
            name='stopped_reason',
            field=models.CharField(blank=True, choices=[('RESPONDED', 'Atsakymas gautas iš tvarkytojų/koordinatorių.'), ('MANUAL', 'Sustabdyta rankiniu būdu.'), ('MAX_LEVEL', 'Pasiektas maksimalus eskalacijos lygis.')], max_length=20),
        ),
    ]
