# Generated by Django 3.2.23 on 2024-01-26 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0010_auto_20240124_0541'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestassignment',
            table='request_assignment',
        ),
    ]
