# Generated by Django 3.2.25 on 2024-09-02 07:46

from django.db import migrations


def assign_request_organizations(apps, schema_editor):
    Request = apps.get_model('vitrina_requests', 'Request')
    RequestAssignment = apps.get_model('vitrina_requests', 'RequestAssignment')
    Dataset = apps.get_model('vitrina_datasets', 'Dataset')
    Model = apps.get_model('vitrina_structure', 'Model')
    Property = apps.get_model('vitrina_structure', 'Property')

    for request in Request.objects.all():
        if (
            not request.requestassignment_set.exists() and
            request.requestobject_set.exists()
        ):
            for obj in request.requestobject_set.all():
                organization = None

                obj_model = apps.get_model(
                    app_label=obj.content_type.app_label,
                    model_name=obj.content_type.model,
                )
                content_object = obj_model.objects.get(id=obj.object_id)

                if isinstance(content_object, Dataset):
                    organization = content_object.organization
                elif isinstance(content_object, Model):
                    organization = content_object.dataset.organization
                elif isinstance(content_object, Property):
                    organization = content_object.model.dataset.organization

                if (
                    organization and
                    not request.requestassignment_set.filter(organization=organization).exists()
                ):
                    RequestAssignment.objects.create(
                        organization=organization,
                        request=request,
                        status=request.status
                    )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_requests', '0011_auto_20240126_0852'),
        ('vitrina_datasets', '0026_auto_20240822_0849'),
        ('vitrina_structure', '0014_alter_metadata_prepare_ast'),
    ]

    operations = [
        migrations.RunPython(assign_request_organizations),
    ]
