# Generated by Django 3.2.25 on 2025-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_uapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='oauth_client_id',
            field=models.CharField(blank=True, help_text='Jei kliento identifikatorius egzistuoja - agentas gali vykdyti užklausas į katalogą.', max_length=255, verbose_name='Autorizacijos kliento identifikatorius'),
        ),
    ]
