# Generated by Django 3.2.25 on 2025-08-05 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0005_metadata_count'),
        ('vitrina_uapi', '0002_agent_oauth_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('endpoint', models.CharField(max_length=255, verbose_name='API galinis taškas')),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('DELETE', 'Delete'), ('PATCH', 'Patch')], max_length=10, verbose_name='HTTP metodas')),
                ('http_result', models.IntegerField(verbose_name='HTTP rezultatas')),
                ('result', models.CharField(choices=[('FAILED', 'Nesėkminga'), ('UPDATED', 'Atnaujinta'), ('UPDATED_WITH_CONFLICT', 'Atnaujinta su konfliktu'), ('UPDATED_WITHOUT_CHANGES', 'Atnaujinta be pakeitimų'), ('STATUS_ALIVE', 'Statusas veikia'), ('STATUS_ERROR', 'Statuso klaida')], max_length=30, verbose_name='Rezultatas')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Klaida')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesthistory', to='vitrina_uapi.agent', verbose_name='Agentas')),
            ],
            options={
                'verbose_name': 'Užklausų istorija',
                'verbose_name_plural': 'Užklausų istorijos',
            },
        ),
        migrations.CreateModel(
            name='RequestHistoryChanges',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('changed_by', models.CharField(choices=[('AGENT', 'Agentas'), ('ADMIN', 'Adminas')], max_length=255, verbose_name='Pakeitimo autorius')),
                ('change_type', models.CharField(choices=[('CREATE', 'Sukurti'), ('UPDATE', 'Atnaujinti'), ('DELETE', 'Ištrinti')], max_length=255, verbose_name='Pakeitimo tipas')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_structure.metadata', verbose_name='Elementas')),
                ('request_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='vitrina_uapi.requesthistory', verbose_name='Užklausų istorija')),
            ],
            options={
                'verbose_name': 'Užklausų istorijos pakeitimas',
                'verbose_name_plural': 'Užklausų istorijos pakeitimai',
            },
        ),
    ]
