# Generated by Django 4.2.23 on 2025-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_uapi", "0003_requesthistory_requesthistorychanges"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="agent_address",
            field=models.CharField(
                blank=True,
                help_text="Jei yra nurodytas vartų adresas, tada agento adresas yra vidinis adresas, kurį mato API vartai. Jei API vartai nenurodyti, tada yra nurodomas išorinis agento adresas",
                max_length=255,
                verbose_name="Agento adresas",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="api_gate_server_url",
            field=models.URLField(
                blank=True,
                help_text="Nurodomas API vartų serverio adresas.",
                max_length=255,
                verbose_name="API vartų serverio adresas",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="auth_server_url",
            field=models.URLField(
                blank=True,
                help_text="Nurodomas autorizacijos serverio adresas.",
                max_length=255,
                verbose_name="Autorizacijos serverio adresas",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="environment",
            field=models.CharField(
                choices=[
                    ("DEVELOPMENT", "Vystymo"),
                    ("TESTING", "Testavimo"),
                    ("PRODUCTION", "Gamybinė"),
                ],
                default="DEVELOPMENT",
                help_text="Aplinka, kurioje diegiamas agentas.",
                max_length=32,
                verbose_name="Aplinka",
            ),
        ),
    ]
