# Generated by Django 4.2.27 on 2026-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_uapi', '0004_agent_agent_address_agent_api_gate_server_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Informacija'),
        ),
    ]
