# Generated by Django 4.2.28 on 2026-03-03 15:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_uapi', '0005_requesthistory_details'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='agent',
            managers=[
                ('not_archived', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='requesthistory',
            managers=[
                ('visible', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agent_address',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='api_gate_server_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='auth_server_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_last_sync_successful',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='is_open_data_published',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='oauth_client_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='open_data_publish_url',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='service',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='synchronized_at',
        ),
        migrations.RemoveField(
            model_name='requesthistory',
            name='agent',
        ),
        migrations.CreateModel(
            name='AgentEnvironment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('synchronized_at', models.DateTimeField(blank=True, help_text='Nurodoma data, kada paskutinį kartą buvo bandyta vykdyti sinchronizaciją.', null=True, verbose_name='Paskutinės sinchronizacijos data')),
                ('is_last_sync_successful', models.BooleanField(blank=True, help_text='Nurodoma, ar paskutinė sinchronizacija įvyko sėkmingai t.y. jos metu nekilo klaidų.', null=True, verbose_name='Ar paskutinė sinchronizacija įvyko sėkmingai?')),
                ('is_open_data_published', models.BooleanField(default=False, help_text='Nurodo, ar agento aplinka papildomai publikuoja `access=open` duomenis į atvirų duomenų Saugyklą.', verbose_name='Atviri duomenys publikuojami Saugykloje')),
                ('open_data_publish_url', models.URLField(blank=True, default='https://get.data.gov.lt/', help_text='Nuoroda, kur turėtų būti publikuojami atviri duomenys.', max_length=1024, verbose_name='Atvirų duomenų publikavimo nuoroda')),
                ('oauth_client_id', models.CharField(blank=True, help_text='Jei kliento identifikatorius egzistuoja - agentas gali vykdyti užklausas į katalogą.', max_length=255, verbose_name='Autorizacijos kliento identifikatorius')),
                ('environment', models.CharField(choices=[('DEVELOPMENT', 'Vystymo'), ('TESTING', 'Testavimo'), ('PRODUCTION', 'Gamybinė')], default='DEVELOPMENT', help_text='Aplinka, kurioje diegiamas fizinis agentas.', max_length=32, verbose_name='Aplinka')),
                ('auth_server_url', models.URLField(blank=True, help_text='Nurodomas autorizacijos serverio adresas.', max_length=255, verbose_name='Autorizacijos serverio adresas')),
                ('api_gate_server_url', models.URLField(blank=True, help_text='Nurodomas API vartų serverio adresas.', max_length=255, verbose_name='API vartų serverio adresas')),
                ('agent_address', models.URLField(help_text='Jei yra nurodytas vartų adresas, tada agento adresas yra vidinis adresas, kurį mato API vartai. Jei API vartai nenurodyti, tada yra nurodomas išorinis agento adresas', max_length=255, verbose_name='Agento adresas')),
                ('is_enabled', models.BooleanField(default=False, help_text='Nurodoma, ar Agento aplinka yra įjungta ar išjungta.', verbose_name='Agento aplinka įjungta')),
                ('is_archived', models.BooleanField(default=False, help_text='Nurodo ar Agento aplinka yra archyvuota. Archyvuotos aplinkos nėra pasiekiamos įprastiems platformos vartotojams.', verbose_name='Agento aplinka archyvuota')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='vitrina_uapi.agent', verbose_name='Agentas')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('not_archived', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='agent_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesthistory', to='vitrina_uapi.agentenvironment', verbose_name='Agento aplinka'),
            preserve_default=False,
        ),
    ]
