from django.urls import path

from vitrina.datasets.views import DatasetListView
from vitrina.orgs.views import (
    OrganizationListView,
    RepresentativeCreateView,
    RepresentativeUpdateView,
    RepresentativeDeleteView,
    OrganizationManagementsView,
    OrganizationUpdateView,
    OrganizationApiKeysView,
    OrganizationApiKeysCreateView,
    OrganizationApiKeysUpdateView,
    OrganizationApiKeysDeleteView,
    OrganizationApiKeysDetailView,
    OrganizationApiKeysScopeCreateView,
    OrganizationApiKeysScopeChangeView,
    OrganizationApiKeysScopeDeleteView,
    OrganizationApiKeysScopeToggleView,
    OrganizationApiKeysRegenerateView,
    OrganizationApiKeysScopeObjectChangeView,
    OrganizationApiKeysScopeObjectDeleteView,
    OrganizationApiKeysScopeObjectToggleView,
    OrganizationApiKeysToggleView,
    AdminRemoteOrganizationSearchView,
    OrganizationContactsView,
    ContactCreateView,
    ContactUpdateView,
    ContactDeleteView,
    create_remote_organization,
    check_organization,
    OrganizationBasedAgreementListView,
    OrganizationBasedAgreementDetailView,
    OrganizationBasedAgreementApproveView,
    OrganizationBasedAgreementFormView,
    OrganizationBasedAgreementSignView,
)
from vitrina.orgs.views import (
    OrganizationDetailView,
    OrganizationMembersView,
    RepresentativeRegisterView,
    PartnerRegisterInfoView,
    PartnerRegisterView,
    OrganizationPlanView,
    OrganizationPlanCreateView,
    RepresentativeRequestApproveView,
    RepresentativeRequestDenyView,
    PartnerRegisterCompleteView,
    RepresentativeRequestDownloadView,
    RepresentativeRequestSuspendView,
)
from vitrina.orgs.views import OrganizationPlansHistoryView
from vitrina.orgs.views import OrganizationMergeView
from vitrina.orgs.views import ConfirmOrganizationMergeView
from vitrina.orgs.views import RepresentativeApiKeyView
from vitrina.orgs.views import RepresentativeExistsView
from vitrina.orgs.views import RepresentativeRequestExistsView
from vitrina.orgs.views import RepresentativeRegisterExpiredView
from vitrina.orgs.views import (
    OrganizationCreateSearchView,
    OrganizationCreateView,
    OrganizationCreateSearchUpdateView,
    OrganizationProjectsView,
    OrganizationWizardView,
    OrganizationWizardTreeView,
    OrganizationWizardCreateRedirectView,
)


urlpatterns = [
    # @RequestMapping("/organizations")
    path("organizations/", OrganizationListView.as_view(), name="organization-list"),
    path(
        "organizations/stats/jurisdiction/",
        OrganizationManagementsView.as_view(),
        name="organization-stats-jurisdiction",
    ),
    path("orgs/<int:pk>/", OrganizationDetailView.as_view(), name="organization-detail"),
    path(
        "orgs/<int:pk>/update/",
        OrganizationUpdateView.as_view(),
        name="organization-change",
    ),
    path(
        "orgs/create/search-update",
        OrganizationCreateSearchUpdateView.as_view(),
        name="organization-create-search-update",
    ),
    path(
        "orgs/create/search",
        OrganizationCreateSearchView.as_view(),
        name="organization-create-search",
    ),
    path("orgs/create/", OrganizationCreateView.as_view(), name="organization-create"),
    path(
        "orgs/<int:pk>/members/",
        OrganizationMembersView.as_view(),
        name="organization-members",
    ),
    path(
        "orgs/<int:pk>/datasets/",
        DatasetListView.as_view(),
        name="organization-datasets",
    ),
    path(
        "orgs/<int:pk>/members/add/",
        RepresentativeCreateView.as_view(),
        name="representative-create",
    ),
    path(
        "orgs/<int:pk>/members/<int:representative_id>/change/",
        RepresentativeUpdateView.as_view(),
        name="representative-update",
    ),
    path(
        "orgs/<int:organization_id>/members/<int:pk>/delete/",
        RepresentativeDeleteView.as_view(),
        name="representative-delete",
    ),
    path(
        "orgs/<int:pk>/contacts/",
        OrganizationContactsView.as_view(),
        name="organization-contacts",
    ),
    path(
        "orgs/<int:pk>/contacts/add/",
        ContactCreateView.as_view(),
        name="contact-create",
    ),
    path(
        "orgs/<int:pk>/contacts/<int:contact_id>/change/",
        ContactUpdateView.as_view(),
        name="contact-update",
    ),
    path(
        "orgs/<int:pk>/contacts/<int:contact_id>/delete/",
        ContactDeleteView.as_view(),
        name="contact-delete",
    ),
    path(
        "orgs/<int:pk>/projects/",
        OrganizationProjectsView.as_view(),
        name="organization-projects",
    ),
    path(
        "orgs/<int:pk>/agreements/",
        OrganizationBasedAgreementListView.as_view(),
        name="organization-agreement-list",
    ),
    path(
        "orgs/<int:pk>/agreements/<uuid:agreement_id>/",
        OrganizationBasedAgreementDetailView.as_view(),
        name="organization-agreement-detail",
    ),
    path(
        "orgs/<int:pk>/agreements/<uuid:agreement_id>/approve",
        OrganizationBasedAgreementApproveView.as_view(),
        name="organization-agreement-approve",
    ),
    path(
        "orgs/<int:pk>/agreements/<uuid:agreement_id>/form",
        OrganizationBasedAgreementFormView.as_view(),
        name="organization-agreement-form",
    ),
    path(
        "orgs/<int:pk>/agreements/<uuid:agreement_id>/sign",
        OrganizationBasedAgreementSignView.as_view(),
        name="organization-agreement-sign",
    ),
    path(
        "register/<token>/",
        RepresentativeRegisterView.as_view(),
        name="representative-register",
    ),
    path(
        "register/link-expired",
        RepresentativeRegisterExpiredView.as_view(),
        name="register-link-expired",
    ),
    path(
        "partner/register-info/",
        PartnerRegisterInfoView.as_view(),
        name="partner-register-info",
    ),
    path("partner/register/", PartnerRegisterView.as_view(), name="partner-register"),
    path(
        "partner/register-complete/",
        PartnerRegisterCompleteView.as_view(),
        name="partner-register-complete",
    ),
    path(
        "partner/approve/<int:pk>/",
        RepresentativeRequestApproveView.as_view(),
        name="partner-register-approve",
    ),
    path(
        "partner/deny/<int:pk>/",
        RepresentativeRequestDenyView.as_view(),
        name="partner-register-deny",
    ),
    path(
        "partner/suspend/<int:pk>/",
        RepresentativeRequestSuspendView.as_view(),
        name="partner-register-suspend",
    ),
    path(
        "partner/download/<int:pk>/",
        RepresentativeRequestDownloadView.as_view(),
        name="partner-register-download",
    ),
    path(
        "partner/representative/exists/",
        RepresentativeExistsView.as_view(),
        name="representative-exists",
    ),
    path(
        "partner/representative-request/exists/",
        RepresentativeRequestExistsView.as_view(),
        name="representative-request-exists",
    ),
    path(
        "orgs/<int:pk>/plans/",
        OrganizationPlanView.as_view(),
        name="organization-plans",
    ),
    path(
        "orgs/<int:pk>/plans/add/",
        OrganizationPlanCreateView.as_view(),
        name="organization-plans-create",
    ),
    path(
        "orgs/<int:pk>/apikeys/",
        OrganizationApiKeysView.as_view(),
        name="organization-apikeys",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/",
        OrganizationApiKeysDetailView.as_view(),
        name="organization-apikeys-detail",
    ),
    path(
        "orgs/<int:pk>/apikeys/add/",
        OrganizationApiKeysCreateView.as_view(),
        name="organization-apikeys-create",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/change/",
        OrganizationApiKeysUpdateView.as_view(),
        name="organization-apikeys-update",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/regenerate/",
        OrganizationApiKeysRegenerateView.as_view(),
        name="organization-apikeys-regenerate",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/remove/",
        OrganizationApiKeysDeleteView.as_view(),
        name="organization-apikeys-delete",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/scope/add/",
        OrganizationApiKeysScopeCreateView.as_view(),
        name="organization-apikeys-scope-create",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/<str:scope>/change/",
        OrganizationApiKeysScopeChangeView.as_view(),
        name="organization-apikeys-scope-change",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/<int:content_type_id>/<int:obj_id>/change/",
        OrganizationApiKeysScopeObjectChangeView.as_view(),
        name="organization-apikeys-scope-object-change",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/<str:scope>/delete/",
        OrganizationApiKeysScopeDeleteView.as_view(),
        name="organization-apikeys-scope-delete",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/<int:content_type_id>/<int:obj_id>/delete/",
        OrganizationApiKeysScopeObjectDeleteView.as_view(),
        name="organization-apikeys-scope-object-delete",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/<str:scope>/toggle/",
        OrganizationApiKeysScopeToggleView.as_view(),
        name="organization-apikeys-scope-toggle",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/toggle/",
        OrganizationApiKeysToggleView.as_view(),
        name="organization-apikeys-toggle",
    ),
    path(
        "orgs/<int:pk>/apikeys/<int:apikey_id>/<int:content_type_id>/<int:obj_id>/toggle/",
        OrganizationApiKeysScopeObjectToggleView.as_view(),
        name="organization-apikeys-scope-object-toggle",
    ),
    path(
        "orgs/<int:pk>/plans/history/",
        OrganizationPlansHistoryView.as_view(),
        name="organization-plans-history",
    ),
    path(
        "orgs/<int:pk>/merge/",
        OrganizationMergeView.as_view(),
        name="merge-organizations",
    ),
    path(
        "orgs/<int:organization_id>/<int:merge_organization_id>/merge/confirm/",
        ConfirmOrganizationMergeView.as_view(),
        name="confirm-organization-merge",
    ),
    path(
        "orgs/<int:pk>/members/<int:rep_id>/api/<key>",
        RepresentativeApiKeyView.as_view(),
        name="representative-api-key",
    ),
    path(
        "orgs/remote-organization-search/",
        AdminRemoteOrganizationSearchView.as_view(),
        name="organization-search",
    ),
    path(
        "orgs/remote-organization-create/",
        create_remote_organization,
        name="create-remote-organization",
    ),
    path("orgs/remote-organization-check/", check_organization, name="check-organization"),
    path("orgs/<int:pk>/wizard/", OrganizationWizardView.as_view(), name="organization-wizard"),
    path("orgs/<int:pk>/wizard/tree/", OrganizationWizardTreeView.as_view(), name="organization-wizard-tree"),
    path("orgs/<int:pk>/wizard/create/", OrganizationWizardCreateRedirectView.as_view(), name="organization-wizard-create"),
]
