# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_catalogs', '0001_initial'),
        ('vitrina_orgs', '0001_initial'),
        ('vitrina_classifiers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestingjob',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_classifiers.licence'),
        ),
    ]
