# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViispKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_content', models.TextField(help_text='Pgp key content in base64 form', verbose_name='key_content')),
            ],
            options={
                'db_table': 'viispkey',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ViispTokenKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_content', models.TextField(help_text='Pgp key content', verbose_name='key_content')),
            ],
            options={
                'db_table': 'viisptokenkey',
                'managed': True,
            },
        ),
    ]
