# Generated by Django 3.2.19 on 2023-06-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_viisp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viispkey',
            options={'managed': True},
        ),
    ]
