# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suggestion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True, verbose_name='Viešas komentaras')),
                ('type', models.CharField(choices=[('USER', 'Naudotojo komentaras'), ('REQUEST', 'Prašymo atverti duomenis komentaras'), ('PROJECT', 'Duomenų rinkinio įtraukimo į projektą komentaras'), ('STATUS', 'Statuso keitimo komentaras'), ('PLAN', 'Įtraukimo į planą komentaras'), ('STRUCTURE', 'Struktūros importavimo komentaras'), ('STRUCTURE_ERROR', 'Struktūros importavimo klaida')], default='USER', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('ANSWERED', 'Atsakytas'), ('APPROVED', 'Įvertintas'), ('CREATED', 'Pateiktas'), ('INVENTORED', 'Inventorintas'), ('OPENED', 'Atvertas'), ('OPENED', 'Įvykdytas'), ('PLANNED', 'Planuojamas atverti'), ('PLANNED', 'Suplanuotas'), ('REJECTED', 'Atmestas')], max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('rel_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('external_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_comments', to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_comments.comment')),
                ('rel_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rel_content_type_comments', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'comment',
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
    ]
