# Generated by Django 3.2.16 on 2022-10-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
