# Generated by Django 4.2.23 on 2025-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_comments', '0002_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('ANSWERED', 'Atsakytas'), ('APPROVED', 'Įvertintas'), ('CREATED', 'Pateiktas'), ('INVENTORED', 'Inventorintas'), ('IN_PROGRESS', 'Vertinamas'), ('OPENED', 'Atvertas'), ('OPENED', 'Įvykdytas'), ('PLANNED', 'Planuojamas atverti'), ('PLANNED', 'Suplanuotas'), ('REJECTED', 'Atmestas')], max_length=255, null=True),
        ),
    ]
