# Generated by Django 4.2.23 on 2025-10-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_comments', '0003_alter_comment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
