# Generated by Django 3.2.16 on 2022-10-24 08:42

from django.db import migrations, models
import django.db.models.deletion

from vitrina import settings


def create_comments_for_datasets(apps, schema_editor):
    Comment = apps.get_model('vitrina_comments', 'Comment')
    Dataset = apps.get_model('vitrina_datasets', 'Dataset')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    DatasetEvent = apps.get_model('vitrina_datasets', 'DatasetEvent')
    DatasetResource = apps.get_model('vitrina_datasets', 'DatasetResource')
    User = apps.get_model('vitrina_users', 'User')

    sys_user = User.objects.get(email=settings.SYSTEM_USER_EMAIL)
    ct = ContentType.objects.get_for_model(Dataset)

    for dataset in Dataset.objects.all():
        user = sys_user
        if DatasetEvent.objects.filter(dataset_id=dataset.pk, type="CREATED").exists():
            create_event = DatasetEvent.objects.filter(dataset_id=dataset.pk, type="CREATED").first()
            if create_event.user_0:
                user = create_event.user_0

        if dataset.published:
            Comment.objects.create(
                created=dataset.published,
                content_type=ct,
                object_id=dataset.pk,
                user=user,
                type="STATUS",
                status="INVENTORED"
            )
        if dataset.datasetstructure_set.exists():
            Comment.objects.create(
                created=dataset.datasetstructure_set.first().created,
                content_type=ct,
                object_id=dataset.pk,
                user=user,
                type="STATUS",
                status="STRUCTURED"
            )
        if DatasetResource.objects.filter(dataset_id=dataset.pk).exists():
            Comment.objects.create(
                created=DatasetResource.objects.filter(dataset_id=dataset.pk).first().created,
                content_type=ct,
                object_id=dataset.pk,
                user=user,
                type="STATUS",
                status="OPENED"
            )


def create_comments_for_requests(apps, schema_editor):
    Comment = apps.get_model('vitrina_comments', 'Comment')
    RequestEvent = apps.get_model('vitrina_requests', 'RequestEvent')
    Request = apps.get_model('vitrina_requests', 'Request')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Dataset = apps.get_model('vitrina_datasets', 'Dataset')
    User = apps.get_model('vitrina_users', 'User')

    sys_user = User.objects.get(email=settings.SYSTEM_USER_EMAIL)
    ct = ContentType.objects.get_for_model(Request)

    for event in RequestEvent.objects.all():
        if event.request.user:
            user = event.request.user
        else:
            user = sys_user

        if event.type == "APPROVED":
            Comment.objects.create(
                created=event.created,
                content_type=ct,
                object_id=event.request.pk,
                user=user,
                type="STATUS",
                status="APPROVED"
            )
        elif event.type == "REJECTED":
            Comment.objects.create(
                created=event.created,
                content_type=ct,
                object_id=event.request.pk,
                user=user,
                type="STATUS",
                status="REJECTED"
            )
        elif event.type == "STATUS_CHANGED":
            created = event.created
            if event.request.dataset_id:
                dataset = Dataset.objects.get(pk=event.request.dataset_id)
                if dataset.datasetdistribution_set.exists():
                    created = dataset.datasetdistribution_set.first().created

            Comment.objects.create(
                created=created,
                content_type=ct,
                object_id=event.request.pk,
                user=user,
                type="STATUS",
                status="OPENED"
            )


def create_comments_for_dataset_projects(apps, schema_editor):
    Comment = apps.get_model('vitrina_comments', 'Comment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Project = apps.get_model('vitrina_projects', 'Project')
    Dataset = apps.get_model('vitrina_datasets', 'Dataset')
    UsecaseDatasetIds = apps.get_model('vitrina_projects', 'UsecaseDatasetIds')
    User = apps.get_model('vitrina_users', 'User')

    sys_user = User.objects.get(email=settings.SYSTEM_USER_EMAIL)
    dataset_ct = ContentType.objects.get_for_model(Dataset)
    project_ct = ContentType.objects.get_for_model(Project)

    for usecase_dataset in UsecaseDatasetIds.objects.all():
        dataset = Dataset.objects.get(pk=usecase_dataset.dataset_ids)
        project = Project.objects.get(pk=usecase_dataset.usecase_id)
        if project.user:
            user = project.user
        else:
            user = sys_user

        Comment.objects.create(
            created=project.created,
            content_type=dataset_ct,
            object_id=dataset.pk,
            rel_content_type=project_ct,
            rel_object_id=project.pk,
            user=user,
            type="PROJECT",
        )


def create_comments_for_dataset_requests(apps, schema_editor):
    Comment = apps.get_model('vitrina_comments', 'Comment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Request = apps.get_model('vitrina_requests', 'Request')
    Dataset = apps.get_model('vitrina_datasets', 'Dataset')
    User = apps.get_model('vitrina_users', 'User')

    sys_user = User.objects.get(email=settings.SYSTEM_USER_EMAIL)
    dataset_ct = ContentType.objects.get_for_model(Dataset)
    request_ct = ContentType.objects.get_for_model(Request)

    for request in Request.objects.all():
        if request.user:
            user = request.user
        else:
            user = sys_user
        if request.dataset_id:
            Comment.objects.create(
                created=request.created,
                content_type=dataset_ct,
                object_id=request.dataset_id,
                rel_content_type=request_ct,
                rel_object_id=request.pk,
                user=user,
                type="REQUEST",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_comments', '0003_auto_20221024_1113'),
        ('vitrina_orgs', '0013_auto_20221014_0904'),
        ('vitrina_datasets', '0003_auto_20220905_0914'),
        ('vitrina_resources', '0001_initial'),
        ('vitrina_users', '0006_auto_20221027_1109'),
        ('vitrina_projects', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='vitrina_comments.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True,
                                   choices=[('INVENTORED', 'Inventorintas'), ('STRUCTURED', 'Įkelta duomenų struktūra'),
                                            ('OPENED', 'Atvertas'), ('APPROVED', 'Patvirtintas'),
                                            ('REJECTED', 'Atmestas')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('USER', 'Naudotojo komentaras'),
                                            ('REQUEST', 'Prašymo atverti duomenis komentaras'),
                                            ('PROJECT', 'Duomenų rinkinio įtraukimo į projektą komentaras'),
                                            ('STATUS', 'Statuso keitimo komentaras')], max_length=255, default='USER'),
        ),
        migrations.RunPython(create_comments_for_datasets),
        migrations.RunPython(create_comments_for_requests),
        migrations.RunPython(create_comments_for_dataset_projects),
        migrations.RunPython(create_comments_for_dataset_requests),
    ]
