# Generated by Django 4.2.29 on 2026-03-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_comments", "0004_comment_edited_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id", "type"],
                name="comment_ct_obj_type_idx",
            ),
        ),
    ]
