# Generated by Django 3.2.25 on 2025-01-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_comments', '0008_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('ANSWERED', 'Atsakytas'), ('APPROVED', 'Įvertintas'), ('CREATED', 'Pateiktas'), ('INVENTORED', 'Inventorintas'), ('OPENED', 'Atvertas'), ('OPENED', 'Įvykdytas'), ('PLANNED', 'Planuojamas atverti'), ('PLANNED', 'Suplanuotas'), ('REJECTED', 'Atmestas')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('USER', 'Naudotojo komentaras'), ('REQUEST', 'Prašymo atverti duomenis komentaras'), ('PROJECT', 'Duomenų rinkinio įtraukimo į projektą komentaras'), ('STATUS', 'Statuso keitimo komentaras'), ('PLAN', 'Įtraukimo į planą komentaras'), ('STRUCTURE', 'Struktūros importavimo komentaras'), ('STRUCTURE_ERROR', 'Struktūros importavimo klaida')], default='USER', max_length=255),
        ),
    ]
