# Generated by Django 3.2.25 on 2025-08-06 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_datasets', '0008_auto_20250714_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Schemos atstovybės pavadinimas')),
                ('uri', models.URLField(help_text='adms:schemeAgency – schemos atstovybės URI', unique=True, verbose_name='Schemos atstovybės URI')),
            ],
            options={
                'verbose_name': 'Atstovybė',
                'verbose_name_plural': 'Atstovybės',
            },
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('notation', models.CharField(help_text='skos:notation – identifikatorius išorinėje sistemoje', max_length=255, verbose_name='Žymėjimas')),
                ('identifier_type', models.CharField(choices=[('URI', 'Nuoroda'), ('LOCAL', 'Lokalus'), ('OTHER', 'Kita')], help_text='dct:type – identifikatoriaus tipas', max_length=100, verbose_name='Identifikatoriaus tipas')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='vitrina_datasets.dataset', verbose_name='Resursas')),
                ('scheme_agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='vitrina_identifiers.agency')),
            ],
            options={
                'verbose_name': 'Identifikatorius',
                'verbose_name_plural': 'Identifikatoriai',
            },
        ),
        migrations.AddConstraint(
            model_name='identifier',
            constraint=models.UniqueConstraint(fields=('resource', 'notation', 'scheme_agency'), name='unique_identifier_per_scheme_and_resource'),
        ),
    ]
