# Generated by Django 3.2.25 on 2025-08-07 12:57

from django.db import migrations, models
import django.db.models.deletion


def create_default_schema_agency(apps, schema_editor):
    Agency = apps.get_model('vitrina_identifiers', 'Agency')

    Agency.objects.get_or_create(
        code='risr',
        defaults={
            'name': 'Registrų ir valstybės informacinių sistemų registras',
            'uri': 'http://registrai.lt'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_identifiers', '0002_auto_20250811_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=100, unique=True, verbose_name='Schemos atstovybės kodas'),
        ),
        migrations.RunPython(create_default_schema_agency, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='agency',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Schemos atstovybės kodas'),
        ),
    ]
