# Generated by Django 3.2.25 on 2025-08-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_identifiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='identifier_type',
            field=models.CharField(choices=[('URI', 'Nuoroda (URI)'), ('LOCAL', 'Lokalus'), ('OTHER', 'Kita')], help_text='dct:type – identifikatoriaus tipas', max_length=100, verbose_name='Identifikatoriaus tipas'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='scheme_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='vitrina_identifiers.agency', verbose_name='Atstovybės'),
        ),
    ]
