# Generated by Django 3.2.25 on 2025-08-19 10:58

from django.db import migrations, models


def set_risr_validation_options(apps, schema_editor):
    Agency = apps.get_model('vitrina_identifiers', 'Agency')
    try:
        agency = Agency.objects.get(code="risr")
        agency.identifier_validation_type = "REGEXP"
        agency.identifier_validation_options = r"^\d{4}$"
        agency.save()
    except Agency.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_identifiers', '0002_auto_20250807_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='identifier_validation_options',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifikatoriaus tikrinimo parinktys'),
        ),
        migrations.AddField(
            model_name='agency',
            name='identifier_validation_type',
            field=models.CharField(blank=True, choices=[('REGEXP', 'Reguliarioji išraiška')], max_length=100, null=True, verbose_name='Identifikatoriaus tikrinimo tipas'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='identifier_type',
            field=models.CharField(choices=[('URI', 'Nuoroda (URI)'), ('LOCAL', 'Lokalus'), ('OTHER', 'Kita')], help_text='dct:type – identifikatoriaus tipas', max_length=100, verbose_name='Identifikatoriaus tipas'),
        ),
        migrations.RunPython(set_risr_validation_options, reverse_code=migrations.RunPython.noop),
    ]
