# Generated by Django 3.2.25 on 2025-08-25 07:01

from django.db import migrations, models


def set_risr_validation_options(apps, schema_editor):
    Agency = apps.get_model('vitrina_identifiers', 'Agency')

    Agency.objects.filter(code="risr").update(
        identifier_validation_type="REGEXP",
        identifier_validation_options=r"^\d{4}$"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_identifiers', '0003_auto_20250819_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='identifier_validation_options',
            field=models.CharField(blank=True, help_text='Tikrinimo parametrai pagal pasirinktą tipą. Reguliariajai išraiškai - įveskite regex šabloną ', max_length=255, null=True, verbose_name='Identifikatoriaus tikrinimo parinktys'),
        ),
        migrations.AddField(
            model_name='agency',
            name='identifier_validation_type',
            field=models.CharField(blank=True, choices=[('REGEXP', 'Reguliarioji išraiška')], default='REGEXP', help_text='Pasirinkite metodą, kaip tikrinti identifikatorių formatą. Reguliarioji išraiška leidžia nustatyti tikslų šabloną.', max_length=100, null=True, verbose_name='Identifikatoriaus tikrinimo tipas'),
        ),
        migrations.RunPython(set_risr_validation_options, reverse_code=migrations.RunPython.noop),
    ]
