# Generated by Django 4.2.30 on 2026-08-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_datasets', '0045_alter_dataset_is_public'),
        ('vitrina_requests', '0010_alter_requestescalation_stopped_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSearchDoc',
            fields=[
                ('text', models.TextField(blank=True, default='')),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_doc', serialize=False, to='vitrina_datasets.dataset')),
                ('title_lt', models.TextField(blank=True, default='')),
                ('title_en', models.TextField(blank=True, default='')),
                ('published_or_created', models.DateTimeField(blank=True, null=True)),
                ('type_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'search_dataset_doc',
            },
        ),
        migrations.CreateModel(
            name='RequestSearchDoc',
            fields=[
                ('text', models.TextField(blank=True, default='')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_doc', serialize=False, to='vitrina_requests.request')),
                ('title_lt', models.TextField(blank=True, default='')),
                ('title_en', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'search_request_doc',
            },
        ),
        migrations.CreateModel(
            name='RequestSearchFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_facets', to='vitrina_requests.request')),
            ],
            options={
                'db_table': 'search_request_facet',
                'indexes': [models.Index(fields=['field', 'value'], name='search_requ_field_f719d3_idx')],
                'unique_together': {('request', 'field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='DatasetSearchFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_facets', to='vitrina_datasets.dataset')),
            ],
            options={
                'db_table': 'search_dataset_facet',
                'indexes': [models.Index(fields=['field', 'value'], name='search_data_field_fcdde3_idx')],
                'unique_together': {('dataset', 'field', 'value')},
            },
        ),
    ]
