# Generated by Django 3.2.25 on 2025-03-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0003_auto_20250313_1841'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datasets',
            field=models.ManyToManyField(to='vitrina_datasets.Dataset'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
