# Generated by Django 3.2.14 on 2022-09-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
