# Generated by Django 3.2.25 on 2025-07-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0002_auto_20250313_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Kliento pavadinimas')),
                ('client_id', models.CharField(max_length=255, verbose_name='Kliento identifikatorius')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_set', to='vitrina_projects.project', verbose_name='Panaudos atvejis')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
                'db_table': 'usecase_client',
            },
        ),
        migrations.CreateModel(
            name='UseCaseClientScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('resource', models.CharField(max_length=255, verbose_name='Išteklius')),
                ('action', models.CharField(max_length=255, verbose_name='Veiksmas')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('use_case_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_projects.usecaseclient', verbose_name='Leidimai')),
            ],
            options={
                'verbose_name': 'Kliento leidimas',
                'verbose_name_plural': 'Kliento leidimai',
                'db_table': 'usecase_client_scope',
            },
        ),
    ]
