# Generated by Django 3.2.25 on 2025-07-22 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0002_auto_20250313_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseClient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Kliento pavadinimas')),
                ('client_id', models.CharField(max_length=255, verbose_name='Kliento ID')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_set', to='vitrina_projects.project', verbose_name='Panaudojimo atvejis')),
            ],
            options={
                'verbose_name': 'Klientas',
                'verbose_name_plural': 'Klientai',
                'db_table': 'usecase_client',
            },
        ),
        migrations.CreateModel(
            name='UseCaseClientScope',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('resource', models.CharField(max_length=255, verbose_name='Leidimo resursas')),
                ('action', models.CharField(max_length=255, verbose_name='Leidimo veiksmas')),
                ('scope', models.CharField(max_length=255, verbose_name='Leidimas')),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('use_case_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_projects.usecaseclient', verbose_name='Klientas')),
            ],
            options={
                'verbose_name': 'Kliento leidimas',
                'verbose_name_plural': 'Kliento leidimai',
            },
        ),
    ]
