# Generated by Django 4.2.23 on 2025-10-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0006_representative_can_write'),
        ('vitrina_projects', '0003_usecaseclient_usecaseclientscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_orgs.organization'),
        ),
    ]
