# Generated by Django 3.2.15 on 2022-09-20 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_projects', '0003_auto_20220901_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsetting',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='applicationusecase',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='applicationusecasedatasetids',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='partnerapplication',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usecasedatasetids',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usecaselike',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
