# Generated by Django 4.2.23 on 2025-10-22 15:30

from django.db import migrations, models
import django.db.models.deletion

def remove_usecaseclients(apps, schema_editor):
    UseCaseClientScope = apps.get_model("vitrina_projects", "UseCaseClientScope")
    UseCaseClient = apps.get_model("vitrina_projects", "UseCaseClient")

    UseCaseClientScope.objects.all().delete()
    UseCaseClient.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_projects", "0004_project_organization"),
    ]

    operations = [
        migrations.RunPython(remove_usecaseclients, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="usecaseclientscope",
            name="use_case_client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scopes",
                to="vitrina_projects.usecaseclient",
                verbose_name="Klientas",
            ),
        ),
    ]
