# Generated by Django 4.2.23 on 2025-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0004_project_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
