# Generated by Django 3.2.16 on 2022-11-25 10:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


def add_datasets_to_project(apps, schema_editor):
    dataset_ids = apps.get_model("vitrina_projects", "UsecaseDatasetIds")
    projects = apps.get_model("vitrina_projects", "Project")

    for project in projects.objects.all():
        items = dataset_ids.objects.filter(usecase_id=project.id)
        for item in items:
            project.datasets.add(item.dataset_ids)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_projects', '0004_auto_20221019_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='datasets',
            field=models.ManyToManyField(to='vitrina_datasets.Dataset'),
        ),
        migrations.RunPython(add_datasets_to_project),
    ]
