# Generated by Django 3.2.16 on 2022-11-25 11:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_projects', '0005_auto_20221125_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsecaseDatasetIds',
        ),
    ]
