# Generated by Django 4.2.23 on 2025-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0005_remove_and_usecaseclient_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
