# Generated by Django 3.2.16 on 2022-12-05 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vitrina_projects', '0006_delete_old_datasetid_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_project', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='image'
        ),
        migrations.RenameField(
            model_name='project',
            old_name='img',
            new_name='image',
        ),
    ]
