# Generated by Django 4.2.23 on 2025-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0006_project_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_assignee_legislations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
