# Generated by Django 4.2.26 on 2025-12-29 14:11

from django.db import migrations, models
import uuid


def fill_project_uuids(apps, schema_editor):
    Project = apps.get_model("vitrina_projects", "Project")

    projects_without_uuid = Project.objects.filter(uuid__isnull=True)
    for project in projects_without_uuid:
        project.uuid = str(uuid.uuid4())

    Project.objects.bulk_update(projects_without_uuid, ["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0007_project_other_assignee_legislations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='datasets',
            field=models.ManyToManyField(blank=True, to='vitrina_datasets.dataset'),
        ),
        migrations.RunPython(fill_project_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True),
        ),
    ]
