# Generated by Django 3.2.25 on 2025-03-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0003_auto_20250313_1841'),
        ('vitrina_structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset', verbose_name='Duomenų rinkinys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset', verbose_name='Duomenų rinkinys'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='dataset',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dataset_version', to='vitrina_datasets.dataset', verbose_name='Duomenų rinkinys'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('dataset', 'version')},
        ),
    ]
