# Generated by Django 3.2.25 on 2025-05-23 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0005_status_statustranslation_visibility_visibilitytranslation'),
        ('vitrina_structure', '0002_auto_20250313_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='eli',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ELI identifikatorius'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_classifiers.status', verbose_name='Statusas'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='visibility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_classifiers.visibility', verbose_name='Metaduomenų matomumas'),
        ),
    ]
