# Generated by Django 3.2.25 on 2025-06-03 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0003_auto_20250527_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='visibility',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Metaduomenų matomumas'),
        ),
    ]
