# Generated by Django 3.2.25 on 2025-06-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0004_alter_metadata_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Eilučių kiekis'),
        ),
    ]
