# Generated by Django 3.2.19 on 2023-07-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0005_metadata_type_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_parameterized',
            field=models.BooleanField(default=False, verbose_name='Parametrizuotas'),
        ),
    ]
