# Generated by Django 4.2.23 on 2025-10-15 10:41

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


def assign_status_based_on_draft(apps, schema_editor):
    Metadata = apps.get_model("vitrina_structure", "Metadata")
    Status = apps.get_model("vitrina_classifiers", "Status")
    status_develop, _ = Status.objects.get_or_create(codename="develop")
    status_completed, _ = Status.objects.get_or_create(codename="completed")
    metadata_rows_with_no_status = Metadata.objects.filter(Q(status__isnull=True) | Q(status__codename=None))
    for row in metadata_rows_with_no_status:
        if row.draft:
            row.status = status_develop
        else:
            row.status = status_completed
        row.save()


def populate_status_metadata_version(apps, schema_editor):
    MetadataVersion = apps.get_model("vitrina_structure", "MetadataVersion")
    Metadata = apps.get_model("vitrina_structure", "Metadata")

    for row in MetadataVersion.objects.all():
        metadata_id = row.metadata_id
        metadata_row = Metadata.objects.filter(id=metadata_id).first()
        if metadata_row:
            metadata_status = metadata_row.status
            if metadata_status:
                row.status = metadata_status
                row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_classifiers", "0015_concepts_with_distribution_status"),
        ("vitrina_structure", "0006_manifestsvalidationentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="metadataversion",
            name="status",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_classifiers.status', verbose_name='Būsena'),
        ),
        migrations.RunPython(assign_status_based_on_draft, migrations.RunPython.noop),
        migrations.RunPython(populate_status_metadata_version, migrations.RunPython.noop),
    ]
