# Generated by Django 4.2.23 on 2025-10-31 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0006_manifestsvalidationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifestvalidationentry',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=10),
        ),
    ]
