# Generated by Django 3.2.20 on 2023-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0006_auto_20230711_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManifestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kodinis pavadinimas', unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
            ],
            options={
                'verbose_name': 'Manifesto tipas',
                'verbose_name_plural': 'Manifesto tipai',
                'db_table': 'manifest_type',
            },
        ),
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name': 'Prefiksas', 'verbose_name_plural': 'Prefiksai'},
        ),
        migrations.AlterField(
            model_name='metadata',
            name='access',
            field=models.IntegerField(blank=True, choices=[(None, 'nepasirinkta'), (0, 'private'), (1, 'protected'), (2, 'public'), (3, 'open')], null=True, verbose_name='Prieiga'),
        ),
    ]
