# Generated by Django 3.2.21 on 2023-09-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0006_auto_20230711_0813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefix',
            options={'verbose_name': 'Prefiksas', 'verbose_name_plural': 'Prefiksai'},
        ),
        migrations.AddField(
            model_name='model',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='access',
            field=models.IntegerField(blank=True, choices=[(None, 'nepasirinkta'), (0, 'private'), (1, 'protected'), (2, 'public'), (3, 'open')], null=True, verbose_name='Prieiga'),
        ),
    ]
