# Generated by Django 3.2.22 on 2023-10-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0007_auto_20230919_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.TextField(blank=True, verbose_name='Pavadinimas'),
        ),
    ]
