# Generated by Django 3.2.22 on 2023-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0007_auto_20230919_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(blank=True, max_length=512, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='prepare',
            field=models.CharField(blank=True, max_length=512, verbose_name='Formulė'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='ref',
            field=models.CharField(blank=True, max_length=512, verbose_name='Ryšys'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='source',
            field=models.CharField(blank=True, max_length=512, verbose_name='Šaltinis'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(blank=True, max_length=512, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='type',
            field=models.CharField(blank=True, max_length=512, verbose_name='Tipas'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='type_args',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Tipo argumentai'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='uri',
            field=models.CharField(blank=True, max_length=512, verbose_name='Žodyno atitikmuo'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='uuid',
            field=models.CharField(max_length=512, verbose_name='Id'),
        ),
    ]
