# Generated by Django 4.2.23 on 2025-11-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0008_metadataversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='external_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Versijos numeris'),
        ),
        migrations.AddField(
            model_name='version',
            name='major',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Pagrindinis versijos numeris'),
        ),
        migrations.AddField(
            model_name='version',
            name='minor',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Mažasis versijos numeris'),
        ),
        migrations.AddField(
            model_name='version',
            name='patch',
            field=models.IntegerField(blank=True, max_length=50, null=True, verbose_name='Pataisos versijos numeris'),
        ),
        migrations.AddField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Juodraštis'), ('PRE_RELEASE', 'Išankstinis leidimas'), ('STABLE', 'Stabili'), ('DEPRECATED', 'Pasenusi'), ('WITHDRAWN', 'Atsisakyta'), ('DELETED', 'Ištrinta'), ('DESTROYED', 'Sunaikinta'), ('TESTING', 'Tikrinama'), ('DEPLOYING', 'Diegiama')], default='DRAFT', max_length=20, verbose_name='Versijos būsena'),
        ),
        migrations.AddField(
            model_name='version',
            name='version_type',
            field=models.CharField(blank=True, choices=[('MAJOR', 'Pagrindinė'), ('MINOR', 'Mažoji'), ('PATCH', 'Pataisa')], max_length=20, null=True, verbose_name='Versijos rūšis'),
        ),
    ]
