# Generated by Django 4.2.23 on 2025-10-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0009_version_external_version_version_major_version_minor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='enum',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='enumitem',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='model',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='param',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='paramitem',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='prefix',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='property',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version', verbose_name='Versija'),
        ),
    ]
