# Generated by Django 4.2.23 on 2025-11-03 09:08

from django.db import migrations


#
#
#
#
# def collect_full_version(apps, schema_editor):
#     Metadata = apps.get_model('vitrina_structure', 'Metadata')
#     MetadataVersion = apps.get_model('vitrina_structure', 'MetadataVersion')
#     Version = apps.get_model('vitrina_structure', 'Version')
#     dataset_ids = Metadata.objects.values_list('dataset_id', flat=True).distinct()
#     for dataset_id in dataset_ids:
#         version_ids = Version.objects.filter(dataset_id=dataset_id).values_list('id', flat=True).distinct().order_by('-version')
#         previous_version = None
#         for version_id in version_ids:
#             if not previous_version:
#                 metadata_rows = Metadata.objects.filter(dataset_id=dataset_id, metadata_version_id=version_id)
#                 previous_version = version_id
#             else:
#                 metadata_rows = Metadata.objects.filter(dataset_id=dataset_id, metadata_version_id__in=[version_id, previous_version])
#
#
#
#
#
class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0009_base_version_enum_version_enumitem_version_and_more'),
    ]

    operations = []
