# Generated by Django 3.2.23 on 2023-11-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0011_alter_metadata_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Pavadinimas'),
        ),
    ]
