# Generated by Django 4.2.23 on 2025-11-13 11:43

from django.db import migrations



def populate_version_field_for_models(apps, schema_editor):
    Metadata = apps.get_model("vitrina_structure", "Metadata")
    Enum = apps.get_model("vitrina_structure", "Enum")
    EnumItem = apps.get_model("vitrina_structure", "EnumItem")
    Param = apps.get_model("vitrina_structure", "Param")
    ParamItem = apps.get_model("vitrina_structure", "ParamItem")
    Base = apps.get_model("vitrina_structure", "Base")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Dataset = apps.get_model("vitrina_datasets", "Dataset")
    Comment = apps.get_model("vitrina_comments", "Comment")

    for metadata_row in Metadata.objects.filter(metadata_version__isnull=False):
        ct = ContentType.objects.filter(id=metadata_row.content_type_id).first()
        content_type_model = apps.get_model(ct.app_label, ct.model)

        if content_type_model in (Dataset, Comment):
            continue

        content_type_object = content_type_model.objects.filter(id=metadata_row.object_id).first()

        if content_type_object:
            content_type_model.objects.filter(id=content_type_object.id).update(
                metadata_version=metadata_row.metadata_version
            )

            if content_type_model == EnumItem:
                Enum.objects.filter(id=content_type_object.enum_id).update(
                    metadata_version=metadata_row.metadata_version
                )

            if content_type_model == ParamItem:
                Param.objects.filter(id=content_type_object.param_id).update(
                    metadata_version=metadata_row.metadata_version
                )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0011_create_version_for_datasets_with_no_version'),
        ('vitrina_resources', '0011_datasetdistribution_metadata_version'),
    ]

    operations = [
        migrations.RunPython(populate_version_field_for_models, migrations.RunPython.noop),
    ]
