# Generated by Django 4.2.23 on 2025-12-08 08:27

from django.db import migrations


def assign_version_number_if_missing(apps, schema_editor):
    Version = apps.get_model("vitrina_structure", "Version")

    datasets_with_no_versions = Version.objects.filter(version__isnull=True).values_list("dataset_id", flat=True)

    for dataset_id in datasets_with_no_versions:
        all_dataset_versions = Version.objects.filter(dataset_id=dataset_id).order_by("-version")
        all_dataset_versions.update(version=None)

        for version_number, version_obj in enumerate(all_dataset_versions, start=1):
            version_obj.version = version_number

        Version.objects.bulk_update(all_dataset_versions, fields=["version"])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0012_populate_version_of_new_tables'),
    ]

    operations = [
        migrations.RunPython(assign_version_number_if_missing),
    ]
