# Generated by Django 4.2.26 on 2025-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0013_version_number_assigning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Vardas'),
        ),
    ]
