# Generated by Django 3.2.23 on 2023-12-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0013_auto_20231121_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='prepare_ast',
            field=models.JSONField(blank=True, null=True, verbose_name='Formulės AST'),
        ),
    ]
