# Generated by Django 3.2.23 on 2024-03-13 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0007_auto_20230731_1331'),
        ('vitrina_structure', '0014_alter_metadata_prepare_ast'),
    ]

    operations = [
    ]
