# Generated by Django 4.2.29 on 2026-03-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_structure", "0014_auto_20260128_1307"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["content_type", "object_id"], name="metadata_ct_obj_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["content_type", "dataset", "metadata_version", "uuid"],
                name="metadata_ct_ds_mv_uuid_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["content_type", "object_id", "metadata_version"],
                name="metadata_ct_obj_mv_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="metadata",
            index=models.Index(
                fields=["content_type", "metadata_version", "name"],
                name="metadata_ct_mv_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="model",
            index=models.Index(
                fields=["dataset", "metadata_version"], name="model_dataset_mv_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["model", "given", "metadata_version"],
                name="property_model_given_mv_idx",
            ),
        ),
    ]
