# Generated by Django 3.2.25 on 2024-11-28 07:29

from django.db import migrations, models


def round_up_average_level(apps, schema_editor):
    metadata_all = apps.get_model("vitrina_structure", "Metadata")
    for metadata in metadata_all.objects.all():
        if metadata.average_level is not None:
            metadata.average_level = round(metadata.average_level)
            metadata.save()


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_structure", "0014_alter_metadata_prepare_ast"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metadata",
            name="average_level",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Apskaičiuotas brandos lygis"
            ),
        ),
        migrations.RunPython(round_up_average_level),
    ]
