# Generated by Django 4.2.26 on 2025-12-29 07:25
import uuid

from django.db import migrations

from vitrina.datasets.helpers import generate_unique_dataset_name
from vitrina.structure import VersionStatus


def create_metadata_rows_for_datasets(apps, schema_editor):
    Dataset = apps.get_model("vitrina_datasets", "Dataset")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Metadata = apps.get_model("vitrina_structure", "Metadata")
    Version = apps.get_model("vitrina_structure", "Version")
    dataset_content_type = ContentType.objects.get_for_model(Dataset)

    for dataset in Dataset.objects.all():
        draft_metadata_version = Version.objects.filter(dataset=dataset, status=VersionStatus.DRAFT).order_by("-version").first()
        if not Metadata.objects.filter(dataset=dataset, content_type=dataset_content_type).exists():
            dataset_name = generate_unique_dataset_name(dataset.organization, dataset)
            Metadata.objects.create(
                uuid=str(uuid.uuid4()),
                dataset=dataset,
                content_type=dataset_content_type,
                object_id=dataset.pk,
                name=dataset_name,
                title=dataset.title,
                description=dataset.description,
                prepare_ast={},
                version=1,
                metadata_version=draft_metadata_version,
            )


def assign_metadata_version_to_dataset_distributions(apps, schema_editor):
    Dataset = apps.get_model("vitrina_datasets", "Dataset")
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")
    Version = apps.get_model("vitrina_structure", "Version")
    for dataset in Dataset.objects.all():
        draft_metadata_version = Version.objects.filter(dataset=dataset, status=VersionStatus.DRAFT).first()
        dataset_distributions_with_no_version = DatasetDistribution.objects.filter(dataset=dataset, metadata_version__isnull=True)
        if dataset_distributions_with_no_version:
            dataset_distributions_with_no_version.update(metadata_version=draft_metadata_version)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0014_alter_metadata_name'),
    ]

    operations = [
        migrations.RunPython(create_metadata_rows_for_datasets, migrations.RunPython.noop),
        migrations.RunPython(assign_metadata_version_to_dataset_distributions, migrations.RunPython.noop),
    ]










