# Generated by Django 4.2.26 on 2026-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0014_dataset_datasetdistribution_data_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='access',
            field=models.IntegerField(blank=True, choices=[(0, 'nepasirinkta'), (1, 'private'), (2, 'protected'), (3, 'public'), (4, 'open')], null=True, verbose_name='Prieiga'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Vardas'),
        ),
        migrations.AlterField(
            model_name='metadataversion',
            name='access',
            field=models.IntegerField(blank=True, choices=[(0, 'nepasirinkta'), (1, 'private'), (2, 'protected'), (3, 'public'), (4, 'open')], null=True, verbose_name='Prieiga'),
        ),
    ]
