# Generated by Django 3.2.25 on 2025-01-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0033_auto_20250123_1308'),
        ('vitrina_structure', '0015_auto_20241128_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='metadata_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_structure.version', verbose_name='Versija'),
        ),
        migrations.AlterField(
            model_name='version',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_version', to='vitrina_datasets.dataset', verbose_name='Duomenų rinkinys'),
        ),
    ]
