# Generated by Django 4.2.29 on 2026-05-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0015_alter_datasetdistribution_status'),
        ('vitrina_structure', '0015_add_metadata_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.datasetdistribution', verbose_name='Pateiktis'),
        ),
    ]
