# Generated by Django 4.2.29 on 2026-05-14 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0016_alter_model_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='UMLDiagram',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('mermaid', models.TextField(null=True, verbose_name='UML diagrama mermaid sintaksės formatu.')),
                ('version_counter', models.IntegerField(default=0, editable=False, help_text='Incremented on every structure change to detect stale UML diagrams.')),
                ('status', models.CharField(choices=[('OUTDATED', 'Outdated'), ('PENDING', 'Pending'), ('UP_TO_DATE', 'Up to date'), ('FAILED', 'Failed')], default='OUTDATED')),
                ('error_message', models.TextField(blank=True, editable=False, null=True)),
                ('metadata_version', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='uml_diagram', to='vitrina_structure.version')),
            ],
            options={
                'verbose_name': 'UML diagrama',
                'verbose_name_plural': 'UML diagramos',
            },
        ),
    ]
