# Generated by Django 4.2.29 on 2026-05-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0018_extend_model_dependencies_with_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_structure.version', verbose_name='Versija')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_scopes', to='vitrina_structure.model')),
            ],
        ),
    ]
