# Generated by Django 3.2.25 on 2025-03-13 14:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('dataset_id', models.IntegerField()),
                ('object_count', models.IntegerField(blank=True, null=True)),
                ('field_count', models.IntegerField(blank=True, null=True)),
                ('model_count', models.IntegerField(blank=True, null=True)),
                ('distribution_count', models.IntegerField(blank=True, null=True)),
                ('request_count', models.IntegerField(blank=True, null=True)),
                ('project_count', models.IntegerField(blank=True, null=True)),
                ('maturity_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset_statistic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512, verbose_name='Nuoroda')),
                ('featured', models.BooleanField(default=False, verbose_name='Rodoma tituliniame puslapyje')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Eiliškumas')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Paveiksliukas')),
            ],
            options={
                'verbose_name': 'Statistikos nuoroda',
                'verbose_name_plural': 'Statistikos nuorodos',
                'db_table': 'stat_route',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ModelDownloadStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('model_format', models.CharField(blank=True, max_length=255, null=True)),
                ('model_requests', models.BigIntegerField(blank=True, null=True)),
                ('model_objects', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_download_statistic',
                'managed': True,
                'unique_together': {('source', 'model', 'model_format', 'created')},
            },
        ),
        migrations.CreateModel(
            name='StatRouteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.statroute')),
            ],
            options={
                'verbose_name': 'Statistikos nuoroda Translation',
                'db_table': 'stat_route_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
