# Generated by Django 3.2.19 on 2023-06-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20230602_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetstats',
            name='dataset_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='distribution_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='download_object_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='download_request_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='field_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='maturity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='model_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='object_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='project_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasetstats',
            name='request_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
