# Generated by Django 3.2.19 on 2023-06-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0004_auto_20230602_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetstats',
            name='download_object_count',
        ),
        migrations.RemoveField(
            model_name='datasetstats',
            name='download_request_count',
        ),
    ]
