# Generated by Django 3.2.20 on 2023-08-17 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('statistics', '0005_auto_20230608_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, verbose_name='Nuoroda')),
                ('featured', models.BooleanField(default=False, verbose_name='Rodoma tituliniame puslapyje')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Eiliškumas')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Paveiksliukas')),
            ],
            options={
                'verbose_name': 'Statistikos nuoroda',
                'verbose_name_plural': 'Statistikos nuorodos',
                'db_table': 'stat_route',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StatRouteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.statroute')),
            ],
            options={
                'verbose_name': 'Statistikos nuoroda Translation',
                'db_table': 'stat_route_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
