# Generated by Django 3.2.20 on 2023-08-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0006_statroute_statroutetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statroute',
            name='url',
            field=models.CharField(max_length=512, verbose_name='Nuoroda'),
        ),
    ]
