# Generated by Django 3.2.20 on 2023-08-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_alter_statroute_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeldownloadstats',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
