# Generated by Django 3.2.23 on 2023-12-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0009_alter_datasetstats_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modeldownloadstats',
            unique_together={('source', 'model', 'model_format', 'created')},
        ),
    ]
