# Generated by Django 3.2.25 on 2025-07-15 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_orgs', '0005_delete_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartContractTemplate',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('default_template', models.FileField(upload_to='data/files/smart_contract_default_templates', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md'], message='Failas turi būti Markdown formato (.md).')], verbose_name='Išmaniųjų sutarčių numatytasis šablonas')),
                ('organization', models.ForeignKey(blank=True, help_text='Nurodoma organizacija, kuriai priskirtas šablonas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization', verbose_name='Organizacija')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
