# Generated by Django 3.2.25 on 2025-07-16 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0005_delete_agent'),
        ('vitrina_projects', '0002_auto_20250313_1841'),
        ('vitrina_smart_contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Pateiktas'), ('FORMED', 'Suformuotas'), ('INITIATED', 'Inicijuota'), ('SIGNED', 'Pasirašyta'), ('ACTIVE', 'Aktyvi'), ('DEACTIVATED', 'Nutraukta')], max_length=255, null=True, verbose_name='Statusas')),
                ('agent_sync_enabled', models.BooleanField(default=False, verbose_name='Agento sinchronizacija įjungta')),
                ('last_sync_date', models.DateTimeField(blank=True, null=True, verbose_name='Paskutinė sinchronizacijos data')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_orgs.organization', verbose_name='Organizacija')),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreement_set', to='vitrina_projects.project', verbose_name='Panaudos atvejis')),
            ],
            options={
                'verbose_name': 'Sutartis',
                'verbose_name_plural': 'Sutartys',
                'db_table': 'usecase_agreement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgreementScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255, verbose_name='Leidimas')),
                ('action', models.CharField(max_length=255, verbose_name='Leidimo veiksmas')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_smart_contracts.agreement', verbose_name='Leidimai')),
            ],
            options={
                'verbose_name': 'Sutarties leidimas',
                'verbose_name_plural': 'Sutarties leidimai',
                'db_table': 'usecase_agreement_scope',
                'managed': True,
            },
        ),
    ]
