# Generated by Django 3.2.25 on 2025-07-18 11:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0002_auto_20250313_1841'),
        ('vitrina_orgs', '0005_delete_agent'),
        ('vitrina_smart_contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Pateikta'), ('FORMED', 'Suformuota'), ('INITIATED', 'Inicijuota'), ('SIGNED', 'Pasirašyta'), ('ACTIVE', 'Aktyvi'), ('TERMINATED', 'Nutraukta')], default='CREATED', max_length=255, verbose_name='Būsena')),
                ('is_agent_sync_enabled', models.BooleanField(default=False, verbose_name='Agento sinchronizacija įjungta')),
                ('last_sync_date', models.DateTimeField(blank=True, null=True, verbose_name='Paskutinės sinchronizacijos data')),
                ('assigner_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_orgs.organization', verbose_name='Duomenis teikianti organizacija')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_projects.project', verbose_name='Panaudojimo atvejis')),
            ],
            options={
                'verbose_name': 'Sutartis',
                'verbose_name_plural': 'Sutartys',
            },
        ),
        migrations.CreateModel(
            name='AgreementScope',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('resource', models.CharField(max_length=255, verbose_name='Leidimas')),
                ('action', models.CharField(max_length=255, verbose_name='Leidimo veiksmas')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_smart_contracts.agreement', verbose_name='Leidimai')),
            ],
            options={
                'verbose_name': 'Sutarties leidimas',
                'verbose_name_plural': 'Sutarties leidimai',
            },
        ),
    ]
