# Generated by Django 3.2.25 on 2025-07-21 07:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0002_agreement_agreementscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_smart_contracts.smartcontracttemplate', verbose_name='Sutarties šablonas'),
        ),
        migrations.CreateModel(
            name='AgreementFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='data/files/agreements', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'adoc'], message='Dokumentas gali būti pdf arba adoc formato.')], verbose_name='Sutarties dokumentas')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vitrina_smart_contracts.agreement', verbose_name='Sutartis')),
            ],
            options={
                'verbose_name': 'Sutarties dokumentas',
                'verbose_name_plural': 'Sutarties dokumentai',
            },
        ),
    ]
