# Generated by Django 3.2.25 on 2025-07-25 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_all_migrations(apps, schema_editor) -> None:
    Agreement = apps.get_model('vitrina_smart_contracts', 'Agreement')
    Agreement.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_orgs', '0005_delete_agent'),
        ('vitrina_projects', '0003_usecaseclient_usecaseclientscope'),
        ('vitrina_smart_contracts', '0003_agreementfile'),
    ]

    operations = [
        migrations.RunPython(delete_all_migrations, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='agreement',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_assignee', to='vitrina_orgs.organization', verbose_name='Duomenis gaunanti organizacija'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_agreements', to='vitrina_users.user', verbose_name='Sutarties iniciatorius'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='other_assignee_legislations',
            field=models.TextField(blank=True, default='', verbose_name='Papildomi gavėjo teisės aktai'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='other_assigner_legislations',
            field=models.TextField(blank=True, default='', verbose_name='Papildomi tiekėjo teisės aktai'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='payment_terms',
            field=models.TextField(blank=True, default='', verbose_name='Mokėjimo sąlygos'),
        ),
        migrations.AddField(
            model_name='agreementfile',
            name='checksum',
            field=models.CharField(blank=True, default='', editable=False, max_length=128, help_text='File content checksum.'),
        ),
        migrations.AddField(
            model_name='agreementfile',
            name='odrl',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='ODRL which have been used to generate the agreement file.'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='assigner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_assigner', to='vitrina_orgs.organization', verbose_name='Duomenis teikianti organizacija'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='vitrina_projects.project', verbose_name='Panaudojimo atvejis'),
        ),
        migrations.AlterField(
            model_name='agreementfile',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='vitrina_smart_contracts.agreement', verbose_name='Sutartis'),
        ),
        migrations.AlterField(
            model_name='agreementscope',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scopes', to='vitrina_smart_contracts.agreement', verbose_name='Leidimai'),
        ),
    ]
