# Generated by Django 3.2.25 on 2025-07-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0003_agreementfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementfile',
            name='checksum',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
