# Generated by Django 3.2.25 on 2025-07-25 12:22
from django.core.files.base import ContentFile
from django.db import migrations

default_smart_contract_template = """
### **DUOMENŲ TEIKIMO-GAVIMO SUTARTIS**

{{ odrl_data["issued"] }}, Vilnius

{{ odrl_data["assigner"][0]["ex:companyName"] }}, juridinio asmens kodas {{ odrl_data["assigner"][0]["ex:companyCode"] }}, registruotos buveinės adresas {{ odrl_data["assigner"][0]["ex:address"] }}, atstovaujama/as {{ odrl_data["assigner"][0]["ex:representative"] }}, veikiančio pagal Teikėjas įgaliojimus (toliau – **Duomenų teikėjas**)

ir

{{ odrl_data["assignee"][0]["ex:companyName"] }}, juridinio asmens kodas {{ odrl_data["assignee"][0]["ex:companyCode"] }}, registruotos buveinės adresas {{ odrl_data["assignee"][0]["ex:address"] }}, atstovaujama/as {{ odrl_data["assignee"][0]["ex:representative"] }}, veikiančio pagal Gavėjo įgaliojimus (toliau – **Duomenų gavėjas**),

toliau Duomenų teikėjas ir Duomenų gavėjas kartu vadinami Šalimis, o kiekvienas atskirai – Šalimi, sudaro šią duomenų teikimo-gavimo sutartį (toliau – Sutartis):

**1 SĄVOKOS**

1.1 Šioje Sutartyje toliau nurodytos sąvokos, parašytos iš didžiosios raidės, turi tokias reikšmes:

1.1.1 **Duomenys** – aktų, faktų ar informacijos ir tokių aktų, faktų ar informacijos rinkinių skaitmeninė išraiška, įskaitant garso, vaizdo arba garso ir vaizdo įrašus.

1.1.2 **Duomenų rinkinio pavadinimas** – {{ odrl_data["permission"][0]["target"]["ex:name"] }}.

**3 DUOMENŲ TEIKIMO IR GAVIMO TEISINIS PAGRINDAS**

3.1. Duomenų teikėjas teikia Duomenis vadovaujantis:

3.1.1. Reglamento 6 straipsnio 1 dalies c punktu

{% if odrl_data["ex:otherAssignerLegislations"] %}
3.1.2. **{{ odrl_data["ex:otherAssignerLegislations"] }}**

3.1.3. Kitais Duomenų teikėjo veiklą reglamentuojančiais Lietuvos Respublikoje galiojančiais teisės aktais.
{% else %}
3.1.2. Kitais Duomenų teikėjo veiklą reglamentuojančiais Lietuvos Respublikoje galiojančiais teisės aktais.
{% endif %}

3.2. Duomenų gavėjas gauna Duomenis vadovaujantis:

3.2.1. Reglamento 6 straipsnio 1 dalies c punktu

{% if odrl_data["ex:otherAssigneeLegislations"] %}
3.2.2. **{{ odrl_data["ex:otherAssigneeLegislations"] }}**

3.2.3. Kitais Duomenų gavėjo veiklą reglamentuojančiais Lietuvos Respublikoje galiojančiais teisės aktais.
{% else %}
3.2.2. Kitais Duomenų gavėjo veiklą reglamentuojančiais Lietuvos Respublikoje galiojančiais teisės aktais.
{% endif %}

**7 DUOMENŲ TEIKIMO SĄLYGOS**

7.1 Teisių sąrašas:

{% for clause in odrl_data["permission"][0]["target"]["ex:scopes"] %}
7.1.{{ loop.index }}. {{ clause }}
{% endfor %}

**8 KAINA, ATSISKAITYMO TVARKA**

{% if odrl_data['ex:paymentTerms'] %}
8.1 {{ odrl_data['ex:paymentTerms'] }}
{% endif %}

**9 PAPILDOMI DUOMENYS**

9.1. Sutarties šablono kontrolinė suma: template_checksum:{{ template_checksum }}

9.2. JSON formato sutarties duomenų kontrolinė suma: json_checksum:{{ json_checksum }}

| **Duomenų teikėjas**                                 | **Duomenų gavėjas**                                 |
|------------------------------------------------------|-----------------------------------------------------|
| {{ odrl_data["assigner"][0]["ex:companyName"] }}     | {{ odrl_data["assignee"][0]["ex:companyName"] }}    |
| {{ odrl_data["assigner"][0]["ex:companyCode"] }}     | {{ odrl_data["assignee"][0]["ex:companyCode"] }}    |
| {{ odrl_data["assigner"][0]["ex:address"] }}         | {{ odrl_data["assignee"][0]["ex:address"] }}        |
| {{ odrl_data["assigner"][0]["ex:email"] }}           | {{ odrl_data["assignee"][0]["ex:email"] }}          |
| {{ odrl_data["assigner"][0]["ex:phone"] }}           | {{ odrl_data["assignee"][0]["ex:phone"] }}          |
| {{ odrl_data["assigner"][0]["ex:personalCode"] }}    | {{ odrl_data["assignee"][0]["ex:personalCode"] }}   |
| {{ odrl_data["assigner"][0]["ex:representative"] }}  | {{ odrl_data["assignee"][0]["ex:representative"] }} |
| `_________________________`                          | `_________________________`                         |
| _Vardas, pavardė, parašas_                           | _Vardas, pavardė, parašas_                          |
"""

def create_initial_default_smart_contract_template(apps, schema_editor):
    SmartContractTemplate = apps.get_model('vitrina_smart_contracts', 'SmartContractTemplate')

    SmartContractTemplate.objects.create(
        default_template=ContentFile(default_smart_contract_template.encode("utf-8"), name="default_template.md")
    )

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0004_auto_20250725_1337'),
    ]

    operations = [
        migrations.RunPython(create_initial_default_smart_contract_template, reverse_code=migrations.RunPython.noop),

    ]
