# Generated by Django 3.2.25 on 2025-08-07 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0005_create_initial_default_smart_contract_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontracttemplate',
            old_name='default_template',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='agreementfile',
            name='odrl',
        ),
        migrations.AlterField(
            model_name='agreementfile',
            name='checksum',
            field=models.CharField(blank=True, default='', editable=False, help_text='Failo turinio kontrolinė suma.', max_length=128),
        ),
        migrations.AlterField(
            model_name='agreementfile',
            name='file',
            field=models.FileField(upload_to='data/files/agreements', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md', 'pdf', 'adoc', 'json'], message='Dokumentas gali būti md, pdf arba adoc formato.')], verbose_name='Sutarties dokumentas'),
        ),
    ]
