# Generated by Django 3.2.25 on 2025-07-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0005_create_initial_default_smart_contract_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartcontracttemplate',
            old_name='default_template',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='agreementfile',
            name='checksum',
            field=models.CharField(blank=True, default='', editable=False, help_text='Failo turinio kontrolinė suma.', max_length=128),
        ),
        migrations.AlterField(
            model_name='agreementfile',
            name='odrl',
            field=models.JSONField(blank=True, default=dict, editable=False, help_text='ODRL kuris buvo naudotas genertuoti sutartį.'),
        ),
    ]
