# Generated by Django 4.2.23 on 2025-10-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0006_auto_20250731_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='other_assigner_legislations',
            field=models.TextField(blank=True, default='', verbose_name='Papildomi teikėjo teisės aktai'),
        ),
    ]
