# Generated by Django 4.2.23 on 2025-11-07 13:28

from django.db import migrations


def move_other_assignee_legislations_to_project(apps, schema_editor):
    Agreement = apps.get_model("vitrina_smart_contracts", "Agreement")
    Project = apps.get_model("vitrina_projects", "Project")

    updated_projects = {}

    agreements_to_update = Agreement.objects.exclude(
        other_assignee_legislations__isnull=True,
        other_assignee_legislations=""
    )
    for agreement in agreements_to_update:
        project = agreement.project
        if not project:
            continue

        if project.id not in updated_projects:
            project.other_assignee_legislations = agreement.other_assignee_legislations
            updated_projects[project.id] = project

    if updated_projects:
        Project.objects.bulk_update(updated_projects.values(), ["other_assignee_legislations"])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0007_alter_agreement_other_assigner_legislations'),
        ('vitrina_projects', '0007_project_other_assignee_legislations')
    ]

    operations = [
        migrations.RunPython(move_other_assignee_legislations_to_project, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='agreement',
            name='other_assignee_legislations',
        ),
    ]
