# Generated by Django 4.2.23 on 2025-11-10 08:53

from django.db import migrations, models
import django.db.models.deletion


def remove_agreements(apps, schema_editor):
    Agreement = apps.get_model("vitrina_smart_contracts", "Agreement")
    AgreementFile = apps.get_model("vitrina_smart_contracts", "AgreementFile")
    AgreementScope = apps.get_model("vitrina_smart_contracts", "AgreementScope")

    AgreementScope.objects.all().delete()
    AgreementFile.objects.all().delete()
    Agreement.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('vitrina_datasets', '0031_auto_20251027_0636'),
        ('vitrina_smart_contracts', '0008_remove_agreement_other_assignee_legislations'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='assignee_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_assignee_representative', to='vitrina_datasets.contact', verbose_name='Duomenų gavėjo atstovas'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='assigner_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements_as_assigner_representative', to='vitrina_datasets.contact', verbose_name='Duomenų teikėjo atstovas'),
        ),
        migrations.RunPython(remove_agreements, reverse_code=migrations.RunPython.noop)
    ]
