# Generated by Django 4.2.23 on 2025-11-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0009_agreement_assignee_representative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='vitrina_smart_contracts.smartcontracttemplate', verbose_name='Sutarties šablonas'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Sukurta'), ('SUBMITTED', 'Pateikta'), ('APPROVED', 'Patvirtinta'), ('FORMED', 'Suformuota'), ('INITIATED', 'Inicijuota'), ('SIGNED', 'Pasirašyta'), ('ACTIVE', 'Aktyvi'), ('TERMINATED', 'Nutraukta')], default='CREATED', max_length=255, verbose_name='Būsena'),
        ),
    ]
