# Generated by Django 4.2.23 on 2025-11-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0010_agreement_template_alter_agreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='other_assigner_legislations',
            field=models.TextField(blank=True, null=True, verbose_name='Duomenų teikimo teisinis pagrindas (prievolė)'),
        ),
    ]
