# Generated by Django 4.2.26 on 2025-12-18 09:14

import django.core.validators
from django.db import migrations, models
import vitrina.storages


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_smart_contracts", "0011_alter_agreement_other_assigner_legislations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreementfile",
            name="file",
            field=models.FileField(
                storage=vitrina.storages.InternalFileSystemStorage(),
                upload_to="data/files/agreements",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["md", "pdf", "adoc", "json"],
                        message="Dokumentas gali būti md, pdf arba adoc formato.",
                    )
                ],
                verbose_name="Sutarties dokumentas",
            ),
        ),
    ]
