# Generated by Django 4.2.26 on 2025-12-29 14:59

from django.db import migrations, models


def fill_file_extensions(apps, schema_editor):
    AgreementFile = apps.get_model("vitrina_smart_contracts", "AgreementFile")

    agreement_files = AgreementFile.objects.all()
    for agreement_file in agreement_files:
        agreement_file.file_extension = agreement_file.file_name.split(".")[-1].lower()

    AgreementFile.objects.bulk_update(agreement_files, ["file_extension"])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_smart_contracts', '0012_alter_agreementfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementfile',
            name='file_extension',
            field=models.CharField(choices=[('md', 'Markdown'), ('pdf', 'PDF'), ('adoc', 'Adoc'), ('json', 'JSON')], default='notset', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(fill_file_extensions, reverse_code=migrations.RunPython.noop),
    ]
