# Generated by Django 3.2.16 on 2022-11-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={},
        ),
    ]
