# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_api', '0001_initial'),
        ('vitrina_datasets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiscope',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset', verbose_name='Duomenų rinkinys'),
        ),
        migrations.AddField(
            model_name='apiscope',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_api.apikey', verbose_name='API raktas'),
        ),
    ]
