# Generated by Django 3.2.25 on 2025-03-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_projects', '0001_initial'),
        ('vitrina_orgs', '0002_initial'),
        ('vitrina_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apidescription',
            options={},
        ),
        migrations.AddField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_projects.project'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.representative'),
        ),
        migrations.AddField(
            model_name='apiscope',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization', verbose_name='Organizacija'),
        ),
    ]
