# Generated by Django 3.2.25 on 2025-03-14 12:07

from django.db import migrations

from vitrina.settings import SITE_ID


def create_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')

    Site.objects.get_or_create(
        pk=SITE_ID,
        defaults={
            'domain': 'localhost',
            'name': 'localhost',
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
        ('vitrina_api', '0003_auto_20250313_1841'),
    ]

    operations = [
        migrations.RunPython(create_default_site, reverse_code=migrations.RunPython.noop),
    ]
