# Generated by Django 3.2.25 on 2025-03-14 12:07

from django.db import migrations

from vitrina.settings import SITE_ID


def create_redirects(apps, schema_editor):
    Redirect = apps.get_model('redirects', 'Redirect')
    redirects = [
        ('/page/regulation/', '/more/regulation/'),
        ('/page/nuorodos/', '/more/nuorodos/'),
        ('/page/savokos/', '/more/savokos/'),
        ('/page/apie/', '/more/apie/'),
        ('/page/contacts/', '/more/contacts/'),
        ('/other/', '/more/other/'),
        ('/reports/', '/more/reports/'),
        ('/page/templates/', '/more/templates/'),
        ('/page/saugykla/', '/opening-tips/saugykla/'),
        ('/page/vadovas/', '/opening-tips/vadovas/'),
        ('/page/aprasas/', '/opening-tips/aprasas/'),
        ('/page/data-opening-tools/', '/opening-tips/data-opening-tools/'),
        ('/opening/learningmaterial/', '/opening-tips/opening/learningmaterial/'),
        ('/page/opening_faq/', '/opening-tips/opening_faq/'),
        ('/usecases/examples/', '/projects/'),
        ('/usecases/applications/', '/projects/'),
        ('/usecase/', '/projects/add/'),
        ('/dataset/', '/datasets/'),
    ]

    for old_path, new_path in redirects:
        redirect = Redirect.objects.create(site_id=SITE_ID, old_path=old_path, new_path=new_path)
        redirect.save()

class Migration(migrations.Migration):

    dependencies = [
        ("redirects", "0001_initial"),
        ('vitrina_api', '0004_create_default_site'),
    ]

    operations = [
        migrations.RunPython(create_redirects, reverse_code=migrations.RunPython.noop),
    ]
