# Generated by Django 3.2.25 on 2025-06-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0003_auto_20250611_1020'),
        ('vitrina_api', '0005_create_redirects'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.agent'),
        ),
    ]
