# Generated by Django 3.2.25 on 2025-06-12 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_api', '0006_apikey_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='agent',
        ),
    ]
