# Generated by Django 3.2.22 on 2023-11-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0022_auto_20231110_1704'),
        ('vitrina_orgs', '0021_auto_20231110_1011'),
        ('vitrina_api', '0006_auto_20231012_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization'),
        ),
        migrations.CreateModel(
            name='ApiScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=255, verbose_name='Taikymo sritis')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset', verbose_name='API raktas')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_api.apikey', verbose_name='API raktas')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization', verbose_name='Organizacija')),
            ],
            options={
                'db_table': 'api_scope',
            },
        ),
    ]
