# Generated by Django 3.2.25 on 2025-06-12 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_uapi', '0001_initial'),
        ('vitrina_api', '0007_remove_apikey_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_uapi.agent'),
        ),
    ]
