# Generated by Django 3.2.23 on 2024-01-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_api', '0010_apikey_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiscope',
            name='enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
