# Generated by Django 3.2.25 on 2025-03-13 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filer', '0017_image__transparent'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CmsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('file_data', models.TextField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cms_attachment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CmsMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'cms_menu_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CmsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('page_order', models.IntegerField(blank=True, null=True)),
                ('published', models.BooleanField()),
                ('slug', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=255, null=True)),
                ('list_children', models.BooleanField()),
            ],
            options={
                'db_table': 'adp_cms_page',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CssRuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('active', models.BooleanField(blank=True, null=True)),
                ('css_order', models.IntegerField(blank=True, null=True)),
                ('css_override', models.TextField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'css_rule_override',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Atsakymas')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Klausimas')),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dažnai užduodamas klausimas',
                'verbose_name_plural': 'Dažnai užduodami klausimai',
                'db_table': 'faq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('author', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('author_name', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(blank=True, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('imageuuid', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'news_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('imageuuid', models.CharField(blank=True, max_length=36, null=True)),
                ('published', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'terms_of_use',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Diegimo darbų pradžia')),
                ('end_date', models.DateTimeField(verbose_name='Diegimo darbų pabaiga')),
                ('message_lt', models.TextField(verbose_name='Pranešimas (lietuvių kalba)')),
                ('message_en', models.TextField(blank=True, null=True, verbose_name='Pranešimas (anglų kalba)')),
            ],
            options={
                'db_table': 'deployment',
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('learning_material_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pavadinimas')),
                ('video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vaizdo įrašo nuoroda')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Santrauka')),
                ('author_name', models.TextField(blank=True, null=True, verbose_name='Autorius')),
                ('published', models.DateField(blank=True, null=True, verbose_name='Publikavimo data')),
                ('uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('requested', models.IntegerField(blank=True, null=True)),
                ('imageuuid', models.CharField(blank=True, max_length=36, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_learning_material', to=settings.FILER_IMAGE_MODEL, verbose_name='Paveikslėlis')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mokymosi medžiaga',
                'verbose_name_plural': 'Mokymosi medžiaga',
                'db_table': 'learning_material',
            },
        ),
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=36, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_files', to='contenttypes.contenttype')),
                ('file', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_object', to='filer.file')),
            ],
            options={
                'db_table': 'file_resource',
            },
        ),
        migrations.CreateModel(
            name='ExternalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('title', models.TextField(blank=True, null=True, verbose_name='Pavadinimas')),
                ('type', models.CharField(blank=True, choices=[('EU_COMISSION_PORTAL', 'Europos komisijos portalai'), ('EU_LAND', 'EU šalys'), ('OTHER_LAND', 'Kitos šalys')], max_length=255, null=True, verbose_name='Tipas')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuoroda')),
                ('imageuuid', models.CharField(blank=True, max_length=36, null=True)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_site', to=settings.FILER_IMAGE_MODEL, verbose_name='Paveikslėlis')),
            ],
            options={
                'verbose_name': 'Portalas',
                'verbose_name_plural': 'Portalai',
                'db_table': 'external_site',
            },
        ),
    ]
