# Generated by Django 3.2.16 on 2022-11-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='externalsite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fileresource',
            options={},
        ),
    ]
