# Generated by Django 3.2.25 on 2025-03-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vitrina_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsattachment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cmsmenuitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cmspage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cssruleoverride',
            options={},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Dažnai užduodamas klausimas', 'verbose_name_plural': 'Dažnai užduodami klausimai'},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='termsofuse',
            options={},
        ),
        migrations.AddField(
            model_name='cmsattachment',
            name='cms_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_cms.cmspage'),
        ),
        migrations.AddField(
            model_name='cmspage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_cms.cmspage'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_news_item', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
