# Generated by Django 3.2.25 on 2025-07-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0002_auto_20250313_1841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={'verbose_name': 'Diegimo pranešimas', 'verbose_name_plural': 'Diegimo pranešimai'},
        ),
    ]
