# Generated by Django 3.2.16 on 2022-11-14 06:42

from django.db import migrations, models


def fix_learning_material_image_field(apps, editor_schema):
    LearningMaterial = apps.get_model('vitrina_cms', 'LearningMaterial')
    for material in LearningMaterial.objects.filter(imageuuid__isnull=False):
        material.imageuuid = f"image/{material.imageuuid}.png"
        material.save(update_fields=['imageuuid'])


def fix_external_site_image_field(apps, editor_schema):
    ExternalSite = apps.get_model('vitrina_cms', 'ExternalSite')
    for site in ExternalSite.objects.filter(imageuuid__isnull=False):
        site.imageuuid = f"image/{site.imageuuid}.png"
        site.save(update_fields=['imageuuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0002_alter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='imageuuid',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='externalsite',
            name='imageuuid',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='image/'),
        ),
        migrations.RunPython(fix_learning_material_image_field),
        migrations.RunPython(fix_external_site_image_field),
        migrations.RenameField(
            model_name='learningmaterial',
            old_name='imageuuid',
            new_name='image'
        ),
        migrations.RenameField(
            model_name='externalsite',
            old_name='imageuuid',
            new_name='image'
        ),
    ]
