# Generated by Django 3.2.16 on 2022-12-05 09:39

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


def get_model(apps, obj_class):
    model = None
    Project = apps.get_model('vitrina_projects', 'Project')
    Organization = apps.get_model('vitrina_orgs', 'Organization')
    ExternalSite = apps.get_model('vitrina_cms', 'ExternalSite')
    LearningMaterial = apps.get_model('vitrina_cms', 'LearningMaterial')
    NewsItem = apps.get_model('vitrina_cms', 'NewsItem')

    if obj_class.endswith("Usecase"):
        model = Project
    elif obj_class.endswith("ExternalSite"):
        model = ExternalSite
    elif obj_class.endswith("Organization"):
        model = Organization
    elif obj_class.endswith("LearningMaterial"):
        model = LearningMaterial
    elif obj_class.endswith("NewsItem"):
        model = NewsItem
    return model


def migrate_content_objects(apps, schema_editor):
    FileResource = apps.get_model('vitrina_cms', 'FileResource')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    for file in FileResource.objects.all():
        model = get_model(apps, file.obj_class)
        content_type = ContentType.objects.get_for_model(model)
        file.content_type = content_type
        file.object_id = file.obj_id
        file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('vitrina_cms', '0003_auto_20221205_1110'),
        ('vitrina_orgs', '0001_initial'),
        ('vitrina_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileresource',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type_files', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_object', to='filer.file'),
        ),
        migrations.AddField(
            model_name='fileresource',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_content_objects),
        migrations.RemoveField(
            model_name='fileresource',
            name='obj_class',
        ),
        migrations.RemoveField(
            model_name='fileresource',
            name='obj_id',
        ),
    ]
