# Generated by Django 3.2.16 on 2022-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0003_alter_imageuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalsite',
            name='type',
            field=models.CharField(blank=True, choices=[('EU_COMISSION_PORTAL', 'Europos komisijos portalai'), ('EU_LAND', 'EU šalys'), ('OTHER_LAND', 'Kitos šalys')], max_length=255, null=True),
        ),
    ]
