# Generated by Django 3.2.25 on 2025-06-09 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0003_alter_deployment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='learning-material-files/')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('learning_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='vitrina_cms.learningmaterial')),
            ],
        ),
    ]
