# Generated by Django 3.2.16 on 2022-11-16 12:54

from django.db import migrations, models


def fix_file_resource_file_field(apps, editor_schema):
    FileResource = apps.get_model('vitrina_cms', 'FileResource')
    for resource in FileResource.objects.all():
        resource.filename = f"file/{resource.filename}"
        resource.save(update_fields=['filename'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0004_alter_externalsite_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileresource',
            name='filename',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='file/'),
        ),
        migrations.RunPython(fix_file_resource_file_field),
        migrations.RenameField(
            model_name='fileresource',
            old_name='filename',
            new_name='file'
        )
    ]
