# Generated by Django 3.2.25 on 2024-06-27 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vitrina_cms', '0004_auto_20221205_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Diegimo darbų pradžia')),
                ('end_date', models.DateTimeField(verbose_name='Diegimo darbų pabaiga')),
                ('message_lt', models.TextField(verbose_name='Pranešimas (lietuvių kalba)')),
                ('message_en', models.TextField(blank=True, null=True, verbose_name='Pranešimas (anglų kalba)')),
            ],
            options={
                'db_table': 'deployment',
            },
        ),
        migrations.AlterModelOptions(
            name='externalsite',
            options={'verbose_name': 'Portalas', 'verbose_name_plural': 'Portalai'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'managed': False, 'verbose_name': 'Dažnai užduodamas klausimas', 'verbose_name_plural': 'Dažnai užduodami klausimai'},
        ),
        migrations.AlterModelOptions(
            name='learningmaterial',
            options={'verbose_name': 'Mokymosi medžiaga', 'verbose_name_plural': 'Mokymosi medžiaga'},
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='externalsite',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_site', to=settings.FILER_IMAGE_MODEL, verbose_name='Paveikslėlis'),
        ),
        migrations.AlterField(
            model_name='externalsite',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='externalsite',
            name='type',
            field=models.CharField(blank=True, choices=[('EU_COMISSION_PORTAL', 'Europos komisijos portalai'), ('EU_LAND', 'EU šalys'), ('OTHER_LAND', 'Kitos šalys')], max_length=255, null=True, verbose_name='Tipas'),
        ),
        migrations.AlterField(
            model_name='externalsite',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuoroda'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='author_name',
            field=models.TextField(blank=True, null=True, verbose_name='Autorius'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_learning_material', to=settings.FILER_IMAGE_MODEL, verbose_name='Paveikslėlis'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Publikavimo data'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Santrauka'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='topic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pavadinimas'),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Vaizdo įrašo nuoroda'),
        ),
    ]
