# Generated by Django 4.2.24 on 2025-09-23 12:33
from django.db import migrations


def create_groups_with_permissions(groups_permissions, app_label, apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    for group_name, permission_codenames in groups_permissions.items():
        group, created = Group.objects.get_or_create(name=group_name)
        if not created:
            continue
        for codename in permission_codenames:
            try:
                permission = Permission.objects.get(
                    codename=codename,
                    content_type__app_label=app_label
                )
                group.permissions.add(permission)
            except Permission.DoesNotExist:
                # Skip for tests
                continue

def create_learning_material_groups(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')

    # Get all permissions for `LearningMaterial` model.
    learning_permissions = Permission.objects.filter(
        content_type__app_label='vitrina_cms',
        content_type__model='learningmaterial'
    ).values_list('codename', flat=True)

    learning_groups = {
        'Learning Material Viewers': ['view_learningmaterial'],
        'Learning Material Administrators': list(learning_permissions),
    }
    create_groups_with_permissions(learning_groups, 'vitrina_cms', apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0004_learningmaterialfile'),
    ]

    operations = [
        migrations.RunPython(create_learning_material_groups, migrations.RunPython.noop),
    ]
