# Generated by Django 4.2.29 on 2026-05-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0042_merge_20260526_2010"),
        ("vitrina_cms", "0005_create_viewer_and_admin_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulmaColumn",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Auto"),
                            ("is-1", "1/12"),
                            ("is-2", "2/12"),
                            ("is-3", "3/12 (ketvirtadalis)"),
                            ("is-4", "4/12 (trečdalis)"),
                            ("is-5", "5/12"),
                            ("is-6", "6/12 (pusė)"),
                            ("is-7", "7/12"),
                            ("is-8", "8/12 (du trečdaliai)"),
                            ("is-9", "9/12"),
                            ("is-10", "10/12"),
                            ("is-11", "11/12"),
                            ("is-12", "12/12 (visa)"),
                        ],
                        max_length=10,
                        verbose_name="Plotis",
                    ),
                ),
                (
                    "extra_classes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Papildomos klasės"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stulpelis (Bulma column)",
            },
            bases=("cms.cmsplugin",),
        ),
        migrations.CreateModel(
            name="BulmaRow",
            fields=[
                (
                    "cmsplugin_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="%(app_label)s_%(class)s",
                        serialize=False,
                        to="cms.cmsplugin",
                    ),
                ),
                (
                    "extra_classes",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Papildomos klasės"
                    ),
                ),
            ],
            options={
                "verbose_name": "Eilutė (Bulma columns)",
            },
            bases=("cms.cmsplugin",),
        ),
    ]
