# Generated by Django 4.2.30 on 2026-07-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0005_create_viewer_and_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Publikuoti'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='level',
            field=models.CharField(choices=[('info', 'Informacinis'), ('warning', 'Įspėjamasis'), ('critical', 'Kritinis')], default='info', max_length=20, verbose_name='Pranešimo tipas'),
        ),
    ]
