# Generated by Django 4.2.30 on 2026-10-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_cms', '0006_deployment_is_published_deployment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmaterial',
            name='requested',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
