# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('financed_datasets', models.IntegerField(blank=True, null=True)),
                ('financing_plan_state_id', models.BigIntegerField(blank=True, null=True)),
                ('projected_cost', models.IntegerField(blank=True, null=True)),
                ('projected_datasets', models.IntegerField(blank=True, null=True)),
                ('received_financing', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financing_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinancingPlanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('financing_plan_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financing_plan_state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NationalFinancingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(blank=True, null=True)),
                ('confirmed_budget', models.BigIntegerField(blank=True, null=True)),
                ('confirmed_by', models.BigIntegerField(blank=True, null=True)),
                ('estimated_budget', models.BigIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True, unique=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'national_financing_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Sukurta')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Įgyvendinimo terminas')),
                ('provider_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Paslaugų teikėjo pavadinimas')),
                ('procurement', models.URLField(blank=True, null=True, verbose_name='Nuoroda į viešąjį pirkimą')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Pirkimo kaina EUR')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Uždarytas')),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Įtraukimo data')),
            ],
            options={
                'db_table': 'plan_dataset',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Aprašymas')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Projekto pradžios data')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Projekto pabaigos data')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Projekto biudžetas')),
                ('procurement', models.URLField(blank=True, null=True, verbose_name='Viešasis pirkimas')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Įtraukimo data')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_plans.plan', verbose_name='Planas')),
            ],
            options={
                'db_table': 'plan_request',
            },
        ),
    ]
