# Generated by Django 3.2.14 on 2022-09-09 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingPlanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('financing_plan_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'financing_plan_state',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NationalFinancingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(blank=True, null=True)),
                ('confirmed_budget', models.BigIntegerField(blank=True, null=True)),
                ('confirmed_by', models.BigIntegerField(blank=True, null=True)),
                ('estimated_budget', models.BigIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True, unique=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'national_financing_plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinancingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField()),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('financed_datasets', models.IntegerField(blank=True, null=True)),
                ('financing_plan_state_id', models.BigIntegerField(blank=True, null=True)),
                ('projected_cost', models.IntegerField(blank=True, null=True)),
                ('projected_datasets', models.IntegerField(blank=True, null=True)),
                ('received_financing', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vitrina_orgs.organization')),
            ],
            options={
                'db_table': 'financing_plan',
                'managed': True,
                'unique_together': {('organization', 'year')},
            },
        ),
    ]
