# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vitrina_datasets', '0002_initial'),
        ('vitrina_plans', '0001_initial'),
        ('vitrina_requests', '0001_initial'),
        ('vitrina_orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planrequest',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_requests.request', verbose_name='Poreikis'),
        ),
        migrations.AddField(
            model_name='plandataset',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_datasets.dataset', verbose_name='Duomenų rinkinys'),
        ),
        migrations.AddField(
            model_name='plandataset',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_plans.plan', verbose_name='Planas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_plans.project', verbose_name='Projektas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publisher_plans', to='vitrina_orgs.organization', verbose_name='Duomenų atvėrimo paslaugų teikėjas'),
        ),
        migrations.AddField(
            model_name='plan',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver_plans', to='vitrina_orgs.organization', verbose_name='Paslaugų gavėjas'),
        ),
    ]
