# Generated by Django 3.2.20 on 2023-09-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Uždarytas'),
        ),
    ]
