# Generated by Django 3.2.25 on 2025-03-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0003_auto_20250313_1841'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vitrina_requests', '0003_request_dataset'),
        ('vitrina_orgs', '0002_initial'),
        ('vitrina_plans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financingplan',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financingplan',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vitrina_orgs.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='financingplan',
            unique_together={('organization', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='plandataset',
            unique_together={('plan', 'dataset')},
        ),
        migrations.AlterUniqueTogether(
            name='planrequest',
            unique_together={('plan', 'request')},
        ),
    ]
