# Generated by Django 3.2.25 on 2025-01-27 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_plans', '0003_auto_20241230_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financingplan',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='financingplanstate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='nationalfinancingplan',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_plans.project', verbose_name='Projektas'),
        ),
    ]
