# Generated by Django 3.2.25 on 2025-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
        ('vitrina_datasets', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'distribution_format',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('extension', models.TextField(blank=True, null=True, verbose_name='Failo plėtinys')),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('mimetype', models.TextField(blank=True, null=True, verbose_name='MIME tipas')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Vertinimas')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Pavadinimas')),
                ('uri', models.CharField(blank=True, max_length=255, verbose_name='Formato nuoroda į kontroliuojamą žodyną')),
                ('media_type_uri', models.CharField(blank=True, max_length=255, verbose_name='Laikmenos tipo nuoroda į kontroliuojamą žodyną')),
            ],
            options={
                'verbose_name': 'Formatas',
                'verbose_name_plural': 'Formatai',
                'db_table': 'format',
            },
        ),
        migrations.CreateModel(
            name='GeoportalFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_resources.format', verbose_name='Formatas')),
            ],
            options={
                'verbose_name': 'Geoportalo formatas',
                'verbose_name_plural': 'Geoportalo formatai',
                'db_table': 'geoportal_format',
            },
        ),
        migrations.CreateModel(
            name='GeoportalFormatValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Reikšmė')),
                ('geoportal_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vitrina_resources.geoportalformat', verbose_name='Geoportalo formatas')),
            ],
            options={
                'verbose_name': 'Geoportalo formato reikšmė',
                'verbose_name_plural': 'Geoportalo formato reikšmės',
                'db_table': 'geoportal_format_value',
            },
        ),
        migrations.CreateModel(
            name='DatasetDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('deleted', models.BooleanField(blank=True, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('access_url', models.CharField(blank=True, help_text='Nuoroda į svetainę iš kurios galima atsisiųsti duomenis.', max_length=255, verbose_name='Prieigos nuoroda')),
                ('download_url', models.TextField(blank=True, help_text='Tiesioginė duomenų atsisiuntimo nuoroda.', null=True, verbose_name='Atsisiuntimo nuoroda')),
                ('geo_location', models.CharField(blank=True, max_length=255, verbose_name='Geografinė aprėptis')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Periodo pradžia')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Periodo pabaiga')),
                ('distribution_version', models.IntegerField(blank=True, null=True)),
                ('issued', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_parameterized', models.BooleanField(default=False, verbose_name='Parametrizuotas')),
                ('upload_to_storage', models.BooleanField(default=False, verbose_name='Įkėlimas į saugyklą')),
                ('imported', models.BooleanField(default=False, verbose_name='Importuojamas išorinis metaduomenų katalogas')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('data_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_service_distributions', to='vitrina_datasets.dataset')),
                ('file', filer.fields.file.FilerFileField(blank=True, help_text='Atvirų duomenų katalogas nėra skirtas duomenų talpinimui ir įprastinių atveju duomenys turėtu būti talpinami atvirų duomenų Saugykloje ar kitoje vietoje, pateikiant tiesioginę duomenų atsisiuntimo nuorodą. Tačiau nedidelės apimties (iki 5Mb) duomenų failus, galima talpinti ir kataloge.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_distribution', to='filer.file', verbose_name='Duomenų failas')),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.format', verbose_name='Duomenų formatas')),
            ],
            options={
                'db_table': 'dataset_distribution',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatasetDistributionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Pavadinimas')),
                ('description', models.TextField(blank=True, verbose_name='Aprašymas')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='vitrina_resources.datasetdistribution')),
            ],
            options={
                'verbose_name': 'dataset distribution Translation',
                'db_table': 'dataset_distribution_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
