# Generated by Django 3.2.14 on 2022-09-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetdistribution',
            options={},
        ),
    ]
