# Generated by Django 3.2.14 on 2022-09-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0002_alter_datasetdistribution_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='filename',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='data/'),
        ),
    ]
