# Generated by Django 3.2.25 on 2025-04-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0002_datasetdistribution_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=255, null=True, verbose_name='Failo plėtinys')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Pavadinimas')),
                ('uri', models.CharField(blank=True, max_length=255, verbose_name='Formato nuoroda į kontroliuojamą žodyną')),
            ],
            options={
                'verbose_name': 'Suspausto failo formatas',
                'verbose_name_plural': 'Suspausto failo formatai',
                'db_table': 'compression_format',
            },
        ),
        migrations.CreateModel(
            name='PackagingFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=255, null=True, verbose_name='Failo plėtinys')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Pavadinimas')),
                ('uri', models.CharField(blank=True, max_length=255, verbose_name='Formato nuoroda į kontroliuojamą žodyną')),
            ],
            options={
                'verbose_name': 'Suspausto failų paketo formatas',
                'verbose_name_plural': 'Suspausto failų paketo formatai',
                'db_table': 'packaging_format',
            },
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_distributions', to='vitrina_resources.format', verbose_name='Duomenų formatas'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='compression_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.compressionformat', verbose_name='Suspausto failo formatas'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='packaging_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.packagingformat', verbose_name='Suspausto failų paketo formatas'),
        ),
    ]
