# Generated by Django 3.2.25 on 2025-03-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "vitrina_classifiers",
            "0003_populate",
        ),
        ("vitrina_resources", "0002_datasetdistribution_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetdistribution",
            name="licence",
            field=models.ForeignKey(
                db_column="licence",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vitrina_classifiers.licence",
                verbose_name="Licencija",
            ),
        ),
    ]
