# Generated by Django 3.2.25 on 2025-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_datasets", "0008_hvd_category_and_dataset_type"),
        ("vitrina_resources", "0003_auto_20250428_0653"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetdistribution",
            name="applicable_legislation",
            field=models.ManyToManyField(
                help_text="Nuoroda į taikomą teisęs aktą",
                to="vitrina_datasets.LegalResource",
                verbose_name="Taikomi teisės aktai",
            ),
        ),
    ]
