# Generated by Django 3.2.25 on 2025-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0003_auto_20250428_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='last_modified_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='last_size_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
