# Generated by Django 3.2.25 on 2025-07-14 05:04

from django.db import migrations, models
import django.db.models.deletion


def migrate_licences_and_conditions(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")

    for distribution in DatasetDistribution.objects.all():
        if distribution.dataset:
            distribution.licence = distribution.dataset.licence
            distribution.conditions = distribution.dataset.distribution_conditions
            distribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0004_alter_category_groups'),
        ('vitrina_resources', '0003_auto_20250428_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_classifiers.licence', verbose_name='Licencija'),
        ),
        migrations.AddField(
            model_name='datasetdistributiontranslation',
            name='conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Platinimo sąlygos'),
        ),
        migrations.RunPython(migrate_licences_and_conditions),
    ]
