# Generated by Django 3.2.25 on 2025-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0011_applicablelegislation'),
        ('vitrina_resources', '0004_auto_20250714_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='applicable_legislation',
            field=models.ManyToManyField(blank=True, related_name='dataset_distributions', to='vitrina_classifiers.ApplicableLegislation', verbose_name='Teisinis pagrindas'),
        ),
    ]
