# Generated by Django 3.2.25 on 2025-06-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0004_auto_20250714_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='last_size_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
