# Generated by Django 3.2.25 on 2025-08-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0004_auto_20250714_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='spatial_resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Erdvinė skiriamoji geba (metrais)'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='temporal_resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Laiko skiriamoji geba (sekundėmis)'),
        ),
    ]
