# Generated by Django 3.2.25 on 2025-08-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0013_applicablelegislation'),
        ('vitrina_resources', '0005_auto_20250821_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='applicable_legislation',
            field=models.ManyToManyField(blank=True, related_name='dataset_distributions', to='vitrina_classifiers.ApplicableLegislation', verbose_name='Teisinis pagrindas'),
        ),
    ]
