# Generated by Django 3.2.25 on 2025-08-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0005_auto_20250821_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='rights_relation',
            field=models.URLField(blank=True, help_text='Teisių deklaracijos nuoroda. Atitinka dct:relation.', max_length=1024, null=True, verbose_name='Platinimo sąlygų nuoroda'),
        ),
        migrations.AlterField(
            model_name='datasetdistributiontranslation',
            name='conditions',
            field=models.TextField(blank=True, help_text='Laisvu tekstu pateikiamas teisių deklaracijos aprašymas. Atitinka dct:description.', null=True, verbose_name='Platinimo sąlygos'),
        ),
    ]
