# Generated by Django 3.2.25 on 2025-08-26 14:06

from django.db import migrations, models
import django.db.models.deletion
import vitrina.resources.models


def populate_existing_rows(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    completed = Concept.objects.get(code="COMPLETED")
    develop = Concept.objects.get(code="DEVELOP")

    for distribution in DatasetDistribution.objects.all():
        if distribution.dataset.access_rights == "PUBLIC":
            distribution.status = completed
        else:
            distribution.status = develop
        distribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0016_concepts_with_distribution_status'),
        ('vitrina_resources', '0006_datasetdistribution_applicable_legislation'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept'),
        ),
        migrations.RunPython(populate_existing_rows),

        migrations.AlterField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(default=vitrina.resources.models.get_default_status, help_text='Duomenų distribucija gali būti kuriama, suplanuota kūrimui arba įgyvendinta - veikianti.', on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept', verbose_name='Duomenų distribucijos būsena.'),
        )
    ]
