# Generated by Django 3.2.25 on 2025-09-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0007_auto_20250822_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='rights_relation',
            field=models.URLField(blank=True, help_text='Teisių deklaracijos nuoroda. Atitinka dct:rights / dct:relation.', max_length=1024, null=True, verbose_name='Teisės - Susijęs dokumentas'),
        ),
        migrations.AlterField(
            model_name='datasetdistributiontranslation',
            name='conditions',
            field=models.TextField(blank=True, help_text='Laisvu tekstu pateikiamas teisių deklaracijos aprašymas. Atitinka dct:rights / dct:description.', null=True, verbose_name='Teisės - Aprašymas'),
        ),
    ]
