# Generated by Django 3.2.25 on 2025-08-26 14:06

from django.db import migrations, models
import django.db.models.deletion
import vitrina.resources.models


def populate_existing_rows(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")
    Concept = apps.get_model("vitrina_classifiers", "Concept")

    completed = Concept.objects.get(code="COMPLETED")
    develop = Concept.objects.get(code="DEVELOP")

    DatasetDistribution.objects.filter(dataset__access_rights="PUBLIC").update(status=completed)
    DatasetDistribution.objects.exclude(dataset__access_rights="PUBLIC").update(status=develop)


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0015_concepts_with_distribution_status'),
        ('vitrina_resources', '0007_auto_20250822_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept'),
        ),
        migrations.RunPython(populate_existing_rows),

        migrations.AlterField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(default=vitrina.resources.models.get_default_status, help_text='Duomenų distribucija gali būti įgyvendinta - veikianti, kuriama, suplanuota kūrimui, pasenusi arba atsisakyta.', on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept', verbose_name='Statusas'),
        )
    ]
