# Generated by Django 4.2.23 on 2025-10-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0007_base_version_enum_version_enumitem_version_and_more'),
        ('vitrina_resources', '0009_datasetdistribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='connected_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version'),
        ),
    ]
