# Generated by Django 4.2.23 on 2025-10-20 05:28

from django.db import migrations, models


def set_is_hvd_on_distributions(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")

    for dist in DatasetDistribution.objects.filter(
        dataset__category__groups__translations__title="Didelės vertės rinkiniai"
    ):
        dist.is_hvd = True
        dist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0009_datasetdistribution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='is_hvd',
            field=models.BooleanField(default=False, verbose_name='Ar duomenų šaltinis yra didelės vertės'),
        ),
        migrations.RunPython(set_is_hvd_on_distributions),
    ]
