# Generated by Django 4.2.23 on 2025-12-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_structure', '0010_base_version_enum_version_enumitem_version_and_more'),
        ('vitrina_resources', '0010_datasetdistribution_is_hvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='metadata_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_structure.version'),
        ),
    ]
