# Generated by Django 3.2.16 on 2022-10-07 11:39
from django.db import migrations, models
import django.db.models.deletion


def fix_null(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")
    for resource in DatasetDistribution.objects.all():
        if resource.period_end is None:
            resource.period_end = ''
        if resource.period_start is None:
            resource.period_start = ''
        resource.save(update_fields=['period_start', 'period_end'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0010_alter_dataset_field'),
    ]

    operations = [
        migrations.RunPython(fix_null),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='period_end',
            field=models.CharField(blank=True, max_length=255, verbose_name='Periodo pabaiga'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='period_start',
            field=models.CharField(blank=True, max_length=255, verbose_name='Periodo pradžia'),
        ),
    ]
