# Generated by Django 3.2.16 on 2022-10-07 11:39
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0010_alter_dataset_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='period_end',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodo pabaiga'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='period_start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Periodo pradžia'),
        ),
    ]
