# Generated by Django 4.2.26 on 2026-01-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0011_datasetdistribution_metadata_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='access',
            field=models.IntegerField(blank=True, choices=[(0, 'nepasirinkta'), (1, 'private'), (2, 'protected'), (3, 'public'), (4, 'open')], null=True, verbose_name='Prieiga'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brandos lygis'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vardas'),
        ),
    ]
