# Generated by Django 3.2.16 on 2022-10-07 11:39
from django.db import migrations, models


def replace_null_values(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")

    for resource in DatasetDistribution.objects.all():
        if not resource.title:
            resource.title = ''
        if not resource.description:
            resource.description = ''
        resource.save(update_fields=['title', 'description'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0011_alter_periods'),
    ]

    operations = [
        migrations.RunPython(replace_null_values),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Aprašymas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Pavadinimas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
