# Generated by Django 4.2.26 on 2026-01-06 00:02

from django.db import migrations, models


def populate_new_distribution_fields(apps, schema_editor):
    DatasetDistribution = apps.get_model('vitrina_resources', 'DatasetDistribution')
    ContentType = apps.get_model("contenttypes", "ContentType")
    Metadata = apps.get_model('vitrina_structure', 'Metadata')
    dd_ct = ContentType.objects.get_for_model(DatasetDistribution)

    metadata_dict = {
        metadata['object_id']: metadata
        for metadata in Metadata.objects.filter(content_type=dd_ct).values(
            'object_id', 'name', 'access', 'level'
        )
    }
    distributions_to_update = []
    for dataset_distribution in DatasetDistribution.objects.all():
        if metadata_instance := metadata_dict.get(dataset_distribution.id):
            dataset_distribution.name = metadata_instance['name']
            dataset_distribution.access = metadata_instance['access']
            dataset_distribution.level = metadata_instance['level']
            distributions_to_update.append(dataset_distribution)

    if distributions_to_update:
        DatasetDistribution.objects.bulk_update(
            distributions_to_update,
            ['name', 'access', 'level'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0011_datasetdistribution_metadata_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='access',
            field=models.IntegerField(blank=True,choices=[(0, 'private'), (1, 'protected'), (2, 'public'), (3, 'open')], null=True,verbose_name='Prieiga'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Brandos lygis'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Vardas'),
        ),
        migrations.RunPython(populate_new_distribution_fields, migrations.RunPython.noop),
    ]
