# Generated by Django 4.2.28 on 2026-03-20 07:15

from django.db import migrations


def populate_json_and_openapi_formats(apps, schema_editor):
    Format = apps.get_model('vitrina_resources', 'Format')
    
    json_format, _ = Format.objects.get_or_create(title="JSON")
    json_format.extension = "json"
    json_format.mimetype = "application/json"
    json_format.rating = 3
    json_format.uri = "http://publications.europa.eu/resource/authority/file-type/JSON"
    json_format.media_type_uri = "https://www.iana.org/assignments/media-types/application/json"
    json_format.save()

    openapi_format, _ = Format.objects.get_or_create(title="OpenAPI")
    openapi_format.extension = ""
    openapi_format.mimetype = ""
    openapi_format.rating = None
    openapi_format.uri = ""
    openapi_format.media_type_uri = ""
    openapi_format.save()

class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0012_datasetdistribution_access_datasetdistribution_level_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_json_and_openapi_formats, migrations.RunPython.noop),
    ]
