# Generated by Django 3.2.16 on 2022-11-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0012_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo pabaiga'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Periodo pradžia'),
        ),
    ]
