# Generated by Django 4.2.26 on 2026-02-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_resources", "0013_populate_json_and_openapi_formats"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetdistribution",
            name="data_last_updated",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
