# Generated by Django 4.2.29 on 2026-05-07 11:07

from django.db import migrations, models
import django.db.models.deletion
import vitrina.resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0018_add_udts_concept'),
        ('vitrina_resources', '0014_add_data_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(default=vitrina.resources.models.get_default_status, help_text='Pateiktis gali būti įgyvendinta - veikianti, kuriama, suplanuota kūrimui, pasenusi arba atsisakyta.', on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept', verbose_name='Statusas'),
        ),
    ]
