# Generated by Django 4.2.29 on 2026-04-30 08:08

from django.db import migrations, models
import django.db.models.deletion
import vitrina.resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0019_activity_provenancestatement_rule_servicequalitypage_and_more'),
        ('vitrina_datasets', '0043_dataset_dataset_type_dataset_follows_and_more'),
        ('vitrina_resources', '0016_alter_datasetdistribution_is_hvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='access_url',
            field=models.CharField(blank=True, help_text='Nuoroda į svetainę, kurioje galima rasti tiesiogines duomenų atsisiuntimo nuorodas. Atitinka dcat:accessUrl.', max_length=255, verbose_name='Prieigos nuoroda'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='compression_format',
            field=models.ForeignKey(blank=True, help_text='Ši savybė nurodo failo, kuriame yra duomenys, formatą suspaustoje formoje. Atitinka dcat:compressFormat.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.compressionformat', verbose_name='Suspausto failo formatas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='data_service',
            field=models.ForeignKey(help_text='Duomenų paslauga, per kurią prieinama duomenų pateiktis. Atitinka dcat:accessService.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_service_distributions', to='vitrina_datasets.dataset', verbose_name='Duomenų paslauga'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='download_url',
            field=models.TextField(blank=True, help_text='Tiesioginė duomenų atsisiuntimo nuoroda. Ši nuoroda turi rodyti tiesiogiai į CSV, JSON ar kito formato duomenų failą. Atitinka dcat:downloadURL.', null=True, verbose_name='Atsisiuntimo nuoroda'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='format',
            field=models.ForeignKey(help_text='Pateikties failų formatas. Atitinka dct:format.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_distributions', to='vitrina_resources.format', verbose_name='Duomenų formatas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='licence',
            field=models.ForeignKey(blank=True, help_text='Licencija, pagal kurią platinamas pateikimas. Atitinka dct:license.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_classifiers.licence', verbose_name='Licencija'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kodinis pavadinimas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='packaging_format',
            field=models.ForeignKey(blank=True, help_text='Ši savybė nurodo failo, kuriame yra vienas ar daugiau duomenų, formatą. Atitinka dcat:packageFormat.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.packagingformat', verbose_name='(Failų) Pakavimo formatas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(default=vitrina.resources.models.get_default_status, help_text='Nurodomas pateikties brandos lygmuo. Atitinka adms:status.', on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept', verbose_name='Statusas'),
        ),
    ]
