# Generated by Django 3.2.19 on 2023-07-11 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0015_auto_20230608_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='is_parameterized',
            field=models.BooleanField(default=False, verbose_name='Parametrizuotas'),
        ),
    ]
