# Generated by Django 4.2.29 on 2026-05-04 10:55

from django.db import migrations, models
import django.db.models.deletion


def add_concept_schemas(apps, schema_editor):
    ConceptSchema = apps.get_model("vitrina_classifiers", "ConceptSchema")

    schema, created = ConceptSchema.objects.get_or_create(
        uri="http://publications.europa.eu/resource/authority/planned-availability"
    )
    schema.set_current_language("lt")
    schema.label = "Planuojamas prieinamumas"
    schema.description = "Planuojamas prieinamumas"
    schema.set_current_language("en")
    schema.label = "Planned availability"
    schema.description = "Planned availability"
    schema.save()

    schema, created = ConceptSchema.objects.get_or_create(
        uri="https://data.gov.lt/id/non-standard/DistributionStandard"
    )
    schema.set_current_language("lt")
    schema.label = "Pateikties standartas"
    schema.description = "Pateikties standartas. Atitinka dct:conformsTo."
    schema.set_current_language("en")
    schema.label = "Distribution standard"
    schema.description = "Distribution standard. Corresponds to dct:conformsTo."
    schema.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0019_activity_provenancestatement_rule_servicequalitypage_and_more'),
        ('vitrina_datasets', '0043_dataset_dataset_type_dataset_follows_and_more'),
        ('vitrina_resources', '0015_alter_datasetdistribution_access_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='availability',
            field=models.ForeignKey(blank=True, help_text='Ši savybė nurodo, kiek laiko planuojama išlaikyti duomenų rinkinio platinimą. Atitinka dcatap:availability.', limit_choices_to={'concept_schemas__uri': 'http://publications.europa.eu/resource/authority/planned-availability'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='vitrina_classifiers.concept', verbose_name='Prieinamumas'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='checksum_algorithm',
            field=models.CharField(blank=True, choices=[('SHA1', 'SHA1'), ('SHA224', 'SHA224'), ('SHA256', 'SHA256'), ('SHA384', 'SHA384'), ('SHA512', 'SHA512'), ('SHA3-256', 'SHA3-256'), ('SHA3-384', 'SHA3-384'), ('SHA3-512', 'SHA3-512'), ('BLAKE2b-256', 'BLAKE2b-256'), ('BLAKE2b-384', 'BLAKE2b-384'), ('BLAKE2b-512', 'BLAKE2b-512'), ('BLAKE3', 'BLAKE3'), ('MD2', 'MD2'), ('MD4', 'MD4'), ('MD5', 'MD5'), ('MD6', 'MD6'), ('ADLER32', 'ADLER32')], help_text='Algoritmas, naudojamas objekto kontrolinei sumai sukurti. Atitinka spdx:algorithm.', max_length=20, null=True, verbose_name='Kontrolinės sumos algoritmas'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='checksum_value',
            field=models.CharField(blank=True, help_text='Šešioliktaine sistema užkoduota kontrolinės sumos reikšmė. Atitinka spdx:checksumValue.', max_length=255, null=True, verbose_name='Kontrolinės sumos reikšmė'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='conforms_to',
            field=models.ManyToManyField(blank=True, help_text='Nurodo, kokį standartą ar schemą atitinka pateiktis. Atitinka dct:conformsTo.', related_name='distribution_conforms_to', to='vitrina_classifiers.concept', verbose_name='Susijusi schema'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='date_modified',
            field=models.DateField(blank=True, help_text='Paskutinio pateikties atnaujinimo ar pakeitimo data. Atitinka dct:modified.', null=True, verbose_name='Atnaujinimo / pakeitimo data'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='documentation',
            field=models.ManyToManyField(blank=True, help_text='Nuorodos į dokumentus su informacija apie pateiktį. Atitinka foaf:page.', related_name='distributions', to='vitrina_datasets.documentation', verbose_name='Puslapis (dokumentacija)'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Ši savybė nurodo pateikties kalbą. Atitinka dct:language.', limit_choices_to={'concept_schemas__uri': 'http://publications.europa.eu/resource/authority/language'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='vitrina_classifiers.concept', verbose_name='Kalba'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='issued',
            field=models.CharField(blank=True, help_text='Data, kada pateiktis buvo pirmą kartą išleista. Atitinka dct:issued.', max_length=255, null=True, verbose_name='Išleista'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='Pateikties dydis baitais. Atitinka dcat:byteSize.', null=True, verbose_name='Dydis baitais'),
        ),
        migrations.RunPython(add_concept_schemas, migrations.RunPython.noop),
    ]
