# Generated by Django 3.2.16 on 2023-06-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0017_merge_20230629_0914'),
        ('vitrina_resources', '0015_auto_20230608_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='data_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_service_distributions', to='vitrina_datasets.dataset'),
        ),
    ]
