# Generated by Django 3.2.19 on 2023-07-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0016_auto_20230629_1124'),
        ('vitrina_resources', '0016_auto_20230711_0812'),
    ]

    operations = [
    ]
