# Generated by Django 4.2.29 on 2026-05-28 08:09

from django.db import migrations, models
import django.db.models.deletion
import uuid
import vitrina.resources.models


INITIAL_MEDIA_TYPES = [
    ("application", "https://www.w3.org/ns/iana/media-types/application"),
    ("audio",       "https://www.w3.org/ns/iana/media-types/audio"),
    ("example",     "https://www.w3.org/ns/iana/media-types/example"),
    ("font",        "https://www.w3.org/ns/iana/media-types/font"),
    ("haptics",     "https://www.w3.org/ns/iana/media-types/haptics"),
    ("image",       "https://www.w3.org/ns/iana/media-types/image"),
    ("message",     "https://www.w3.org/ns/iana/media-types/message"),
    ("model",       "https://www.w3.org/ns/iana/media-types/model"),
    ("multipart",   "https://www.w3.org/ns/iana/media-types/multipart"),
    ("text",        "https://www.w3.org/ns/iana/media-types/text"),
    ("video",       "https://www.w3.org/ns/iana/media-types/video"),
]


def create_media_types(apps, schema_editor):
    MediaType = apps.get_model("vitrina_resources", "MediaType")
    MediaType.objects.bulk_create([
        MediaType(uuid=uuid.uuid4(), title=title, uri=uri)
        for title, uri in INITIAL_MEDIA_TYPES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_datasets', '0043_remove_dataset_information_system_creator_and_more'),
        ('vitrina_classifiers', '0019_activity_formfieldhelptext_provenancestatement_rule_and_more'),
        ('vitrina_resources', '0016_alter_datasetdistribution_is_hvd'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('uri', models.URLField(max_length=255, unique=True, verbose_name='Nuoroda į kontroliuojamą žodyną')),
            ],
            options={
                'verbose_name': 'Medijos tipas',
                'verbose_name_plural': 'Medijos tipai',
            },
        ),
        migrations.RunPython(create_media_types, migrations.RunPython.noop),
        migrations.AddField(
            model_name='datasetdistribution',
            name='availability',
            field=models.ForeignKey(blank=True, help_text='Ši savybė nurodo, kiek laiko planuojama išlaikyti duomenų rinkinio platinimą. Atitinka dcatap:availability.', limit_choices_to={'concept_schemas__uri': 'http://publications.europa.eu/resource/authority/planned-availability'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='vitrina_classifiers.concept', verbose_name='Prieinamumas'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='checksum_algorithm',
            field=models.CharField(blank=True, choices=[('SHA1', 'SHA1'), ('SHA224', 'SHA224'), ('SHA256', 'SHA256'), ('SHA384', 'SHA384'), ('SHA512', 'SHA512'), ('SHA3-256', 'SHA3-256'), ('SHA3-384', 'SHA3-384'), ('SHA3-512', 'SHA3-512'), ('BLAKE2b-256', 'BLAKE2b-256'), ('BLAKE2b-384', 'BLAKE2b-384'), ('BLAKE2b-512', 'BLAKE2b-512'), ('BLAKE3', 'BLAKE3'), ('MD2', 'MD2'), ('MD4', 'MD4'), ('MD5', 'MD5'), ('MD6', 'MD6'), ('ADLER32', 'ADLER32')], help_text='Algoritmas, naudojamas objekto kontrolinei sumai sukurti. Atitinka spdx:algorithm.', max_length=20, null=True, verbose_name='Kontrolinės sumos algoritmas'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='checksum_value',
            field=models.CharField(blank=True, help_text='Šešioliktaine sistema užkoduota kontrolinės sumos reikšmė. Atitinka spdx:checksumValue.', max_length=255, null=True, verbose_name='Kontrolinės sumos reikšmė'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='conforms_to',
            field=models.ManyToManyField(blank=True, help_text='Nurodo, kokį standartą ar schemą atitinka pateiktis. Atitinka dct:conformsTo.', related_name='distribution_conforms_to', to='vitrina_classifiers.concept', verbose_name='Susijusi schema'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='date_modified',
            field=models.DateField(blank=True, help_text='Paskutinio pateikties atnaujinimo ar pakeitimo data. Atitinka dct:modified.', null=True, verbose_name='Atnaujinimo / pakeitimo data'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='documentation',
            field=models.ManyToManyField(blank=True, help_text='Nuorodos į dokumentus su informacija apie pateiktį. Atitinka foaf:page.', related_name='distributions', to='vitrina_datasets.documentation', verbose_name='Puslapis (dokumentacija)'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Ši savybė nurodo pateikties kalbą. Atitinka dct:language.', limit_choices_to={'concept_schemas__uri': 'http://publications.europa.eu/resource/authority/language'}, to='vitrina_classifiers.concept', verbose_name='Kalbos'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='access_url',
            field=models.CharField(blank=True, help_text='Nuoroda į svetainę, kurioje galima rasti tiesiogines duomenų atsisiuntimo nuorodas. Atitinka dcat:accessUrl.', max_length=255, verbose_name='Prieigos nuoroda'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='compression_format',
            field=models.ForeignKey(blank=True, help_text='Ši savybė nurodo failo, kuriame yra duomenys, formatą suspaustoje formoje. Atitinka dcat:compressFormat.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.compressionformat', verbose_name='Suspausto failo formatas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='data_service',
            field=models.ForeignKey(help_text='Duomenų paslauga, per kurią prieinama duomenų pateiktis. Atitinka dcat:accessService.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_service_distributions', to='vitrina_datasets.dataset', verbose_name='Duomenų paslauga'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='download_url',
            field=models.TextField(blank=True, help_text='Tiesioginė duomenų atsisiuntimo nuoroda. Ši nuoroda turi rodyti tiesiogiai į CSV, JSON ar kito formato duomenų failą. Atitinka dcat:downloadURL.', null=True, verbose_name='Atsisiuntimo nuoroda'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='format',
            field=models.ForeignKey(help_text='Pateikties failų formatas. Atitinka dct:format.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='format_distributions', to='vitrina_resources.format', verbose_name='Duomenų formatas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='issued',
            field=models.CharField(blank=True, help_text='Data, kada pateiktis buvo pirmą kartą išleista. Atitinka dct:issued.', max_length=255, null=True, verbose_name='Išleista'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='licence',
            field=models.ForeignKey(blank=True, help_text='Licencija, pagal kurią platinamas pateikimas. Atitinka dct:license.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_classifiers.licence', verbose_name='Licencija'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kodinis pavadinimas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='packaging_format',
            field=models.ForeignKey(blank=True, help_text='Ši savybė nurodo failo, kuriame yra vienas ar daugiau duomenų, formatą. Atitinka dcat:packageFormat.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.packagingformat', verbose_name='(Failų) Pakavimo formatas'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='Pateikties dydis baitais. Atitinka dcat:byteSize.', null=True, verbose_name='Dydis baitais'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(blank=True, default=vitrina.resources.models.get_default_status, help_text='Nurodomas pateikties brandos lygmuo. Atitinka adms:status.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept', verbose_name='Statusas'),
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='media_type',
            field=models.ForeignKey(blank=True, help_text='Pateikties medijos tipas. Atitinka dcat:mediaType.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.mediatype', verbose_name='Medijos tipas'),
        ),
    ]
