# Generated by Django 4.2.29 on 2026-05-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0017_datasetdistribution_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='is_hvd',
            field=models.BooleanField(default=False, verbose_name='Ar pateiktis yra didelės vertės'),
        ),
    ]
