# Generated by Django 4.2.30 on 2026-08-05 08:21

from django.db import migrations, models
import vitrina.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0017_mediatype_datasetdistribution_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='rights_relation',
            field=models.CharField(blank=True, help_text='Teisių deklaracijos nuoroda. Atitinka dct:rights / dct:relation.', max_length=1024, null=True, validators=[vitrina.validators.validate_absolute_uri], verbose_name='Teisės - Susijęs dokumentas'),
        ),
    ]
