# Generated by Django 4.2.29 on 2026-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0017_mediatype_datasetdistribution_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistribution',
            name='spatial_resolution',
            field=models.CharField(blank=True, help_text='Minimali erdvinė skiriamoji geba metrais. Atitinka dcat:spatialResolutionInMeters.', max_length=255, null=True, verbose_name='Erdvinė skiriamoji geba (metrais)'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='temporal_resolution',
            field=models.CharField(blank=True, help_text='Minimali laiko skiriamoji geba. Atitinka dcat:temporalResolution.', max_length=255, null=True, verbose_name='Laiko skiriamoji geba'),
        ),
        migrations.AlterField(
            model_name='datasetdistributiontranslation',
            name='conditions',
            field=models.TextField(blank=True, help_text='Laisvu tekstu pateikiamas teisių deklaracijos aprašymas. Atitinka dct:rights.', null=True, verbose_name='Teisės - Aprašymas'),
        ),
    ]
