# Generated by Django 4.2.29 on 2026-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0018_alter_datasetdistribution_spatial_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetdistribution',
            name='policy',
            field=models.TextField(blank=True, help_text='Pateikiama duomenų naudojimo politika, kuri yra susijusių taisyklių rinkinys, aprašoma pagal ODRL. Atitinka odrl:hasPolicy', null=True, verbose_name='Politika'),
        ),
    ]
