# Generated by Django 4.2.29 on 2026-05-14 07:51

from django.db import migrations, models
import django.db.models.deletion
import vitrina.resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_classifiers', '0019_activity_provenancestatement_rule_servicequalitypage_and_more'),
        ('vitrina_resources', '0018_alter_datasetdistribution_is_hvd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetdistribution',
            name='language',
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Ši savybė nurodo pateikties kalbą. Atitinka dct:language.', limit_choices_to={'concept_schemas__uri': 'http://publications.europa.eu/resource/authority/language'}, to='vitrina_classifiers.concept', verbose_name='Kalbos'),
        ),
        migrations.AlterField(
            model_name='datasetdistribution',
            name='status',
            field=models.ForeignKey(blank=True, default=vitrina.resources.models.get_default_status, help_text='Nurodomas pateikties brandos lygmuo. Atitinka adms:status.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dataset_distributions', to='vitrina_classifiers.concept', verbose_name='Statusas'),
        ),
    ]
