# Generated by Django 4.2.29 on 2026-06-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0019_datasetdistribution_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetdistributiontranslation',
            name='description',
            field=models.TextField(blank=True, help_text='Pateikties aprašymas. Atitinka dct:description.', verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='datasetdistributiontranslation',
            name='title',
            field=models.CharField(blank=True, help_text='Pateikties pavadinimas. Atitinka dct:title.', max_length=255, verbose_name='Pavadinimas'),
        ),
    ]
