# Generated by Django 3.2.23 on 2023-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0019_auto_20231208_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Formatas', 'verbose_name_plural': 'Formatai'},
        ),
        migrations.AddField(
            model_name='datasetdistribution',
            name='upload_to_storage',
            field=models.BooleanField(default=False, verbose_name='Įkėlimas į saugyklą'),
        ),
        migrations.AlterField(
            model_name='distributionformat',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='format',
            name='extension',
            field=models.TextField(blank=True, null=True, verbose_name='Failo plėtinys'),
        ),
        migrations.AlterField(
            model_name='format',
            name='mimetype',
            field=models.TextField(blank=True, null=True, verbose_name='MIME tipas'),
        ),
        migrations.AlterField(
            model_name='format',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vertinimas'),
        ),
        migrations.AlterField(
            model_name='format',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pavadinimas'),
        ),
    ]
