# Generated by Django 4.2.29 on 2026-05-21 12:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


INITIAL_MEDIA_TYPES = [
    ("application", "https://www.w3.org/ns/iana/media-types/application"),
    ("audio",       "https://www.w3.org/ns/iana/media-types/audio"),
    ("example",     "https://www.w3.org/ns/iana/media-types/example"),
    ("font",        "https://www.w3.org/ns/iana/media-types/font"),
    ("haptics",     "https://www.w3.org/ns/iana/media-types/haptics"),
    ("image",       "https://www.w3.org/ns/iana/media-types/image"),
    ("message",     "https://www.w3.org/ns/iana/media-types/message"),
    ("model",       "https://www.w3.org/ns/iana/media-types/model"),
    ("multipart",   "https://www.w3.org/ns/iana/media-types/multipart"),
    ("text",        "https://www.w3.org/ns/iana/media-types/text"),
    ("video",       "https://www.w3.org/ns/iana/media-types/video"),
]


def create_media_types(apps, schema_editor):
    MediaType = apps.get_model("vitrina_resources", "MediaType")
    MediaType.objects.bulk_create([
        MediaType(uuid=uuid.uuid4(), title=title, uri=uri)
        for title, uri in INITIAL_MEDIA_TYPES
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0019_remove_datasetdistribution_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Pavadinimas')),
                ('uri', models.URLField(max_length=255, unique=True, verbose_name='Nuoroda į kontroliuojamą žodyną')),
            ],
            options={
                'verbose_name': 'Medijos tipas',
                'verbose_name_plural': 'Medijos tipai',
            },
        ),
        migrations.RunPython(create_media_types, migrations.RunPython.noop),
        migrations.AddField(
            model_name='datasetdistribution',
            name='media_type',
            field=models.ForeignKey(blank=True, help_text='Pateikties medijos tipas. Atitinka dcat:mediaType.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrina_resources.mediatype', verbose_name='Medijos tipas'),
        ),
    ]
