# Generated by Django 3.2.25 on 2025-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_resources', '0020_auto_20231211_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='media_type_uri',
            field=models.CharField(blank=True, max_length=255, verbose_name='Laikmenos tipo nuoroda į kontroliuojamą žodyną'),
        ),
        migrations.AlterField(
            model_name='format',
            name='uri',
            field=models.CharField(blank=True, max_length=255, verbose_name='Formato nuoroda į kontroliuojamą žodyną'),
        ),
    ]
