# Generated by Django 3.2.25 on 2025-01-20 08:40
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

from vitrina import settings


def forwards_func(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")
    DatasetDistributionTranslation = apps.get_model(
        "vitrina_resources", "DatasetDistributionTranslation"
    )

    for dist in DatasetDistribution.objects.all():
        DatasetDistributionTranslation.objects.create(
            master_id=dist.pk,
            language_code="lt",
            title=dist.title_old,
            description=dist.description_old,
        )


def backwards_func(apps, schema_editor):
    DatasetDistribution = apps.get_model("vitrina_resources", "DatasetDistribution")
    DatasetDistributionTranslation = apps.get_model(
        "vitrina_resources", "DatasetDistributionTranslation"
    )

    for dist in DatasetDistribution.objects.all():
        translation = _get_translation(dist, DatasetDistributionTranslation)
        dist.title = translation.title
        dist.description = translation.description
        dist.save()  # Note this only calls Model.save()


def _get_translation(dist, DatasetDistributionTranslation):
    translations = DatasetDistributionTranslation.objects.filter(master_id=dist.pk)
    try:
        # Try default translation
        return translations.get(language_code=settings.LANGUAGE_CODE)
    except ObjectDoesNotExist:
        try:
            # Try default language
            return translations.get(language_code=settings.LANGUAGE_CODE)
        except ObjectDoesNotExist:
            # Maybe the object was translated only in a specific language?
            # Hope there is a single translation
            return translations.get()


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_resources", "0021_add_translation_model"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
