# Generated by Django 3.2.25 on 2025-01-20 08:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_resources", "0022_migrate_translatable_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datasetdistribution",
            name="title_old",
        ),
        migrations.RemoveField(
            model_name="datasetdistribution",
            name="description_old",
        ),
    ]
