# Generated by Django 3.2.14 on 2022-08-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
    ]