# Generated by Django 3.2.25 on 2025-03-13 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_users", "0001_initial"),
        ("otp_email", "0006_add_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmailDevice",
            fields=[
                (
                    "emaildevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="otp_email.emaildevice",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=40,
                        null=True,
                        verbose_name="IP adresas",
                    ),
                ),
                ("user_agent", models.TextField(blank=True, editable=False, null=True)),
            ],
            options={
                "db_table": "user_email_device",
                "managed": True,
            },
            bases=("otp_email.emaildevice",),
        ),
    ]
