# Generated by Django 3.2.15 on 2022-09-09 10:01

from django.db import migrations
from django.db.models import Q


def fix_passwords(apps, schema_editor):
    User = apps.get_model('vitrina_users', 'User')
    users = User.objects.exclude(Q(password__startswith='bcrypt$') | Q(password__startswith='pbkdf2_sha256$'))
    for user in users:
        user.password = "bcrypt$%s" % user.password
        user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0003_auto_20220816_1153'),
    ]

    operations = [
        migrations.RunPython(fix_passwords),
    ]
