# Generated by Django 4.2.23 on 2025-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0003_create_cms_and_blog_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_request_email',
            field=models.BooleanField(default=False),
        ),
    ]
