# Generated by Django 3.2.14 on 2022-09-09 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_orgs', '0001_initial'),
        ('vitrina_users', '0003_auto_20220816_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldpassword',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ssotoken',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usertablepreferences',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vitrina_orgs.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='needs_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
