# Generated by Django 4.2.23 on 2025-10-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0004_user_receive_request_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viisp_company_code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
