# Generated by Django 3.2.15 on 2022-09-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0004_auto_20220909_1301'),
        ('vitrina_users', '0005_auto_20220913_1408'),
    ]

    operations = [
    ]
