# Generated by Django 3.2.16 on 2022-10-27 08:09

from django.db import migrations

from vitrina import settings


def create_system_user(apps, schema_editor):
    User = apps.get_model('vitrina_users', 'User')
    User.objects.create(
        first_name="Sistemos",
        last_name="Naudotojas",
        email=settings.SYSTEM_USER_EMAIL,
        password="",
        is_staff=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0005_auto_20221010_1047'),
    ]

    operations = [
        migrations.RunPython(create_system_user)
    ]
