# Generated by Django 4.2.23 on 2025-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0005_user_viisp_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_viisp_login',
            field=models.BooleanField(default=False, help_text='Indikuoja, ar vartotojas yra prisijungęs per VIISP.', verbose_name='Vartotojas prisijungęs per VIISP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='viisp_company_code',
            field=models.CharField(blank=True, editable=False, help_text='Nurodomas įmonės kodas organizacijos, kurios vardu vartotojas yra prisijungęs per VIISP.', max_length=255, null=True, verbose_name='Vartotojo atstovaujama organizacija (VIISP)'),
        ),
    ]
