# Generated by Django 3.2.19 on 2023-09-05 13:10
from django.contrib.auth.hashers import make_password
from django.db import migrations


def fix_viisp_passwords(apps, schema_editor):
    User = apps.get_model('vitrina_users', 'User')

    for user in User.objects.filter(password="bcrypt$viisp"):
        user.password = make_password(None)
        user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0006_auto_20221027_1109'),
    ]

    operations = [
        migrations.RunPython(fix_viisp_passwords),
    ]
