# Generated by Django 4.2.29 on 2026-05-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_users", "0006_alter_user_is_viisp_login_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="version",
            new_name="model_version",
        ),
    ]
