# Generated by Django 4.2.30 on 2026-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0007_rename_version_user_model_version'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True), ('deleted_on__isnull', True), models.Q(('status', 'deleted'), _negated=True), models.Q(('email', ''), _negated=True)), fields=('email',), name='unique_active_user_email'),
        ),
    ]
