# Generated by Django 3.2.21 on 2023-10-02 06:20
from django.contrib.auth.hashers import make_password
from django.db import migrations


def fix_none_passwords(apps, schema_editor):
    User = apps.get_model('vitrina_users', 'User')

    for user in User.objects.filter(password="bcrypt$None"):
        user.password = make_password(None)
        user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0007_auto_20230905_1610'),
    ]

    operations = [
        migrations.RunPython(fix_none_passwords),
    ]
