# Generated by Django 4.2.29 on 2026-05-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina_users", "0007_rename_version_user_model_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Elektroninis paštas",
            ),
        ),
    ]
