# Generated by Django 3.2.25 on 2024-09-04 06:17

from django.db import migrations, models

ACTIVE = 'active'
AWAITING_CONFIRMATION = 'awaiting_confirmation'
SUSPENDED = 'suspended'
DELETED = 'deleted'


def assign_user_statuses(apps, schema_editor):
    User = apps.get_model('vitrina_users', 'User')

    for user in User.objects.all():
        if user.deleted:
            user.status = DELETED
        elif not user.is_active:
            user.status = SUSPENDED
        elif user.emailaddress_set.first() and not user.emailaddress_set.first().verified:
            user.status = AWAITING_CONFIRMATION
        else:
            user.status = ACTIVE
        user.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0008_auto_20231002_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldpassword',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='passwordresettoken',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ssotoken',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Naudotojas', 'verbose_name_plural': 'Naudotojai'},
        ),
        migrations.AlterModelOptions(
            name='usertablepreferences',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Aktyvus'), ('awaiting_confirmation', 'Laukiama patvirtinimo'), ('suspended', 'Suspenduotas'), ('deleted', 'Pašalintas')], max_length=255, null=True),
        ),
        migrations.RunPython(assign_user_statuses),
    ]
