# Generated by Django 3.2.25 on 2024-09-17 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_emails(apps, schema_editor):
    User = apps.get_model('vitrina_users', 'User')

    for user in User.objects.all():
        user.email_copy = user.email
        user.save(update_fields=['email_copy'])


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0009_auto_20240904_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_copy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Elektroninis paštas'),
        ),
        migrations.RunPython(copy_emails),
    ]
