# Generated by Django 3.2.25 on 2024-09-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0010_auto_20240917_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email_copy',
            new_name='email'
        )
    ]
