# Generated by Django 3.2.25 on 2024-10-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('otp_email', '0006_add_timestamps'),
        ('vitrina_users', '0011_auto_20240917_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailDevice',
            fields=[
                ('emaildevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_email.emaildevice')),
            ],
            options={
                'db_table': 'user_email_device',
            },
            bases=('otp_email.emaildevice',),
        ),
    ]
