# Generated by Django 3.2.25 on 2024-10-23 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0012_auto_20241016_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremaildevice',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresas'),
        ),
    ]
