# Generated by Django 3.2.25 on 2024-10-23 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0012_auto_20241018_1326'),
        ('vitrina_users', '0013_auto_20241023_1321'),
    ]

    operations = [
    ]
