# Generated by Django 3.2.25 on 2024-10-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrina_users', '0015_auto_20241024_0753'),
        ('vitrina_users', '0015_auto_20241024_0803'),
    ]

    operations = [
    ]
