# Generated by Django 3.2.25 on 2024-11-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vitrina_users", "0016_merge_0015_auto_20241024_0753_0015_auto_20241024_0803"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_viisp_login",
            field=models.BooleanField(default=False),
        ),
    ]
