name: 'Run tests'
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

env:
  DB_HOST: localhost
  DB_USERNAME: adp
  PGPASSWORD: secret


jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      localhost:
        image: postgres
        env:
          POSTGRES_USER: adp
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: adp-dev
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      # https://github.com/elastic/elastic-github-actions/tree/master/elasticsearch
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.8.1

      - name: Install dependencies
        run: poetry install

      - name: Load initial db schema
        run: PGPASSWORD=secret psql -h localhost -U adp -d adp-dev < resources/adp-dev-fresh.sql

      - name: Run migrations
        run: poetry run python manage.py migrate

      - name: Rename database to test
        run: PGPASSWORD=secret psql -h localhost -U adp postgres -c 'alter database "adp-dev" rename to "test_adp-dev";'

      - name: Test with pytest with `--reuse-db`
        run: poetry run pytest -vvxra --tb=short --reuse-db tests