name: 'Run tests'
on:
  push:
    branches:
      - 65-padaryti-github-ci
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Create DB image
        run: docker-compose up -d

      - name: Test with pytest
        run: poetry run pytest -vv