name: 'Run tests'
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      # https://github.com/elastic/elastic-github-actions/tree/master/elasticsearch
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.8.1

      - name: Install dependencies
        run: poetry install

      - name: Build static files
        run: |
          poetry run python manage.py collectstatic --noinput
          cd webpack
          npm install
          npm run build
  
      - name: Create DB image
        run: docker-compose -f docker-compose-test.yml up -d

      - name: Test with pytest
        run: poetry run pytest -vvra --no-migrations --tb=short --cov=vitrina --cov=report=term-missing tests
