name: 'Run tests'
on:
  push:
    branches:
      - devel
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --name redis
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libmagic1

      - name: Install dependencies
        run: poetry install

      - name: Build static files
        run: |
          poetry run python manage.py collectstatic --noinput
          cd webpack
          npm install
          npm run build

      - name: Create DB image
        run: docker compose -f docker-compose-test.yml up -d

      - name: Test with pytest
        run: poetry run pytest -vvra --tb=short --cov=vitrina --cov-report=term-missing tests
